### ISSUE TITLE
C20 - Spelling Mistake

### ISSUE THREAD

**Issue by millstream** [OP-TED/ESPD-EDM#105]
Is the economic operator aware of any conflict of interest, as indicated in national law, the relevant notice or **the** in the ESPD, the relevant notice or  due to its participation in the procurement procedure?

**Comment by ec-mcs** [comment]
We update the text

**Comment by paulakeen** [comment]
Corrected in v2.0.1 to be released on the Github 2.0.1 branch by the 25th February 2018:

1. The REGULATED version now reads: Is the economic operator aware of any conflict of interest, as indicated in national law, the relevant notice or in the ESPD, the relevant notice or due to its participation in the procurement procedure?
2. The SELF-CONTAINED version now reads: Is the economic operator aware of any conflict of interest, as indicated in the ESPD additionally to the national law or the relevant notice, the relevant notice or due to its participation in the procurement procedure?
