### ISSUE TITLE
XML Schema/XSD Validation issue in GITB Testbed

### ISSUE THREAD

**Issue by lotzmann** [OP-TED/ESPD-EDM#138]
The GITB Testbed does not properly test for XML Schema/XSD errors for ESPD version 1.0.2. For example, the representation of criterion 57 as implemented in the attached example artefact (and mentioned in    issue #137) passes the test, but should rather produce an XSD validation error like:
`cvc-complex-type.2.4.a: Invalid content was found starting with element 'ccv:RequirementGroup'. One of '{"urn:isa:names:specification:ubl:schema:xsd:CCV-CommonBasicComponents-1":FulfillmentIndicator, "urn:isa:names:specification:ubl:schema:xsd:CCV-CommonBasicComponents-1":FulfillmentIndicatorType, "urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2":Name, "urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2":Description, "urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2":TypeCode, "urn:isa:names:specification:ubl:schema:xsd:CCV-CommonAggregateComponents-1":Requirement}' is expected.`

[espd-request.zip](https://github.com/ESPD/ESPD-EDM/files/1840911/espd-request.zip)

**Comment by lotzmann** [comment]
Moved to https://github.com/ESPD/ESPD-Service/issues.

**Comment by GPsellitto** [comment]
in order to prepare the interoperability testing, we are using the online validator: http://isaitb2.northeurope.cloudapp.azure.com/espd/
We are testing the self-contained espd request v.2.0.2
It seems that the exceptions that are raised by the validator are mainly due to the difference between the value of the cbc:TypeCode contained in e-certis and the value used by the validator, as this seems coming from the EDM in GitHub https://github.com/ESPD/ESPD-EDM/tree/2.1.0/docs/src/main/asciidoc/dist/cl/xlsx
(example; where 
We are trying to align our values with the ones in the validator, but this has an impact on our system, since we perform a dynamic alignment with e-certis before the builder is started and in this case we shall stop the alignment to mantain something that comes from the taxonomy and not from e-Certis, moreover there is a problem of misalignment between the UUIDs for the criteria themselves (in the excel some UUID have undergone updates).
