### ISSUE TITLE
Global indication for all selection criteria (alpha section - part IV)

### ISSUE THREAD

**Issue by albenzio** [OP-TED/ESPD-EDM#142]
According to the ESPD (https://eur-lex.europa.eu/legal-content/IT/TXT/?uri=CELEX%3A32016R0007), an Economic Operator can satisfy  the required selection criteria with a single declaration, only if the Contracting Authority gives the permission for this possibility (**alpha section of Part IV - ESPD**).

I have probably missed it, but, is there a way to represent this option on the ESPD-EDM? 
If not, does the current version of ESPD-service provide a way to implement this solution (single click to meet all the selection criteria).
Given the possibility to reuse an ESPD response, I am not totally sure if this option should be supported in the data model.

Thanks in advance for your reply.

**Comment by paulakeen** [comment]
We do not have a specific data-structure for this "alpha criterion" in version 2.0.x. We made the decision that the existence of an alpha selection criteria would tempt MS to use it and consequently cripple any possibility of interoperability.

Having said that the effort of creating a data-structure for an alpha criterion is very low. If the decision is made because the legal context requires to do so it would take very little effort to have in, say, version 2.0.3. We'd also create the related schematron rules.

**Comment by paulakeen** [comment]
Solve in v2.0.3. See Issue #97 .
