### ISSUE TITLE
ESPD Self-contained 2.0.2: Criterion 35

### ISSUE THREAD

**Issue by AFSOLUZIONI** [OP-TED/ESPD-EDM#170]
Hi
i'm inserting now a lot of considerations we made in the last months.
I'm sorry if I bore you, but if think could be usefull.
For criterion 35 in the Requirement Group the Lot ID requirement is classifiede as a CAPTION and not as a REQUIREMENT.
I suppose a misprint.

Francesco

**Comment by AFSOLUZIONI** [comment]
Hi,
we go in deep in the analisys of criterion 35 and we've found a lot of possible issues to solve. More precisely:

1. Line 11 cardinality must be 1;
2. Line 12 is a "Requirement and not a "Caption" (as said in the previous comment)
3. Line 16 cardinality must be 1..n
4. the indentation seems to be not correct (in attach a proposal)

We made a parallel between taxonomy self-contained 2.0.2 and  ESPD-EDM XML_Guide VI.5.2 paragraph.

We considered the taxonomy as a "bible", and we concentrate our resources on develop SW to implement the management of information contained in it. Now we are in alpha-test phase and, in few week, we have the acceptance meeting ... we are in big troubles and I hope you can help us.
Regards

Francesco
[Criterio - 035-TEST.xlsx](https://github.com/ESPD/ESPD-EDM/files/2533841/Criterio.-.035-TEST.xlsx)

**Comment by paulakeen** [comment]
Dear Francesco,

About the CAPTION in line 14: your'e right, once again, this should have been declared as a REQUIREMENT. 

It'll be solved in v2.0.3.

**Comment by paulakeen** [comment]
About issue related to line 11:

1. Take into account that this Data Structure is used to reflect both views, the CA and the EO views (btw, this is why we have column 20, Value /example to simulate automatic Responses). 
2. The CA needs to be able to require more than one type of insurance. This explains why the group needs cardinality 1..n.
3. In this case, the EO will have to provide information for each of the Groups of Requirements requested by the CA.

Having said this, if you need to impose a very specific national or procedure-related constraint (cardinality 1 and only 1) the model doesn't restrict you to do so, because the cardinality is 1..n.

**Comment by paulakeen** [comment]
Relating to line 12: This needs to be a caption because the UBL-2.2 XSD schema requires a compulsory CriterionProperty element as the first element of the group. We do not like this UBL-2.2 design and we have proposed to change this cardinality from 1..n to 0..n. 

These CAPTIONS are intented for the software applications to have a literarl to identify a group of fields (imagine it as the label in the frame that is encompassing a group of field in a GUI).

**Comment by paulakeen** [comment]
About issues line 16 and the indentation proposal:

If we keep our current structure but modify the cardinality of line 16 to 1..n then the current data structure cater for the need of specificying more than one requirements per lot.

The current data structure provides more flexibility but we'll need to come up with a clear explanation, and examples, on how your objective can be achieved (and would facilitate backwards compatibility).

The explanation and example will be provided in v2.0.3.

**Comment by paulakeen** [comment]
About your concerns on your deadlines, please count on us to help streamline your problems. Your contribution is vital to ensure the ESPD-EDM SELF-CONTAINED model.

Thank you

**Comment by AFSOLUZIONI** [comment]
Hi Paula,
our comments started from a parallel between taxonomy and mock-up inside the ESPD-EDM document:
as you can se in the figure below, it seems we have more insurance inside each Lot-id group

![image](https://user-images.githubusercontent.com/44367854/48013323-55d69a80-e124-11e8-8e9e-c6e514440eca.png)
![image](https://user-images.githubusercontent.com/44367854/48015022-55400300-e128-11e8-8ee7-0f7c905a04f2.png)

I try to answer to your response:

Line 12 you're right I confused 12 with 14!!!
Line 11, in our opinion is the "envelope for all the iterations that are managed in line 16. Line 19 must be moved below line 31 to allow the right iteration of answers by OE.
Maybe I don't have so clear UBL and so on but the moke-up seems better represented from our structure.
Sorry I attached our own taxonomy but our goal is to give you an idea of what we change the indentation!.

Francesco

P.S. it's not so simple to exchange ideas with my poor and bad english!!!

**Comment by paulakeen** [comment]
About the indentation of the blocks containing the QUESTIONs addressed to the economic operator: you and  MariaSpr are right. Thank you for having pasted the mock-up. As it should be possible to add more than one type of insurance per set of lots specified by the buyer the cardinality has to be 1..n (as we mentioned in the previous correction) AND the blocks of questions need to go INSIDE the inner REQUIREMENT. So this is what we'll go to version 2.0.3:

![insurances](https://user-images.githubusercontent.com/16134316/48252181-5dd45a00-e404-11e8-947b-dcd78a27ab67.png)

Thank you!

**Comment by paulakeen** [comment]
Sorry, the previous screen-capture still contained errors. Please review that [this other version](https://github.com/ESPD/ESPD-EDM/blob/2.0.3/docs/src/main/asciidoc/dist/cl/xlsx/ESPD-CriteriaTaxonomy-SELFCONTAINED-V2.0.3.xlsx) is correct:

![c35](https://user-images.githubusercontent.com/16134316/48582362-9d2f0900-e924-11e8-88a4-175be504a345.png)

**Comment by mireiaBM** [comment]
This issue has been solved in version 2.1.0 of the ESPD-EDM
