### ISSUE TITLE
Criteria 1 to 6 (convictions)

### ISSUE THREAD

**Issue by AFSOLUZIONI** [OP-TED/ESPD-EDM#173]
Hi,
testing the criteria in re, we found an issues about "Element code":

in line 18, 48, 78, 108, 138 and 168 the "element code" must be "ON*" and not "ONTRUE" because there isn't an "INDICATOR" before them to activate the condition.
Are we right??

Francesco

**Comment by paulakeen** [comment]
Dear Francesco, 

You're absolutely right. Thank you for spotting this bug. We already have corrected in version 2.0.3.

**Comment by paulakeen** [comment]
This issue has been addressed in V2.0.3 and should be closed once reviewed by the WG.

**Comment by AFSOLUZIONI** [comment]
Hi  Paula,
we discover another issue (maybe) for the same criteria (from 1 to 6):
the first "QuestionGroup" for each criterion we think must have cardinality 1 instead of 1..n because we can give only 1 answer (I have convictions or not).
Are we wrong??

**Comment by paulakeen** [comment]
Yes, this was also raised in another issue and has been already fixed in the new version 2.0.3 we're about to release. 
![convictions](https://user-images.githubusercontent.com/16134316/48012999-9bdf2e80-e123-11e8-929d-7b4c9779db2e.png)


BTW, my username (avatar) is Paula Keen, but my name is Enric Staromiejski. ;D

**Comment by AFSOLUZIONI** [comment]
I had some dubt :-) :-) :-)
Next time I'll call you Enric!!!

**Comment by mireiaBM** [comment]
This issue has been solved in version 2.1.0 of the ESPD-EDM
