### ISSUE TITLE
Part IV, Section C (Technicians or technical bodies for quality control / For works contracts: technicians or technical bodies to carry out the work)

### ISSUE THREAD

**Issue by rantati7** [OP-TED/ESPD-EDM#19]
**For works contracts: technicians or technical bodies to carry out the work** 

CA must be able to define minimum criteria for technicians or technical bodies

It would be good if the question is shown only if works contracts in question.

**Comment by paulakeen** [comment]
We close this issue, for it's been unified with issue #15

**Comment by paulakeen** [comment]
Please find below what was commented about this issue in the discussion group:

Rudolf Maier: It is Asked for the following technicians, so the EO must have a possibility to explain.

Anne Katrine, NIRAS A/S, DK: Do you mean the requirements, Timo?

Timo Rantanen / Hansel / Finland: yes

Rudolf Maier: It is better the CA has additionally anrequirement field. There will be cases where this is necessary.

Anne Katrine, NIRAS A/S, DK: Yes. I would also suggest that "It" is changed.

Jose Luis Cueva (Spain): I think it is "context determined" by every contract, and even the Directive wording is quite lax

Rudolf Maier: Either more clear explanation in ESPD or to take it out of ESPD and it has to be described in the other proceedure documents..

Rudolf Maier: With technicians normally a detailled description of the work experience is asked for.

Marc-Christopher SCHMIDT: Technicians or technical bodies for quality control - we will add a requirement field (0..N) on CA side. On EO side each reuquirement has to agree

Timo Rantanen / Hansel / Finland: In this place the logic of ESDP differs from previous sections

Rudolf Maier: The tecnicians and their experience is often used as weighting criteria.

Rudolf Maier: Yes

Timo Rantanen / Hansel / Finland: not always but could happen (fro technicials) 

Jose Luis Cueva (Spain): a list with detailed info

Timo Rantanen / Hansel / Finland: I do not hink this will be used very often

Timo Rantanen / Hansel / Finland: no one understands how to use it 

Jose Luis Cueva (Spain): the form says " ... the following technicians..."

Jose Luis Cueva (Spain): profession or capability, experience, ...

Rudolf Maier: Yes, because the CA must have the chance to insist that exactlythis person will carry out thew contract/will be part of the team.

Marc-Christopher SCHMIDT: Answer from EO to technicians: Name (textfield), Experience (textfield)

Marc-Christopher SCHMIDT: Profession (type, textfield)

Timo Rantanen / Hansel / Finland: For example: the supplier must have two technicians with fire work permit

Marc-Christopher SCHMIDT: First/Last name, Profession, Certificates, Experience

Timo Rantanen / Hansel / Finland: I do not think the first and last names are necessary... just that the supplier confirms that they have these people at the time of concluting the conjtract

Rudolf Maier: Mostly  there is a (small) form for each person to be filled in. E.g. also how long somebody is  with the EO. But his will blow ESPD out of proportion.

Giampaolo Sellitto: certiicates from attestation bodies can be used 

Giampaolo Sellitto: ancd can be asked if a Quality assurance is requested to be in place

Giampaolo Sellitto: as weighting criteria

Timo Rantanen / Hansel / Finland: but in this place I may just want to ask that they have the required people at their disposal. I would ask the names elsewhere (in eTendering system) 

Timo Rantanen / Hansel / Finland: could be used in all

Jose Luis Cueva (Spain): we use it as pass/fail

Rudolf Maier: Can be also Past/Fail, but mostly weighting.

Jose Luis Cueva (Spain): with a threshold

Timo Rantanen / Hansel / Finland: exactly

John Degiorgio: Depends if it is a bpqr tender

Rudolf Maier: How long with the EO.

Timo Rantanen / Hansel / Finland: MC: see there is people but also technical bodies... 

John Degiorgio: experience is waived if tender is less than Eur500K to give opportunities to smses

Timo Rantanen / Hansel / Finland: so last name / First name not relevant

Timo Rantanen / Hansel / Finland: just name 

Timo Rantanen / Hansel / Finland: area of ...

Timo Rantanen / Hansel / Finland: expdertice

Timo Rantanen / Hansel / Finland: not experience but expertise area

Timo Rantanen / Hansel / Finland: expertise area is what I meant

Jose Luis Cueva (Spain): I suggest LastName/FirstName instead of just Name (fix the format)

Timo Rantanen / Hansel / Finland: I still do not think this is necessary in this place.... the CA can write what he requires in the requiremetn field

Anne Katrine, NIRAS A/S, DK: MC, That should be enoough.

Rudolf Maier: Clarification of difference between Quality control body and subcontractor.

Timo Rantanen / Hansel / Finland: if there is requirement box for CA, he can  rite what the EO needs to provide

Timo Rantanen / Hansel / Finland: write

Timo Rantanen / Hansel / Finland: there are so many variations for this 

Marc-Christopher SCHMIDT: Persons: First/Last name, Profession, Experience, Other information, How long with EOTechnical bodies: Name, Expertise area, Other information

Timo Rantanen / Hansel / Finland: This is what lawyers and IT people want: lists - but not often possible because of complexities of life

Jose Luis Cueva (Spain): we can provide a place for both: code and text

**Comment by paulakeen** [comment]
Please find below a proposal for the solution and mock-ups, as commented in the last meeting:

The CA will be able to add multiple requirements. 

The EO will need to provide, for each requirement:	
- Technicians (one or several). For each added technician, the following information will be required: First / Last name; Profession; Experience; Other information; How long with EO.

- Technical bodies (one or several). For each added technical body, the following information will be required: Name; Expertise area; Other information.

There's been a change in the description of the criterion (EO view).

View of the CA:
![image](https://cloud.githubusercontent.com/assets/16134316/25390740/afda543a-29d4-11e7-80b9-a5b94d3b2681.png)

View of the EO:
![image](https://cloud.githubusercontent.com/assets/16134316/25390753/b7b7771e-29d4-11e7-9872-0aaa85f33222.png)

**Comment by paulakeen** [comment]
Please find below a proposal of a mock-up of the view of the EO, as commented in the last meeting:

![image](https://cloud.githubusercontent.com/assets/16134316/25613704/7a03bb0c-2f2f-11e7-9179-3c7d1317168f.png)

**Comment by paulakeen** [comment]
Please find the details of the final decision in https://github.com/ESPD/ESPD-EDM/wiki/18.-Technicians-or-technical-bodies
