### ISSUE TITLE
Subcriterion structure

### ISSUE THREAD

**Issue by AFSOLUZIONI** [OP-TED/ESPD-EDM#197]
Hi
in italian taxonomy we need two kind of subcriterion:

1. a simple description that clarify the means of the european question (i.g. yellow row in the taxonomy) in our national taxonomy is coded as criterion_0

2. a subcriterion that asked furthe information not requested in the european criterion. In our taxonomy is coded criterion_1 .. N.

the second one is simple: "is just like a criterion" (as said in the ESPD-EDM) with group, subgroup, question, caption etc. etc.

the first one, in our model, contains only the declaration of subcriterion.
To be more clear an example:

![image](https://user-images.githubusercontent.com/44367854/48505958-9cc14000-e848-11e8-95c8-806d0acb44d1.png)
 Do you think that this approach could be right?? And if not how we can implement the case 1.??

**Comment by paulakeen** [comment]
We need to discuss this together with GROW and MS. The principle adopted for the design in ESPA and eCertis2 was that all every criterion is always a "descendant" of one European criterion. Otherwise this would mean that the national criteria are somehow not aligned to the EU Directives. 

We understand that if this is clear for the Exclusion criteria it may be clearless regarding some selection criteria. 

But in your example I see that you are illustrating your need in relation to an exclusion criterion, which btw seem aligned to what we have in the Directive, too. So my question would be: isn't your national sub-criterion a particular case of the European one?

Additionally you could also design a national criterion as a "sub-sub-criterion", having as the root criterion the European one which would contain a national broader sub-criterion which could in turn a narrower national sub-sub-criterion. Complex but implementable.

Let's have a look into it together, please. 

BTW, national sub-criteria design do not impact the "standard" ESPD-EDM specification. Therefore this can be discussed at any time from now on, and does not block releasing the v2.0.3 the soonest.

**Comment by ec-mcs** [comment]
I would like to confirm the comment of @paulakeen. The system of mapping evidence between different countries only work if we all have the same understanding of a specific criteria. This is why eCertis is necessary to provide a "root" criteria. It is the necessary for countries to map their criteria correctly to the EU ones. While sub-sub-criterion would work, it would create more problems in the end. At the same time it is clear that we need to improve the logic in eCertis or provide more granularity of criteria offered there. But before doing changes, we should learn and see how things are used to better understand what we probably would need to change. @AFSOLUZIONI, maybe you store ESPD requests and ESPD responses so that we can better understand how the ESPD is used.

**Comment by ec-mcs** [comment]
I think we can close this issue. In order to have interoperable solutions, criterion structure should be the same in all ESPDs Please feel free to ask to open it again if necessary.
