### ISSUE TITLE
Part III: National exclusion grounds

### ISSUE THREAD

**Issue by ec-mcs** [OP-TED/ESPD-EDM#200]
The EPSD service from ESPDint is building the UI dynamically. Using the ESPD service from ESPDint to check v2 I found probably a problem:
v2 self-contained should allow for each national criteria to ask if the information is available electronically. But it seems the EDM does not allow this. It seems that the EO can only provide this information once even if there are multiple national criteria. This would be wrong. Just today in an eMeeting this was a request from Slovenia.
https://github.com/ESPD/ESPD-EDM/wiki/13.-Purely-national-exclusion-grounds

**Comment by mfontsan** [comment]
This issue is closed as it was solved in version 2.1.0.

Currently the extended model (before, named self-contained model) allows to provide multiple evidences as the cardinality was changed from 0..1 to 1..n in v2.1.0.

See the criteria taxonomy of the extended model:
•	https://github.com/ESPD/ESPD-EDM/blob/master/docs/src/main/asciidoc/dist/cl/xlsx/ESPD-CriteriaTaxonomy-SELFCONTAINED-V2.1.0.xlsx
