### ISSUE TITLE
Part IV: Set up of an economic operator

### ISSUE THREAD

**Issue by ec-mcs** [OP-TED/ESPD-EDM#202]
The ESPDint solution does not allow to enter a date for the EO when it was established. Is this a bug in the ESPD EDM?

**Comment by jerouris** [comment]
Do you mean Part II? Where in Part IV there is a criterion about the setup of the EO?

**Comment by paulakeen** [comment]
I do not understand this issue, MC. Can we discuss this asap.

**Comment by mireiaBM** [comment]
During the meeting with the MS held on September 10, 2019, it was decided that this issue requires a change of structure: removing the criterion and put it in as subcriterion of specific and generic turnover.
The change will be implemented in version 3.0.0.

**Comment by hricolor** [comment]
After the presentation of several proposed solutions to the OUC (Wednesday 17 of June), and the discussion over the topic, the agreement was to delete de Criterion No 33 and include the information about the set up of the economic operator as subcriteria of the generic and specific turnover criteria. 

This issue will be fixed in the new version of ESPD.

**Comment by hricolor** [comment]
> After the presentation of several proposed solutions to the OUC (Wednesday 17 of June), and the discussion over the topic, the agreement was to delete de Criterion No 33 and include the information about the set up of the economic operator as subcriteria of the generic and specific turnover criteria.
> 
> This issue will be fixed in the new version of ESPD.

As commented in the previous contribution. It was applied in the last ESPD release 3.0.0.
