### ISSUE TITLE
Alpha Criterion (# 65): Redundant Evidence QUESTION_SUBGROUP

### ISSUE THREAD

**Issue by MariaSpr** [OP-TED/ESPD-EDM#208]
REGULATED 2.1.0 Taxonomy: 
At the CRITERION.SELECTION.ALL there is a redundant evidence QUESTION_SUBGROUP.

![alpha](https://user-images.githubusercontent.com/15072613/49161263-28e76300-f331-11e8-8549-a5fb3eeb286b.PNG)

**Comment by paulakeen** [comment]
Corrected! Also:
The Criterion Description reads now: "Concerning the selection criteria the economic operator declares that It satisfies all the required selection criteria indicated in the relevant notice or in the procurement documents referred to in the notice."
And the QUESTION reads "Your answer?"

![alpha](https://user-images.githubusercontent.com/16134316/49285124-ed66a900-f496-11e8-89a9-bec2a7343eb1.png)

Thank you.

**Comment by AFSOLUZIONI** [comment]
Hi,
there is a little issue:
the "true/false" value indicate if open or not the part IV at all (more or less).
Nowadays we use the INDICATOR to skip just the next Group or SubGroup (Requirement or Question).
Thecnically speacking the request is not so simple to implement.
It's just a reflection.
What do you think about that??

Francesco

**Comment by paulakeen** [comment]
We have had this same discussion with the ESPDint Consortium. 

The problem here is that the data structure cannot be used to controll the GUI behaviour 100%.  And the data structure is mainly intended to represent the formal commitment by the economic operator that it states and possibly signs that it fulfills all the selection criteria. 

If I understood well, what ESPDInt did is to "hard-code" the show or not-show the Part IV depending on whether the ESPD does not contain or contains the Alpha Criterion. Would that be a solution for you?

**Comment by mireiaBM** [comment]
This issue has been solved in version 2.1.0 of the ESPD-EDM
