### ISSUE TITLE
Criterion 62: Redundant Evidence QUESTION_SUBGROUP

### ISSUE THREAD

**Issue by MariaSpr** [OP-TED/ESPD-EDM#212]
Both REGULATED and SELF-CONTAINED 2.1.0 Taxonomy:
At the CRITERION.OTHER.EO_DATA.LOTS_TENDERED there is a redundant evidence QUESTION_SUBGROUP.

![criterion_62](https://user-images.githubusercontent.com/15072613/49515936-f1346a00-f8a0-11e8-82b1-be7631c12003.PNG)

**Comment by paulakeen** [comment]
OK to the redundancy of the group "Is this information available online". But about the Lots, in the REGULATED we should have a group of LOT Identifier with cardinality multiple instead of "Your Answer", as we have in the SELF-CONTAINED. Currently we have this:

REGULATED:
![image](https://user-images.githubusercontent.com/16134316/49689997-12f45200-fb2a-11e8-8b60-a7f5a083355e.png)

SELF-CONTAINED:
![image](https://user-images.githubusercontent.com/16134316/49690011-36b79800-fb2a-11e8-8831-e3686a090192.png)

**Comment by jerouris** [comment]
There is a major difference that makes the self contained require a "LOT_IDENTIFIER" and the regulated not requiring one:

The Self Contained contains a list of lots provided by the CA, which the LOT_IDENTIFIER maps to. However there is nothing that a LOT_IDENTIFIER can map to in regulated, thus this list of values will be "orphan".
This is why I would prefer a "Description" or a list of CODEs like CPVs (but with no codelist this could be a schematron and implementation nightmare)

**Comment by mfontsan** [comment]
OK:

1. The group "Is this information available electronically" has been removed from the both, the REGULATED and the SELF-CONTAINED CriteriaTaxonomies; and
2. The REGULATED and the SELF-CONTAINED data structures are now identical, except for the fact in the REGULATED the data property type for the field Lots ID is a DESCRIPTION and in the SELF-CONTAINED it is of type LOT_IDENTIFIER. 

This will also be commented in section VII.6 Economic Operator / Differences between Regulated and Self-contained of the online documentation.

**Comment by mireiaBM** [comment]
This issue has been solved in version 2.1.0 of the ESPD-EDM
