### ISSUE TITLE
Criterion group ELIM-OTHER-EO-Contributions

### ISSUE THREAD

**Issue by realeroberto** [OP-TED/ESPD-EDM#227]
As of commit c29b2e1, the criterion group `ELIM-OTHER-EO-Contributions` is not available anymore in the `xlsx` taxonomy at

`ESPD-EDM/docs/src/main/asciidoc/dist/cl/xlsx/ESPD-CriteriaTaxonomy-SELFCONTAINED-V2.1.0.xlsx`

yet it is still present in the `CriteriaTaxonomy` section of the `CodeList` at

`ESPD-EDM/docs/src/main/asciidoc/dist/cl/xlsx/ESPD-CodeLists-V2.1.0.xlsx`

**Comment by paulakeen** [comment]
Done, thank you. But we understand you were referring to the criterion in tab OTHER-EO-Contributions, UUID 5a8dea31-5db9-4e03-862b-07810aa6a7fd, code CRITERION.OTHER.EO_DATA.CONTRIBUTIONS_CERTIFICATES. 

This criterion was removed because it was redundant, as the information required therein was also asked in C#58 (see data structure for this criterion below).

**Removed Criterion** 

The name of the removed criterion was: "Contributions certificates"

And the description: "Will the economic operator be able to provide a certificate with regard to the payment of social security contributions and taxes or provide information enabling the contracting authority or contracting entity to obtaining it directly by accessing a national database in any Member State that is available free of charge?".

This is how it looked like in the Self-contained Criteria Taxonomy:

![image](https://user-images.githubusercontent.com/16134316/52889963-aaa59a80-3182-11e9-8688-cafabdfdbe58.png)

** The Criterion #58"

Criterion name: "EO   registered in a PQS"
Description: "If   applicable, is the economic operator registered on an official list of   approved economic operators or does it have an equivalent certificate (e.g.   under a national (pre)qualification system)?"

The figure below shows the data structure. In line 15, the QUESTION reads: "Will the economic operator be able to provide a certificate with regard to the payment of social security contributions and taxes or provide information enabling the contracting authority or contracting entity to obtaining it directly by accessing a national database in any Member State that is available free of charge?" See also the Criteria Taxonomy [spread-sheet](https://github.com/ESPD/ESPD-EDM/blob/2.1.0/docs/src/main/asciidoc/dist/cl/xlsx/ESPD-CriteriaTaxonomy-SELFCONTAINED-V2.1.0.xlsx), tab "OTHER-EO-PQS".

![image](https://user-images.githubusercontent.com/16134316/52890343-94004300-3184-11e9-9ab2-dda22cf92f54.png)

**Comment by realeroberto** [comment]
Thank you so much, @paulakeen. Will you close the issue?

**Comment by eprocurementontology** [comment]
Not yet, @reale: issues are closed by DG GROW before starting a new release. In any case, if you ever need to reopen this topic we can do it at anytime.

**Comment by realeroberto** [comment]
Glad to hear. Thanks again!

**Comment by paulakeen** [comment]
Not yet, @reale: issues are closed by DG GROW before starting a new release. In any case, if you ever need to reopen this topic we can do it at anytime.

**Comment by mireiaBM** [comment]
This issue has been solved in version 2.1.0 of the ESPD-EDM
