### ISSUE TITLE
ESPD terminology - "version" or "flavour"

### ISSUE THREAD

**Issue by JachymHercher** [OP-TED/ESPD-EDM#229]
In the ESPD world, the word "version" seems to be used ambiguously. First of all, it can refer to v1, v2, v2.0.1 etc. Second of all, it can refer to "regulated" and "self-standing".

What about using the word "version" for v1, v2, v2.0.1, etc. and "flavour" to distinguish "regulated" and "self-standing"? This should mainly be taken into account when updating the documentation, presentations, etc.

**Comment by paulakeen** [comment]
Thank you for your suggestion. As a matter of fact, using "flavour" only to make the disctinction between Regulated and Self-contained was the idea, but at some point (probably because of tireness) they were used in the wrong places.

We'll review the more recent online documentation and will correct that.

Thanks!

**Comment by ec-mcs** [comment]
We could use something like v1.0.2r, v2.1.0r ('r' for regulated) and v2.1.0sc ('sc' for self-contained)

**Comment by JachymHercher** [comment]
Related point, recently discussed with @ec-mcs: the distinction between "regulated" and "self-contained" is a bit confusing, because "self-contained" is also "regulated" (in the sense of complying with the regulation). We should use a different terminology. 

What about "basic" and "self-contained"; "basic" and "extended"; or something similar?

**Comment by mireiaBM** [comment]
Between DG GROW, OP and the MS it has been decided that:
1. From now on, the documentation will use "version" to only refer to releases (e.g. v2.0.0, v2.1.0...).
2. We will stop using the term "flavour". From now on, instead of saying “ESPD regulated flavour” we will say “basic ESPD”. Similarly, instead of saying “ESPD self -contained flavour” we will say “extended ESPD”.
The documentation will be updated where necessary and as soon as possible. This update will be published in the next release.

**Comment by JachymHercher** [comment]
Great news about "version" and about regulated/self-contained --> basic/extended!

I'm a bit confused about abandoning "flavour". Why is it being abandoned? What word should be used instead, when one needs to refer to the other... thing?

**Comment by mireiaBM** [comment]
Instead of using "flavor", we suggest using the term "**model**", as the main differences between the basic/extended are in the criterion data structure and in the possibility for the CA of introducing requirements specific to the procurement procedure.

**Comment by mfontsan** [comment]
We have reopened the issue as the change of terminology in the documentation from "regulated" to "basic" and from "self-contained" to "extended" will be implemented in version 2.1.1. 

Once the change is implemented, we will proceed to comment and close the issue.

**Comment by JosePRevenga** [comment]
Please note that from v2.1.1 _version_ will only be used when referring to the actual EDM version (i.e., 2.1.0, 2.1.1, etc.), while the **new nomenclature** for the **Regulated** and **Self-contained** ESPD are **Basic** and **Extended**, respectively.
