### ISSUE TITLE
Question: “Is the economic operator a Micro, a small or a medium-size entrerprise??”

### ISSUE THREAD

**Issue by AFSOLUZIONI** [OP-TED/ESPD-EDM#230]
Hi,
the problem is that we have a question that require an answer YES/NO (as reported in the official   documents like directive 24) and the request to insert a value chosen in a code list.
In other word:
Here you are the mock-up in the EDM 2.1.0
![mock-up sme](https://user-images.githubusercontent.com/44367854/54024192-5006c980-4197-11e9-9f18-758a396797c6.jpg)

But in the document it's required a choice in a code list.

The question isn't the right one to accept a response in a code list then we have two different solution:

1. we change the question in a way like "could you insert your enterprise dimension (using the rules defined in the recommendation UE 20003/361)?"

2. leave the question as is and use only two elements of code list:
                YES  -->   SME
                NO  -->   LARGE

Both the solutions have some little issue:
Number 1 there is an ambiguity in the code list because there are MICRO SMALL MEDIUM values and the SME value that represents the last to values ... An EO must select SMALL, MEDIUM or SME???
Number 2 SME doesn't contain the MICRO enterprise and then doesn't allow to insert this value.

It seems we haven't a solution, even if I'm for the number 2 anyway.

The problem is we haven't a structure in which represents   how to fill in all the information contained in the ESPD. I know that we must use UBL to manage information related to CA and EO, but 

**may we use something like the taxonomy to define how we ask for each field present in the ESPD?**

As Enric know we adopted a structure, like Criterion, to represent the other information (no Criteria)  from the beginning and we have no problem and every information is well defines (INDICATOR, CODE, etc. etc.)

What do you think about that??

P.S. we have already the mapping of all information in ESPD not in Criteria, if it could be useful we can share it. 

Francesco

**Comment by JachymHercher** [comment]
This issue is linked to https://github.com/eprocurementontology/eprocurementontology/issues/164.

**Comment by mireiaBM** [comment]
Originally (in previous versions of the ESPD) this was modelled using the criterion data structure, thus making it possible to specify the quantity of employees and other data about the company. Later on, this data structure was removed and the UBL code “industry classification” was used to specify one option out of four (micro, small, medium, large). 

Ideally, it would be for the UBL 2.3 TC to consider how to model this in the XSD Schema. As members of the UBL TC we will create a ticket in their Jira, so that we can initiate this discussion there.

Solution: the proposal by @AFSOLUZIONI of retrieving this criterion-based data structure seems interesting, but with one additional proposal: including the code inside the structure. This solution will be implemented immediately, if no one disagrees. Otherwise, please feel free to provide feedback.

**Comment by JosePRevenga** [comment]
New Criterion OTHER-EO-SME has been added to the Extended ESPD in v2.1.1, as the UBL code "industry classification" used until now did not allow to give the yes/no answer included in the Directives.
