### ISSUE TITLE
UUID not found in e-CERTIS (Criteria #58 and #64)

### ISSUE THREAD

**Issue by AFSOLUZIONI** [OP-TED/ESPD-EDM#234]
Hi,
for the following Criterion we don't found UUID in e-CERTIS:

1. Criterion #64 (6a21c421-5c1e-46f4-9762-116fbcd33097)
2. Criterion #58 (9b19e869-6c89-4cc4-bd6c-ac9ca8602165) 

but our "member state" validator (we are Italian and the validation is performed by ANAC) give us an error ... in the european one the two criteria are OK!!

Any idea??
Thank you for support.
Francesco.

**Comment by dambeol** [comment]
Can you give us more details on the context. 
Are these 2 criteria, existing criteria that used to be available in eCertis and now they are not?
Is it possible that you give us the name of the criteria so we can check what are the uuid in eCertis for them?

**Comment by AFSOLUZIONI** [comment]
HI,
I'll try to be more clear:
in the taxonomy self-contained we have 64 criteria.
In e-CERTIS we have 58 criteria.
We have 6 criteria in the taxonomy that aren't present in e-CERTIS.
Where they are??
More deeper:
we have some national criterion linked to the "ghost" criterion. 
How I can add the national criterion to have the right UUID to manage correctly the ESPD Request / Response XML generation?
I will be back with some example that could help to understand our problem.

Francesco

**Comment by AFSOLUZIONI** [comment]
Hi,
I make a very tough job to verify the alignment between e-CERTIS and ESPD Taxonomy. The result is the following:

EU Criteria in e-CERTIS  -->   58
EU Criteria in Taxonomy -->  64
Criteria only in e-CERTIS  -->  2 (see screen shot below)
Criteria only in taxonomy  -->  8

Common criteria  --> 56

the criteria that are only on e-CERTIS are:
Generic EU Criterion
![image](https://user-images.githubusercontent.com/44367854/61889992-d2094c00-af06-11e9-896d-642184bd7e84.png)

and

Bankrupt,   the subject of insolvency or winding-up, arrangement with creditors,   analogous situation arising from a similar procedure under national laws and   regulations, its assets are being administered by a liquidator or by the   court, or its business activities are suspended
![image](https://user-images.githubusercontent.com/44367854/61890118-1c8ac880-af07-11e9-918e-33c9fb3fd737.png)

the criteria that are only in taxonomy are:

#57 - EO is a sheltered workshop  (UUID 2043338f-a38a-490b-b3ec-2607cb25a017)
#58 - EO registered in a PQS         (UUID 9b19e869-6c89-4cc4-bd6c-ac9ca8602165)
#59 - EO together with others       (UUID ee51100f-8e3e-40c9-8f8b-57d5a15be1f2)
#60 - Relied on entities                  (UUID 0d62c6ed-f074-4fcf-8e9f-f691351d52ad)
#61 - Not relied on entities            (UUID 72c0c4b1-ca50-4667-9487-461f3eed4ed7)
#62 - Lots the EO tenders to          (UUID 8b9700b7-b13c-41e6-a220-6bbf8d5fab31)
#63 - Reduction of the number of qualified candidates (UUID 51c39ba9-0444-4967-afe9-36f753b30175)
#64 - CA Lots                                 (UUID 6a21c421-5c1e-46f4-9762-116fbcd33097)

For the first case (criteria only in e-CERTIS) I suppose that the criteria must be "archived" as the wrong italian one.
For the second case (criteria in the taxonomy) I know that this criteria aren't exclusion or selection criteria, but, unfortunately, we have subcriteria (italian national criteria) for #57, #58, #59 and #61. 
How we can insert the subcriteria in e-CERTIS without the EU criteria??

Sorry for the very long answer, but I'm not able to do better.

Francesco

**Comment by dambeol** [comment]
Hi Francesco, 

Thanks for all the details.

The 2 criteria that you mentioned are only available in eCertis (from the screenshots) are EU criteria. The EU criteria are added in eCertis by commission users. For each country, it is possible to add criteria starting from the EU criteria, each national criterion defined in eCertis must have an EU criterion as a parent.

'For the first case (criteria only in e-CERTIS) I suppose that the criteria must be "archived" as the wrong italian one.'
I assume they are in eCertis because there are no italian criteria defined for these 2 EU criteria. It is not possible to archive this 2 criteria defined at EU level. Although there are no national criteria for them in Italy, they are parent criteria for national criteria in other countries.

'For the second case (criteria in the taxonomy) I know that this criteria aren't exclusion or selection criteria, but, unfortunately, we have subcriteria (italian national criteria) for #57, #58, #59 and #61.
How we can insert the subcriteria in e-CERTIS without the EU criteria??'
I assume these criteria are needed in Italy but they don't match any of the EU criteria.
No, it is not possible in eCertis to add national criteria without an EU criterion as a parent.

I hope this helps.

Best regards,
Olimpia

**Comment by dambeol** [comment]
For the criteria that are only available in your system, you can always add them in eCertis, but they must have an EU criterion as a parent. Adding more EU criteria will have an impact on all the countries so, for any change in the criteria at EU level (adding, editing etc.), you can contact Marc Christopher.

**Comment by ec-mcs** [comment]
Indeed we need to delete (inactivate) the criteria in eCertis. Before that, we will ask the countries to link their national criteria to other criteria. Once done, we can delete them.

**Comment by mireiaBM** [comment]
This issue will be addressed in version 2.1.1 of the ESPD data model.

**Comment by rerigirl** [comment]
Hi everyone , please i need help. I am new to coding and would like to to implement the ESPD and have an end user experience by testing.

Please how do i go about implementing espd and using the tool? also i would like to integrate it with my eprocurement tool.

**Comment by JosePRevenga** [comment]
Hello rerigirl,

This forum is dedicated to the ESPD Exchange Data Model (EDM), so for questions related to the UI you can access the [ESPD Service ](https://github.com/ESPD/ESPD-Service)repository. 

I also recommend you check the DG-GROW [Web page](https://ec.europa.eu/growth/single-market/public-procurement/digital/espd_en) dedicated to ESPD.

For further information about the ESPD-EDM, you can check the [online documentation](https://espd.github.io/ESPD-EDM/v2.1.0/) (latest version 2.1.0) or contact us.

**Comment by JosePRevenga** [comment]
Same as issue #231
