### ISSUE TITLE
CRITERION #47

### ISSUE THREAD

**Issue by AFSOLUZIONI** [OP-TED/ESPD-EDM#235]
Hi,
in the criterion #47 there is a Type Code IDENTIFIER that we aren't able to manage in our application (see image)
![#47 CRITERION](https://user-images.githubusercontent.com/44367854/54756393-72153880-4be8-11e9-863a-b6f07d0af15c.jpg)

Time ago we decided we must "typezed" IDENTIFIER to manage correctly the UI.
We have:

EO_IDENTIFIER  for Economic Operator

EVIDENCE_IDENTIFIER for Evidence

LOT_IDENTIFIER for LOTS

for EO_IDENTIFIER we discussed we have a codelist to specify values to fill the combo defining the kind of code used
How we must manage the IDENTIFIER in the #47??
In my opinion we need to modify from IDENTIFIER to QUAL_IDENTIFIER and insert in Code-List a proper code list with the right values (e.g. ESCO) and an "OTHER" values that allow to insert Qualifications not coded.
Another solution could be changes the type code from IDENTIFIER to DESCRIPTION.
We found this issue in the test session we are performing for the validation meeting.

Waiting your answer 
Francesco

**Comment by mireiaBM** [comment]
In the ESPD-EDM meeting with the MS held on September 10, 2019, it was decided that:

- In version 2.1.1, the QUAL_IDENTIFIER will be included in the code list ReponseDataType. However, first it will need to be checked with the Publications Office.

- For version 3.0.0, it will be necessary to rethink whether these prefixes can be avoided at all. If they were, then strong rules would be needed.

**Comment by JosePRevenga** [comment]
As announced in mireiaBM's previous comment, the new QUAL_IDENTIFIER code has been added in v2.1.1 to the ResponseDataType Code List, to properly identify the educational qualifications requested in Criterion 47, SC.ABILITIES.3 (Education).

**Comment by psotofer** [comment]
Greetings,

Regarding both QUAL_IDENTIFIER and EVIDENCE_IDENTIFIER:
@AFSOLUZIONI @jerouris 
Could you confirm if these prefixes are still needed and their purpose?
Thank you.

**Comment by AFSOLUZIONI** [comment]
Hi @psotofer ,
I think so!
Even if we haven't nowadays the proper code list for QUAL-IDENTIFIER.
Francesco

**Comment by rantati7** [comment]
#210 #47 Could someone who understands ESCO qualification explain how one should reply to questions in #47? We have implemented #47 but I do not understand what I should reply as a tenderer to the questions. 

**1. Please identify ESCo identifier? Response field: URL.** 

What is this URL that I as a tenderer should reply to this question?

**2. Please describe the ESCO qualification?  Response field: Description**

This is easier as I can possibly write whatever I wish in their field - including that I do not understand.

3. Qualification number? Response field: QUAL_IDENTIFIER

What is this QUAL- IDENTIFIER? Is there a predefined list of ESCO identifiers?

I do not know how this ESCO works - is this somewhere an understandable description on how it works?  

This is how this looks in Excel and what it looks like when we implemented it (tenderer's ESPD response). Have we implemented it correctly (for ESPD Response)???

![image](https://user-images.githubusercontent.com/20238848/92376916-feccf280-f10b-11ea-82e1-514118c9d02f.png)

![image](https://user-images.githubusercontent.com/20238848/92377365-b2ce7d80-f10c-11ea-84e7-3c14b358c557.png)

**Comment by psotofer** [comment]
Greetings,

@rantati7 we are working in your query and will come back to you ASAP.

In other order of things, after discussion in the OUC we agreed to delete element **_LOT_IDENTIFIER_** and we in keeping both **_QUAL_IDENTIFIER_** and **_EVIDENCE_IDENTIFIER_**.

Best Regards.

**Comment by mfontsan** [comment]
Hi @rantati7 
1.	ESCO Identifier as URL: The reason why the expected type of data is a URL is because in ESCO taxonomy each concept is identified with a URI. You can find the ESCO Qualifications in this link: https://ec.europa.eu/esco/portal/qualification (description on the ESCO qualification) and https://europa.eu/europass/en/find-courses (list of qualifications).

2.	ESCO Qualification as description: this is an optional element to provide additional information on the qualification.

3.	Qualification number as QUAL_IDENTIFIER: this field is not related to ESCO. The following 4 fields are used for to define a qualification, out of ESCO. More specifically, the expected value is an identifier, the validator tool does not check this validator.

![image](https://user-images.githubusercontent.com/15996178/93859586-1a183000-fcbe-11ea-985e-ec6bc806b5b8.png)

**Comment by hricolor** [comment]
After present this issue in the OUC of the 3rd of September, and discuss with the stakeholders, this is the proposed solution that will be implemented:

The need of keeping criteria QUAL_IDENTIFIER and EVIDENCE_IDENTIFIER was discussed with the interested users. Since they acknowledged their need for the criteria it was agreed on keeping them and deleting LOT_IDENTIFIER. 

This issue will be implemented within the next ESPD-EDM 3.0.0.

**Comment by hricolor** [comment]
> After present this issue in the OUC of the 3rd of September, and discuss with the stakeholders, this is the proposed solution that will be implemented:
> 
> The need of keeping criteria QUAL_IDENTIFIER and EVIDENCE_IDENTIFIER was discussed with the interested users. Since they acknowledged their need for the criteria it was agreed on keeping them and deleting LOT_IDENTIFIER.
> 
> This issue will be implemented within the next ESPD-EDM 3.0.0.

As commented in the previous contribution. It was applied in the last ESPD release 3.0.0.
