### ISSUE TITLE
Criterion #63 missing set of fields

### ISSUE THREAD

**Issue by sakispantazis** [OP-TED/ESPD-EDM#248]
Criterion 63 (i.e. the question regarding the reduction of the number of qualified candidates ‘Part V’)

The Regulation’s stipulations for this criterion are:
 
![image](https://user-images.githubusercontent.com/16813866/57989349-2d9c0100-7aa2-11e9-9d56-4d838d6944b6.png)

a)	Regarding this criterion the CA/CE and the EO (only in case the EO starts a response from scratch) have to be able to choose if this criterion has to be included in the artifact or not
•	either via a checkbox placed here (Part V)
•	or via a drop down list containing the type of procedures. This drop down list could be placed into Part I (like it has been done in the EU ESPD implementation) or it could be placed here (Part V). In case the CA/CE has chosen an open procedure then Part V should not be included in the ESPD request, i.e. Part V should not appear to the EO.

b)	There seems to be some fields missing which are described in the Regulation comprising the following set of fields: [text field for the non-discriminatory criterion or rule + “yes/no” question indicating whether the EO has the documentation for this specific non-discriminatory criterion or rule + web address text fields for the documentation]. This set of fields should appear for each of the non-discriminatory criteria or rules, i.e. the set of fields has a cardinality of 1..n.
For the regulated version I think it would be enough to have this implemented in the response only, but in the self-contained version I think it should be implemented in the request as well as the response.

**Comment by ec-mcs** [comment]
About a) We do have a codelist in v2.1.0 for the type of the procedure. So depending on this setting the UI can decide if Part V is shown or not. We put it into Part I as the CA should know best what type of procedure is used. If data is reused from the eTendering service this information can be taken over. It is then for the ESPD service to decide if this section is shown or not.

About b) Indeed this is not fully correct. As we are moving towards the extended ESPD (especially in the light of the upcoming eForms), Part V is not necessary anymore - if the ESPD uses the possibility of weighting. Part V is only necessary if weighting is not used for a two stage procedure. Because of this, I would suggest to close this issue.

**Comment by sakispantazis** [comment]
Dear Marc, 

for a) we are going to use this codelist as you suggested

for b) I need some elaboration on why Part V is not necessary in light of the upcoming eForms and also for the weighting (I am not aware that weighting is possible for the first stage of a two stage procedure) during the next ESPD Data Model maintenance meeting.
