### ISSUE TITLE
Correct Interpretation of use of Taxonomy

### ISSUE THREAD

**Issue by AFSOLUZIONI** [OP-TED/ESPD-EDM#258]
Hi all,
We had yesterday a discussion about the argument in re: there are two different position. I don't say what's my position and ask you to express your opinion 😊 :

1. The European taxonomy (the information expressed in the xslx) is just a guide line. Each Member State build its own criteria using: the European one if there are no difference between EU directives and national law; a different articulation (sometime more than one criterion) if the national law is different from the EU directive. In other word, each Member state have an ESPD developed only on Member state criteria;

2. Each Member state MUST use EU taxonomy and the related criteria. If needed (i.e. differences depending on a more restrictive interpretation of the EU Directives inside the national law), each Member State can add to each EU criterion one or more criteria to ask the further information needed to be compliant with its own national law.

What do you think about??
I'm waiting for your response / opinion.

Francesco.

**Comment by paulakeen** [comment]
Dear Francesco,

The answer is "2". Otherwise the interpretation of the criteria, based on its very particular **expected** structure, could not be **shared cross-border**.

National criteria can be added as sub-criteria. However these sub-criteria will not be understood (or processed) by other countries unless you share them:

* If the sub-criteria are common for any Procurement Procedure and are applicable to the MS, and not just to one level of administration, then the right place to share these sub-criteria is e-Certis.

* If the sub-criteria are particular for a specific Procurement Procedure, then the only way of sharing these ad-hoc structure is documenting them in the Procurement Documents, in the Buyer Profile, and in any other documentation relevant to the Procedure.

**Comment by SellittoGiampaolo** [comment]
It seems that the question is not clearly defined, and on the other side the interpretation of this point is not uniform at EU level, at least from an overview of the eCertis editorial situation.

I'd start form the elementary use case, where an economic operator wants to use eCertis as an informative tool (at this moment I do not consider the ESPD) for cross border participation.
E.g. an EO located in Greece wants to participate in a tender in Italy.
She goes to eCertis and asks which are the EG and SC in Italy. I imagine that from an usability point of view, she selects Italy from the menu (and not EU AND Italy) together with criteria or evidence and the like.
She expects an exhaustive list of the criteria of participation/exclusion grounds that she has to fulfill in italy., related to the EU criteria. 
This is confirmed by the fact that the legal framework should refer to National Law if there has been a national implementation of the Directive.

This is also the base for ESPD in a M2M interaction, as the system can retrieve the IT criteria to build an ESPD...

In the case the MS should include in eCertis ONLY the differences from the EU directive, without providing the equivalent criterion for each of the EU criteria, the list of criteria that eCertis provides as a response would be partial and the EO could deduce that only a limited set of criteria should be fulfilled for cross-border participation.

In one of the last eCertis Meetings the need arised for MS to explicitly state the (strange) condition that an EG or a Criterion does nto apply at national level.

Based on these consideration, I'd conclude that a MS should provide the national correspondent foreach EU criterion, detailing the local regulatory framework. Eventually, the MS could split the criterion into subcriteria in order to better specify particular implementaqtion flavours of the parent EU criterion.

**Comment by AFSOLUZIONI** [comment]
It seems you explain better the first one option, but essentially the concept is the same.
"Based on these consideration, I'd conclude that a MS should provide the national correspondent for each EU criterion, detailing the local regulatory framework" and then each MS must reproduce all the criteria in its own national criteria. I think we must introduce the correct localization of EU criteria in all language in the UE but we don't reproduce them in each MS.
Francesco

**Comment by paulakeen** [comment]
OK, let us discuss this internally with DG GROW and OP, too, so we can coordinate the answer. We have though a logistic problem in aligning the agendas....we'll come back to you in the very next days.

**Comment by SellittoGiampaolo** [comment]
Just a clarification...
In the current data model the translation of the directive could be fine if
the MS did not provide a national transposition of the directive itself...
Else the legal framework changes, notwithstanding the fact that the
transposition in some articles can reflect the directive literally.
In any case when there is a national transposition of the directive, imho
we should provide BOTH the translation of the directive (EU criterion,
language=IT) and the correspondent national criterion (MS=IT & Language =
IT)
In the construction of an espd we select the criteria for MS=IT.
Else we would have a tight coupling between the  text of the directive and
the correspondent text of MS legislation and moreover we would have to rely
heavily on business logic to build an espd

Il lun 11 nov 2019, 16:00 Paula Keen <notifications@github.com> ha scritto:

**Comment by ec-mcs** [comment]
The key for eCertis (actually for public procurement ingeneral) is mutual recognition of means of proof. If a company in Greece participates in Italy, they have to meet the exclusion and selection criteria selected by the Italian buyer in the "Greece" way. If the Greece company would need to have Italian certificates etc, it would not be a single market.

The Italian public buyer would in this regard need to check the Greece means of proof.

Besides that, an EU Directive has to be implemented into national law. So one EU criteria could have multiple national criteria. So answering the opening remark, it is a mixture of 1 and 2 (more 2).

**Comment by GPsellitto** [comment]
Thanks, MC
The point of discussion here (it is likely that it is not clear in the above formulation, but Isabel responded in BXL) is whether as a Member State that has a national law  implementing the Directives we shall provide in eCertis all of the criteria reported in our law, notwithstanding the fact that they differ or not in their formulation from the EU criterion or ONLY those criteria that differ from EU formulation.
Some remarks, in order to evaluate the impact at service-level:
In the case "2" we report ONLY the criteria that differ form EU form, so the EO that searches in eCERTIS for criteria selecting MS = IT will find only a very limited number of criteria.
In the case "1" the EO will retrieve the complete list of criteria (from a legal point of view) for MS = IT

In both case the Parent Criterion is retrieved without the text, as the text of the parent EU criterion is retrieved when you select MS=EU in the eCERTIS menu.

**Comment by AFSOLUZIONI** [comment]
Hi all,

This interpretation is a little different from mine:
_In the case "2" we report ONLY the criteria that differ form EU form, so the EO that searches in eCERTIS for criteria selecting MS = IT will find only a very limited number of criteria._
The correct definition is: In e-CERTIS we report, under the related EU criterion, the restriction adopted in our own legislation as a national criterion.

If the MS law accept the EU criterion "as is", I think is very redundant introduce another national criterion to represent it. I have another observation: For each criterion we have to add the "evidences" needed to prove the EO requisites. Each MS insert for each evidence their own documents needed to prove the satisfaction of the criterion request. In the "1" scenario each member state MUST insert his own documents in each evidence linked to the national criterion. In my opinion it's a mess!! My vision is:

1. We have a document named ESPD (Electronic SINGLE Procurement Document). 
2. We have a definition of this document in the EU directives. 
3. We have a "way out" clause for MS that have "restricted" the European contents, that allow single MS to add to the EU criterion one or more national criteria to add its own restriction.
 
Each MS accept all the EU criteria and insert the exceptions related to its own law.
That's the more simple solution and allow to maintain the concept of SINGLE document that is one of the reasons to introduce the ESPD.
For the question "How to have the complete list of criteria" my answer is very simple: choose "IT" and "EU" in the criteria selection obtaining both Standard EU criteria plus IT own criteria.

I'm strongly convinced of my interpretation because it's the one that meet completely with the original requisites. 

Francesco

**Comment by ec-mcs** [comment]
Isabel is right. All national criteria must be provided. 
In the way you dscribe case 2, this would not work. So it is case 1.

**Comment by hricolor** [comment]
Dear all, 
 
This has been a useful discussion regarding the correct interpretation of use of the Taxonomy. Since there are no more comments, have you found out any solution/conclusion regarding the raised question? Or Can we proceed to close the issue? 
 
If yes, we will close the issue but before we will gather all the information that has raised during the conversation. 
 
Thank you all

**Comment by GPsellitto** [comment]
Yes, we arrived at the conclusion that the EU criteria act as the entry points of a taxonomy that classifies national criteria  (the information expressed in the xslx). Each Member State reports in the taxonomy its own implementation of the parent EU criterion, eventually splitted in more than one criterion if needed (e.g. when national implementing law is different for Works and Services or if there are particular characteristics at national level to be highlighted). In this manner each Member state can assemble an ESPD based only on the Member State criteria, but the correspondence with the parent criteria will be explicit; 
The ESPD will have an esoskeleton formed by the EU criteria (actually their UUIDs suffice), but it will consist of the MS- specific criteria and questions.

**Comment by paulakeen** [comment]
In this decision, where would the evidences be attached (related) to? to the national criterion, only to the EU criterion, to a specific national requirement, to a specific EU requirement and never to the national ones? 

In other workds, what would be the common "pivot" entity?

**Comment by GPsellitto** [comment]
In eCERTIS Member States cannot attach evidences directly to the EU criterion (anyway, it would be conceptually wrong), so they must be attached to the national criterion. This is the only possibility that is fully compliant with the current data model. This implementation is also compliant with the fact the National evidences are dictated by national legal framework, not directly by the directive (the EU legal framework) and so the MS-criterion (the istance) is logically tied both with the MS-legislation and the MS-evidence, in the same way it is linked with its own question and question-group.
The various MS implementations of an EU criterion (the so-called "parent criterion", which should be considered the EU-point-of-view of the criterion itself)  are linked by the common parent criterion, therefore it is easy to estabilish a correspondence between siblings of the EU criterion and equivalent evidences. 
There is still a weakness of the whole model, as you cannot specifly if the criteria of the same MS implementing the same EU criterion are in OR between them or in AND, that is if the OE has to fullfill all of them at once in order to fulfill the EU criterion or if the OE must fulfill one OR the other in order to fulfill the parent criterion.

**Comment by GPsellitto** [comment]
A further consideration: imagine that you attach the evidences to the EU criterion directly: you would not have a mean to define which evidence would apply to which MS or in an ESPD you could mix-match any of the evidences linked to a criterion, regardless to your Member State. So if there is a member state that does not have an evidence, you can provide no evidence and that would be absolutely compliant with your data model.

**Comment by AFSOLUZIONI** [comment]
As you know, my opinion is a little bit different from the one of @ermeio :

1. if the EU criterion comply with the MS law it could be useful link evidence directly to it, obtaining the opportunity to understand how OE belonging to different MS  must prove the answer to the criterion.
2. If the MS have your own criterion (related to restriction of his law), the evidence must be "attached" to the national criterion and CA will have some difficult to establish wich evidence required to a foreign OE.

Obviously this approach require to give the complete visibility of EU criteria to the CA and, generally speaking to all people consulting e-CERTIS (not available at moment). 
Francesco

**Comment by GPsellitto** [comment]
Linking the evidences directly to the EU criterion would hamper the possibility to adopt the very same Data Model for the EU criterion and the MS criterion (actually they are instances of the same concept "criterion", where just the "MS" code is different), it would allow the mix-up of evidences from different MS in the same ESPD (unless you adopt some patchy and business-logic based method to assemblate evidences) and it has a lot of unwanted side-effects.
Currently each criterion has its own evidences - were they attached to the EU. the EU would have the evidences attached for other MS while the MS-criterion would have no evidence or evidences would be replicated both in EU and MS criterion....
A long discussion, but IMHO it is would be an example of an Architectural antipattern, that is a bad practice.
The current model (if correctly understood and implemented) is very clean and lends itself to a simple implementation in the systems, supports a simple mapping between different Member States, support translations and mappings and it is very easy to assemble an ESPD based on a simple query to e-certis. 
When RDF will be adopted, it is also very simple to foresee a REST SPARQL access to base registries in order to retrieve evidences, where the sparql query will be a sort of ESPD

**Comment by GPsellitto** [comment]
> In this decision, where would the evidences be attached (related) to? to the national criterion, only to the EU criterion, to a specific national requirement, to a specific EU requirement and never to the national ones?
> 
> In other workds, what would be the common "pivot" entity?



> As you know, my opinion is a little bit different from the one of @ermeio :
> 
> 1. if the EU criterion comply with the MS law it could be useful link evidence directly to it, obtaining the opportunity to understand how OE belonging to different MS  must prove the answer to the criterion.
> 2. If the MS have your own criterion (related to restriction of his law), the evidence must be "attached" to the national criterion and CA will have some difficult to establish wich evidence required to a foreign OE.
> 
> Obviously this approach require to give the complete visibility of EU criteria to the CA and, generally speaking to all people consulting e-CERTIS (not available at moment).
> Francesco

I want also to clarify that back in 2018, MC and Paula Keen in the issue  **#197 Subcriterion structure** [https://github.com/ESPD/ESPD-EDM/issues/197] responded to a similar question (the same proposal, disguised under another form) confirming that the approach proposed here was not satisfctory: "The system of mapping evidence between different countries only work if we all have the same understanding of a specific criteria. This is why eCertis is necessary to provide a "root" criteria. It is the necessary for countries to map their criteria correctly to the EU ones. " through the mapping to the same parent EU criterion you can derive the equivalence between national criteria and MS-specific evidences.

**Comment by AFSOLUZIONI** [comment]
Hi, 
I think it was clear where we must link evidence in my proposal.
I don't understand what you mean for "Requirement". As you know "requirements" are information in ESPD that must be filled by CA. What is the relation between evidences and requirements??
Finally, even if we have a "common root", I didn't see a command in e-CERTIS that allow CA to see all evidences related to different national criteria for the same EU criterion. Could you give me this information??
Thank you.
Francesco

**Comment by paulakeen** [comment]
My bad! apologies for using the term "Requirement" in this context. The origin of the confusion for you is that we are right now evolving the Core Criterion and Evidence Vocabulary ([CCCEV](https://github.com/SEMICeu/CCCEV/issues/2#issuecomment-593864412)) and what in the current version of the ESPD is named "Criterion Property" in the latest CCCEV is now called "Requirement". 

We're precisely now trying to produce an example of how the current ESPD criteria taxonomy can be expressed using the new version of the ESPD. Hopefully this should also contribute to clarify where evidences can be/should be attached to. 

If I understand well, the evidence should be attached to the class Criterion. In the new CCCEV model the evidence is attached to the "InformationRequirement" class, as it is considered (as defined therein) as the element that defines the expected evidence.

**Comment by GPsellitto** [comment]
it is likely that we are trying to tie together too many things, here.
My main concern was not deriving a theory of the Criteria and Evidence in a bottom-up fashion. 
Simply, I was using what I have at hand (the **Current** data model, the Current version of e-Certis) and trying to have a working and robust solution for the ESPD, that permits cross-border and cross-organizational interoperability and leverages e-Certis at the best of its possibilities.
Without violating the Data Model integrity

**Comment by paulakeen** [comment]
@ermeio: Agree!

**Comment by ec-mcs** [comment]
I think we can close this issue as there is a common understanding that all national laws must be represented in eCertis and not only the ones that are used in addition. Please feel free to ask to open it again if necessary.
