### ISSUE TITLE
PropertyDataType in Criterion 30: SC-GENERAl_AVERAGE_TURNOVER

### ISSUE THREAD

**Issue by lbota** [OP-TED/ESPD-EDM#265]
Dear ESPD team,

During the development of SEMIC we have found that in Criterion 30 of both Basic and Extended taxonomies the QUESTION/REQUIREMENT “Number of fiscal years” data types were changed to QUANTITY_INTEGER from AMOUNT in the latest ESPD version. While this change is much a better fit for it, we would like to propose to refine even more the data type by using QUANTITY_YEAR, that is already present in ESPD’s CL.

The QUESTION_GROUP/REQUIREMENT_GROUP we are referring to are:
-	Basic: e1886054-ada4-473c-9afc-2fde82c24cf4
-	Extended: 53882893-f4a8-40ae-99dc-cad7b0748790

Please note that in the latter, the REQUIREMENT_GROUP is wrongly closed, as cardinality, UUID and ElementCode are present at element closure, but the closing bracket “}” is missing:

![issue](https://user-images.githubusercontent.com/35966057/78220667-3b902000-74c2-11ea-975b-eb978df59f4d.png)

We hope you find these remarks useful.

Kind regards,
SEMIC team

**Comment by AFSOLUZIONI** [comment]
Hi,
you're right!
In my analisys of 2.1.1 extended I found the same remarks,
Francesco

**Comment by hricolor** [comment]
After carrying out the analysis and present in the OUC meeting (Wednesday 17 of June), for this issue the PropertyDataType will be changed from QUANTITY_INTEGER to QUANTITY_YEAR, to better represent the content expected for "Number of fiscal years". Also, the errors found in the Criteria Taxonomy will be corrected. 

This issue will be fixed in the new version of ESPD.
