### ISSUE TITLE
New criteria in extended 2.1.1 taxonomy

### ISSUE THREAD

**Issue by AFSOLUZIONI** [OP-TED/ESPD-EDM#266]
Hi,
In the 2.1.1 extended taxonomy we found three new criteria (#65 to #67).
If #65 seems to substitute a "static" portion of OE definition (see fig below)

![image](https://user-images.githubusercontent.com/44367854/79367242-d3bfe780-7f4d-11ea-9ade-f065c22910f5.png)

I have some doubt about #66 and #67: Where we must insert this two criteria??
In my opinion the right position is Part II Section A. 
Am I right??
Thank you for your response.
Francesco

**Comment by hricolor** [comment]
Hi Francesco, 

As you comment, in case of the criterion #65, it is established by the ESPD Directive 2014/24/EC that it is included within the Part II section A. You can read it in the following image: 
![image](https://user-images.githubusercontent.com/60606496/79538683-19cb9700-8085-11ea-97bd-0dfc23492f31.png)

As can be read in the directive, it is an element with statistical purposes concerning the EO information. 

For criterions #66 and #67, we would like to involve @ec-mcs on the resolution of the doubts you raised. From our understanding, our proposed solution could be the inclusion in the Part II section A. It is due to the fact that both criteria are referring to other directives than 2014/24/EC.  Therefore, as they concern about EO information, it could be possible to add them to this section of the ESPD (Part II section A) as you commented. 

Thank you,

**Comment by hricolor** [comment]
We would like to apologise for the delay. We are currently discussing it internally and it is taking more time than expected. The issue is related to Directives which are being analysed and discussed under the scope of eCertis. Therefore, the complexity of the issue is deeper than initially expected.  

We will come back with an answer once we have a consistent solution.

**Comment by AFSOLUZIONI** [comment]
Hi,
don't worry!
I have other question to make about Lots selections and so on.
Implementing the new release of taxonomy we had some difficult and we need your help.
Hear you soon,
Francesco

**Comment by realeroberto** [comment]
Dear @AFSOLUZIONI, dear @hricolor, I've noticed it as well. Thanks for taking the time to discuss the issue.

**Comment by hricolor** [comment]
As agreed during the OUC from **_09th July 2020_** see [minutes](https://github.com/ESPD/ESPD-EDM/blob/wgm-reports/ESPD_Minutes_OUC_Meetings_20200709_v1.1.pdf), both criteria were removed from ESPD 3.0.0.
