### ISSUE TITLE
Criterion #36 ESPD 2.1.1 Extended

### ISSUE THREAD

**Issue by AFSOLUZIONI** [OP-TED/ESPD-EDM#270]
Hi,
I had two errors in submitting an ESPD Request 2.1.1 XML to the european validator (https://www.itb.ec.europa.eu/espd/upload) related to criterion #36 
The problem is depending of Element Code of two subgroup (see fig. below) 
![image](https://user-images.githubusercontent.com/44367854/83744738-dfca4a80-a65c-11ea-85ba-9f7c1d57311f.png)
We add the value "ON*" because our application must have a value between "ONFALSE", "ONTRUE" or "ON*". But this changes cause the two errors in the validator.
In my opinion the taxonomy must be changed inserting the two missed values.
Am I wrong??

Francesco

**Comment by hricolor** [comment]
Dear Francesco,

We are going to analyse what you are suggesting, and we will come back to you with an answer as soon as possible.

Thank you,
Héctor.

**Comment by hricolor** [comment]
After present the issue in the OUC meeting (Wednesday 17 of June), the issue will be fixed in the next version of the ESPD by adding the Element Type ON* to these questions subgroups that currently do not have it. This change is to ensure proper data processing. 

This issue will be fixed in the new version of ESPD.
