### ISSUE TITLE
Criteria #25, 26 - extended - (trade and commercial registers): logical error

### ISSUE THREAD

**Issue by rantati7** [OP-TED/ESPD-EDM#273]
In criteria 25 (professional register) and in criteria 26 (commercial register) there is a logical error. It does not make sense that the CA defines the **name of the register** nor **URL** for it. 

Reason:
Buyer cannot require the seller to belong to certain national register as all registers in EU are equally good. 

Correction on CA side:
Name of register change to requirement (for the register).
URL delete. URL for the register is already asked in seller response..

[ESPD issues.pptx](https://github.com/ESPD/ESPD-EDM/files/4877729/ESPD.issues.pptx)

**Comment by ec-mcs** [comment]
If we can make it easier, then better. 
When it comes to digitize the processes to help the CA, what would be necessary (or not necessary). Are there specific registers for specific domains (more fine granular than works, services or supply). Is it okay if the supplier can mark that they are in 'a' professional register, or do they need to be in a register of the same/similar type in another country? In some, it might be even that such a professional register is not available. 
What is your view?

**Comment by rantati7** [comment]
Trade register is easier. Those - usually - exist in a country - and at least majority of of the bidders belong to such a register. 

Professional registers are much more difficult. CA should be able to define in what kind of register the EO or employees of EO have to belong to e.g. registered nurse, pharmacist, architect,  etc. **On a second thought:** can we even define what register they have to belong to ... I mean are we again is a situation where we can only define that they have to have ELIGIBILITY to belong to a professional register. I do not think (unless it is stated by other laws) the EO / employees of EO have to belong to a certain register.

Can we make this more granular: NO. There are possibly thousands of variations in EU. Existing in some countries and elsewhere not.

**Comment by ec-mcs** [comment]
Indeed, EOs should not belong to a certain register. Therefore the CA should not define that they have to belong to a certain register.

There are two options that I see:

# Option 1

## Flow

* CA in EE -> Ticks the box that the EO should be registered in a professional register
* EO in FI -> Provides the name and probably the URL of the register
* CA in EE -> Evaluates the ESPD. As they do not understand if it is the right one, they need to check more thoroughly

## Advantages

* Easy technically to implement
* Easy to maintain

## Disadvantages

* Cannot digitise the process. The evaluation and processing will likely always be manual
* EO could be in any kind of register (provides accidentally wrong data)
* CA needs to validate the response manually

# Option 2

## Flow

* CA in EE -> Provides the area where the EO should be registered in a professional register
* EO in FI -> Provides the name and probably the URL of the register
* CA in EE -> With the help of eCertis the CA can see that the register is equivalent to the FI one.

## Advantages

* Process can be digitized
* Helps to remove uncertainty on both sides

## Disadvantages

* A codelist must be maintained to capture the areas (there might already be something like this)
* Data model is slightly more complex due to the area
* Editors must maintain data in eCertis

# Discussion

* Both options have their advantages and disadvantages. 
* We can start with the simpler version and decide later on how to proceed.
* We could indeed remove the possibility for the CA to provide the name of a register and a URL

**Comment by rantati7** [comment]
Let me comment the options: 

Generally this would work with trade registers but not with professional registers. 

For example I do not know - and I think it is not even possible to find out - all professional registers so that I could list them in eCertis for Finland. Some may be domestic but I think there could be some that are "international or at least EU-wide" e.g. in aviation. EU has provided this list of banned airlines in EU - if there was no EU wide register this could not have been provided: https://ec.europa.eu/transport/modes/air/safety/air-ban/search_en

I support option 1 (for the start) but with the following changes: 

Trade register -> CA can tick a box that EO must be registered in a trade register in the country of its establishment and EO can reply to this which trade register it is registered in. Or just tick a box as I don't really care at this stage in which trade register they are registered in. It is only later that I would ask proof of this from the EO.

Professional register -> Here CA cannot just tick a box. CA needs to name **what type of register** the EO should belong to. _Hence there must be a field where the CA can write the requirement_. There are many professional registers and the EO would not know what type of register she needs to be registered in unless the CA names the type of register.

Trade register can be partially digitized. 
Professional register cannot. 

An another practical issue related to professional registers:

In part IV C (technical and professional ability) there is a question on professional and educational qualifications. However the question limits this to the EO itself and/or its **managerial staff**. If I want to hire a flight crew to fly me somewhere - or a medical doctor - I certainly want them to be qualified and registered in the required professional register (both have registers for qualified persons) **even if the persons are not part of EO managerial staff.** Otherwise, where else would I put this requirement in ESPD??

**Comment by psotofer** [comment]
Greetings,

We are analysing the options you comment and will come back as soon as possible.
Please, don't hesitate to add any other detail you consider could be of help.
Thank you.
 
Best Regards.

**Comment by AJDAKOST** [comment]
Here we agree with Timo’s remark that “it does not make sense that the CA defines the name of the register nor URL for it. Buyer cannot require the seller to belong to certain national register as all registers in EU are equally good.”

**Comment by hricolor** [comment]
Dear all, 

After present and discuss this issue in the OUC of 29th October, it was agreed on the following solution: 

Remove the current requirements where the CA provides the Name and the URL of the registered where the EO should be registered. 

Instead, include a requirement to specify the register type (area). This will be specified using an ad-hoc code list including different type of registers that are available at the EU level. The code list will be created taking into account the inputs from different OUC members. Moreover, the code list will include the option to specify “other”, and allow CAs to specify any register type not included in the code list. 

Taking into account these inputs, we encourage you all to provide any input that will be taken into account for the building process of the code list. 

This solution will be implemented in the next ESPD 3.0.0.

Thank you.

**Comment by psotofer** [comment]
As commented before, this issue was included in the last ESPD-EDM Release v3.0.0. therefore we proceed to close this issue.
In case you need further detail regarding this topic, please open a new issue referencing this one.
