### ISSUE TITLE
ɑ: Global indication for all selection criteria

### ISSUE THREAD

**Issue by AJDAKOST** [OP-TED/ESPD-EDM#279]
In accordance with Commission Implementing Regulation (EU) 2016/7 of 5 January 2016 establishing the standard form for the European Single Procurement Document the Global indication for all selection criteria is mandatory. In Part IV of ESPD: “Selection criteria” the indication is missing. Is there any particular reason why it is not included?

**Comment by ec-mcs** [comment]
The global indicator for the selection criteria, cannot work with the extended version of the ESPD, only with the 'simple' version. The reason is that the ESPD according the regulation is designed in such a way that the CA cannot provide any useful information in the ESPD request to the EO. All information must be provided in the procurement documents. The extended version allows (or even enforces) that the information, the CA would provide in the procurement documents, are directly included in the ESPD. So for the EO to understand the selection criteria, they must go through the selection criteria and answer them directly there.

**Comment by hricolor** [comment]
Many thanks for your contribution @ec-mcs, 

Since the doubt is resolved, we proceed to close the issue.
