### ISSUE TITLE
Part IV, Section C (Tools, plant or technical equipment)

### ISSUE THREAD

**Issue by rantati7** [OP-TED/ESPD-EDM#28]
**Tools, plant or technical equipment**

CA must be able to define minimum criteria

**Comment by paulakeen** [comment]
We close this issue, for it's been unified with issue #18

**Comment by paulakeen** [comment]
Please find below what was commented about this issue in the discussion group:

Timo Rantanen / Hansel / Finland: because not the CA can define more

Timo Rantanen / Hansel / Finland: yes

Robin: Yes, just a bar. No score

Giampaolo SELLITTO: YEs there are contracts where some machines are needed like mini submarines for perspection under rivers or lakes

Robin: Yes, better to clear these things early.

Jose Luis Cueva (Spai): yes

**Comment by paulakeen** [comment]
Please find below a proposal of mock-ups, both for the view of the CA and the view of the EO.

- View of the CA:
![image](https://cloud.githubusercontent.com/assets/16134316/25664383/bcd21be0-301a-11e7-868d-2ed635cda2f0.png)

- View of the EO:
![image](https://cloud.githubusercontent.com/assets/16134316/25664396/c5d26088-301a-11e7-8275-e31b2719c19c.png)

**Comment by paulakeen** [comment]
Please find the details of the final decision in https://github.com/ESPD/ESPD-EDM/wiki/22.-Tools,-plant-or-technical-equipment
