### ISSUE TITLE
Part II: “Information about the economic operator / Information concerning subcontractors on whose capacity the economic operator does not rely”

### ISSUE THREAD

**Issue by AJDAKOST** [OP-TED/ESPD-EDM#281]
In the case of positive answer to the question in Part II: “Information about the economic operator / Information concerning subcontractors on whose capacity the economic operator does not rely”, the supplier has to provide a CPV code. What is the purpose of providing the CPV code in this part of the ESPD? We think that this data is unnecessary.

**Comment by hricolor** [comment]
Hi, as can be read in the Criteria Taxonomy, for this specific criterion the information related to the CPV is not mandatory. Meaning that it has an informative purpose. At this point, this information can help the CA to know which company and the area of business that it covers, and the alignment with the subject of the contract provided by the CA.

Since the doubt is resolved, we proceed to close the issue.
