### ISSUE TITLE
Part IV: Selection criteria, C: Technical and professional ability (CA`s)

### ISSUE THREAD

**Issue by AJDAKOST** [OP-TED/ESPD-EDM#287]
CA`s side

Part IV: Selection criteria, C: Technical and professional ability

Criteria:
Subcontracting proportion
For supply contracts: samples, descriptions or photographs without certification of authenticity
For supply contracts: samples, descriptions or photographs with certification of authenticity
For supply contracts: certificates by quality control institutes

We suggest adding window Requirement as non-obligatory data, as it is used for example in Criteria: For works contracts: technicians or technical bodies to carry out the work.

**Comment by hricolor** [comment]
Hi, many thanks for all your questions and inputs. 

We will check your inputs and provide an answer as soon as possible. 

Thank you!

**Comment by AJDAKOST** [comment]
Thank you for your reply and all the answers.

**Comment by hricolor** [comment]
Hi all, (@AJDAKOST , @ec-mcs )

We have been analysing and checking the possibility of adding the requirement window as optional in the criteria proposed above: 

•	Subcontracting proportion
•	For supply contracts: samples, descriptions or photographs without certification of authenticity
•	For supply contracts: samples, descriptions or photographs with certification of authenticity
•	For supply contracts: certificates by quality control institutes

It could be possible to add a requirement optional by using a cardinality of 0..n. However, it would be useful to continue the analysis if additional information on business needs regarding this addition could be provided. Find below an example with the subcontracted proportion criteria. Note that the cardinality is 0..n to allow the optional use. The element UUID is not provided since it would be provided once agreed on the inclusion. 

![image](https://user-images.githubusercontent.com/60606496/124899782-bce93300-dfe0-11eb-90a2-129b9136a8b4.png)


Moreover, we have checked the example pointed out in the first comment of the issue “For supply contracts: certificates by quality control institutes” and it includes a requirement with a cardinality of 1. It means that is required and not optional. 

 
![image](https://user-images.githubusercontent.com/60606496/124898679-b4dcc380-dfdf-11eb-96d1-46d126fa3770.png)


Do you think that in this case, it should have a cardinality of 0..n?

**Comment by psotofer** [comment]
Hi all, (@AJDAKOST , @ec-mcs )

Could you provide feedback to further work in this issue?
Thank you.

**Comment by AJDAKOST** [comment]
Hello,

we forward your suggestion to our IT service and we are waiting for replay.

Best regards,

Ajda

**Comment by AJDAKOST** [comment]
Hello,

I`m very sorry for really late response. Your solution (that in this case, it should have a cardinality of 0..n) is acceptable for us. Thank you very much.

Best regards, Ajda

**Comment by psotofer** [comment]
Could you confirm if commented Requirement Group for criterion 'For works contracts: technicians or technical bodies to carry out the work' (work-tech) is alright with a cardinality of 1?
![image](https://user-images.githubusercontent.com/67598083/150780232-ccd8ca15-98e8-4c1c-a913-390a3989eb4f.png)

**Comment by psotofer** [comment]
Greetings, Could you answer our last question? Thanks.

**Comment by AJDAKOST** [comment]
Hello,

we confirm commented Requirement Group for criterion 'For works contracts: technicians or technical bodies to carry out the work' (work-tech) is alright with a cardinality of 1.

Best regards, Ajda

**Comment by acolomer** [comment]
Thank you for your comments. This will be fixed in a future ESPD release.

**Comment by AJDAKOST** [comment]
Hi,
we have another question regarding Part IV: Selection criteria, C. Technical and professional ability. At the beginning there is a field “One or more criteria will be weighted”. If the answer is “Yes”, the EO must fulfil “Criterion Weighting Type” and “Provide the general method used to score and evaluate the weighted criteria” (optional field).

Could you please explain what is the purpose of this field on EO's side?

Thank you and best regards,
Ajda

**Comment by acolomer** [comment]
Good afternoon,
Weighting was removed in ESPD v3.0.0, released on April 2021, and previous versions are no longer maintained.
Kind regards,
The ESPD Team

**Comment by AJDAKOST** [comment]
Hi,

Thank you for the clarification.

Best regards,

Ajda

**Comment by acolomer** [comment]
Good afternoon,
We thank you for your comments.
Optional requirement section has been added to the criterion 51 with cardinality 0..n. A new UUID has been generated:  75b14cf3-c30f-4b8f-b9ab-549ff5ba595a.
![Imagen1](https://user-images.githubusercontent.com/24680296/177990577-f59bdafb-1cff-4485-8b1c-0c4a199e68e8.png)
The ESPD-criterion.xml has been generated in a [specific branch](https://github.com/OP-TED/ESPD-EDM/tree/criterion-evolution/xml-examples)
This will be released it in the next version.
We therefore close the ticket.
Kind regards,
The ESPD-EDM Team.
