### ISSUE TITLE
Part IV: Selection criteria, C: Technical and professional ability - Subcontracting questions

### ISSUE THREAD

**Issue by rantati7** [OP-TED/ESPD-EDM#29]
**Subcontracting proportion**

This is very problematic question. The same is asked already before in PART II. Why not move this question next to the subcontracting questions?

**Comment by lauramrtn** [comment]
We agree - it seems sensible to keep all sub-contracting questions together.

**Comment by paulakeen** [comment]
Please find below what was commented about this issue in the discussion group:

Giampaolo SELLITTO: In general it is asked the proportion of the contract to be subscontracted since there are legal contraints on how much you can subcontract

Anne Katrine, NIRAS A/S, DK: I agree

Giampaolo SELLITTO:  yes

Laura and Steve (Scottish Government): lesve in proportion please

Anne Katrine, NIRAS A/S, DK: It makes sense to leave it in

Laura and Steve (Scottish Government): Agree, it's for info only

Timo Rantanen / Hansel / Finland: yes

Timo Rantanen / Hansel / Finland: still yes

Laura and Steve (Scottish Government): This is about the goods themselves, nott he company

Anne Katrine, NIRAS A/S, DK: I agree

Robin: Agree

Timo Rantanen / Hansel / Finland: we do continiuos inprovement to our online "self-contained" ESPD every day ... unfortunately

**Comment by paulakeen** [comment]
It's been agreed that no changes are required for this criterion.
