### ISSUE TITLE
Duplicate "Question Group UUID" in the same Criterion and the Question Groups have different structures #interproc

### ISSUE THREAD

**Issue by konstantinosraptis91** [OP-TED/ESPD-EDM#320]
hey,

By traversing the ESPD-criterion-V3.0.0 excel sheet I encountered a duplicate "Question Group UUID" in Criterion number 40 (qual-cont-tech) and 41 (work-tech) in Question Groups with different structures. In my understanding, the value of a "Question Group UUID" matches with a specific Question Group structure. This behavior is followed in all the other Criteria, so in my opinion, this is a possible bug.

The "Question Group UUIDs" that appear to be duplicate are:

1. 52ffcf91-3598-438f-8c3d-faf97da02602
2. 9026e403-3eb6-4705-a9e9-e21a1efc867d
3. 0a166f0a-0c5f-42b0-81e9-0fc9fa598a48

Below there is a snapshot that shows the issue in Criterion 40 (qual-cont-tech)

<img width="947" alt="Στιγμιότυπο 2022-01-20, 8 16 51 μμ" src="https://user-images.githubusercontent.com/15834471/150399199-17aa1ded-21cd-4a09-9cb6-633206235923.png">

**Comment by psotofer** [comment]
It is true that **UUID** _52ffcf91-3598-438f-8c3d-faf97da02602_ should not be assigned to different structures as you show in your image. We will study the best way to fix this deviation from the **ESPD-EDM** specification and will keep you informed.

It is worth of note that even if this case does not complies with the **ESPD-EDM** specification it presents no risk because the **QUESTION_SUBGROUP** **UUID**s are not used to identify the **QUESTION** response. The relationship between **QUESTION** and response value is defined by the **QUESTION UUID** created dynamically and provided in the **ESPD Request**.
 
On the other hand, the other two **UUID**s that you point out (_9026e403-3eb6-4705-a9e9-e21a1efc867d_ and _0a166f0a-0c5f-42b0-81e9-0fc9fa598a48_) are correct as they identify the same QUESTION_SUBGROUP structure.

**Comment by konstantinosraptis91** [comment]
Yes you are right, 9026e403-3eb6-4705-a9e9-e21a1efc867d and 0a166f0a-0c5f-42b0-81e9-0fc9fa598a48 are correct. The issue appears only with 52ffcf91-3598-438f-8c3d-faf97da02602.

**Comment by psotofer** [comment]
Hello,
We will discuss the best way to deploy this fix in a future release and will keep you informed.
Thank you.

**Comment by acolomer** [comment]
Good morning,
We thank you for your comments.
Criteria 40 and 41 for question subgroup structures: "Technician" and "Technical body" are the same but the structures are different. To solve the reported issue, a new UUID has been generated in Criteria 40 and 41 for structure "Technical body": 70e28455-d0e1-47e7-9caa-ead3b7df7644. This is available in the master branch and it will be released it in the next version.
We therefore close the ticket.
Kind regards,
The ESPD-EDM Team
