### ISSUE TITLE
ProfileID version

### ISSUE THREAD

**Issue by nico3dfx** [OP-TED/ESPD-EDM#324]
Hi,
inside version 2.1.1 of ESPD the value shoud be "41" but for the [ESPD validator](https://www.itb.ec.europa.eu/espd/upload) the correct value is "4.1", the same value inside che schematron file 04 ESPD Common Other BR.xsl

**Comment by psotofer** [comment]
Greetings, 
We are checking this case and will come back to you as soon as possible.

**Comment by acolomer** [comment]
Good afternoon,
We thank you for the comments.
Please take into account that your question is related to v2.1.1, we inform you we no longer maintain this version.
Since this is a known non-blocking issue, we suggest you to provide value 4.1 instead of 41 to bypass this case, and we inform you that in next release this schematron rule won't apply.
Kind regards,
The ESPD-EDM Team
