### ISSUE TITLE
Groups with same UUID and different cardinality

### ISSUE THREAD

**Issue by nico3dfx** [OP-TED/ESPD-EDM#327]
Hi,
the group with UUID **10822ddd-9ba6-42d5-9339-de0845aeafc9** have different cardinality inside the file **ESPD-criterion.xlsx**

Inside the criterion #48 the cardinality is **1..n** but inside the criterion #50 the cardinality is **1**

The same is for other groups, with UUID:
- **289f39b3-2a15-421a-8050-a29858031f35**: differents cardinality are **1** and **1..n**
- **5f9f09f7-f701-432c-9fdc-c22c124a74c9**: differents cardinality are **1** and **0..1**
- **74e6c7b4-757b-4b40-ada6-fad6a997c310**: differents cardinality are **0..1** and **[empty]**
- **9026e403-3eb6-4705-a9e9-e21a1efc867d**: differents cardinality are **1** and **0..1**
- **a53561d5-6614-4dbe-987e-b96f35387f46**: differents cardinality are **0..n** and **1..n**
- **c0cd9c1c-e90a-4ff9-bce3-ac0fe31abf16**: differents cardinality are **1** and **1..n**
- **cc1da737-6c4e-4f4e-821d-c260029058f6**: differents cardinality are **0..1** and **1..n**

**Comment by acolomer** [comment]
Good afternoon,
We thank you for your comments.
To solve the reported issue:
- 10822ddd-9ba6-42d5-9339-de0845aeafc9: differents cardinality are 1 and 1..n : different structures, a new UUID has been generated and assigned to criterion 50: add786b6-7e75-4303-8b9a-3d477331abd9
- 289f39b3-2a15-421a-8050-a29858031f35: differents cardinality are 1 and 1..n : the issue does no longer exists since version 3.0.1 and older versions are not under support, so no changes are necessary.
- 5f9f09f7-f701-432c-9fdc-c22c124a74c9: differents cardinality are 1 and 0..1 : cardinality is wrong in criterion 22,it has been updated to 1
- 74e6c7b4-757b-4b40-ada6-fad6a997c310: differents cardinality are 0..1 and [empty] : empty cardinality is wrong in criteria 18 and 19, it has been updated to 0..1
- 9026e403-3eb6-4705-a9e9-e21a1efc867d: differents cardinality are 1 and 0..1 : cardinalities 0..1 in criteria 40 and 41 are wrong, have been updated to 1
- a53561d5-6614-4dbe-987e-b96f35387f46: differents cardinality are 0..n and 1..n : cardinality is wrong in criterion 26, it has been updated to 0..n
- c0cd9c1c-e90a-4ff9-bce3-ac0fe31abf16: differents cardinality are 1 and 1..n : cardinality is correct as this criteria is for Yearly Turnovers (more than one value, usually 3 years) while Average Turnover is just one single value, so no changes are necessary
- cc1da737-6c4e-4f4e-821d-c260029058f6: differents cardinality are 0..1 and 1..n : UUID has been removed as it´s a structure close line
The fixes have been implemented it in the [criterion-evolution branch](https://github.com/OP-TED/ESPD-EDM/tree/criterion-evolution) and will be released it in the next version.
We therefore close the ticket.
Kind regards,
The ESPD-EDM Team
