### ISSUE TITLE
Same requirement group UUID with different content

### ISSUE THREAD

**Issue by arunas-z** [OP-TED/ESPD-EDM#333]
I assumed UUIDs for property groups exist to facilitate re-use, however 53c9aad8-dc80-48f8-85d9-755c2aab8e95 in Taxonomy excel has different content in exclusion grounds and selection criteria:

![image](https://user-images.githubusercontent.com/30899510/172320345-2241b5cf-e769-4b55-9e55-2c60fcd0fc74.png)

![image](https://user-images.githubusercontent.com/30899510/172320363-f78ab431-d520-4710-83a0-afb5a7dc328e.png)

**Comment by JennyBV** [comment]
Hello! We are working with this within the Interproc project and it is very important to get clarifications about this. Hope to hear from you soon!

**Comment by konstantinosraptis91** [comment]
Just to add more on this issue, I think this is similar to the one I had reported and more specifically the issue [https://github.com/OP-TED/ESPD-EDM/issues/320](url). I found that this UUID (53c9aad8-dc80-48f8-85d9-755c2aab8e95) is used in criteria with numbers 7, 8, 37 and 39 based on Criteria Taxonomy numbering. The problem is that in Criteria 7 and 8 the structure looks like this:

![Στιγμιότυπο 2022-06-30, 1 06 56 μμ](https://user-images.githubusercontent.com/15834471/176656265-ff6b55f5-3cb2-4205-b269-706c2ae9811a.jpg)

and in Criteria 37 and 39 the structure is different and looks like this:

![Στιγμιότυπο 2022-06-30, 1 09 40 μμ](https://user-images.githubusercontent.com/15834471/176656455-bf394c1b-e68e-459d-9ada-083043f3fb59.jpg)

As you see the structures look totally different and this violates the standard that the value of a Question Group/Requirement Group UUID matches with a specific Question Group/Requirement Group structure and vice versa.

**Comment by ghost** [comment]
Good afternoon,
We thank you for your comments.
To solve the reported issue, a new UUID has been generated for the structures in criterias 7 and 8: c7d60cb5-b6fc-4e1a-a6b0-e0d91a09c80a. This will be released it in the next version.
We therefore close the ticket.
Kind regards,
The ESPD-EDM Team.
