### ISSUE TITLE
Questions regarding the purely national EG in ESPD-EDM v3.x.x #interproc

### ISSUE THREAD

**Issue by konstantinosraptis91** [OP-TED/ESPD-EDM#334]
Hello ESPD team

In the context of the InterProc project, we are trying to understand how to implement the "Purely National EG" in ESPD version 3.x.x. According to the technical handbook and more specifically in [Figure 88](https://docs.ted.europa.eu/ESPD-EDM/3.0.1/xml_technical_handbook.html#_mock_up_economic_operator_perspective) it is possible to have multiple purely national EG and the text above the figure says that those national criteria that are displayed in the figure have been captured from e-Certis. As we see by retrieving the "Purely National EG" parent criterion (EU Criterion) from e-Certis, there is a sub-Criteria list in the XML format, which includes all "the purely national EG" for different countries/jurisdictions that are available in e-Certis. By looking at the relevant criterion from the ESPD perspective in the Taxonomy, we see that the placeholder for those "Purely National EG" is different at the syntax binding level in the ESPD-EDM.

![Στιγμιότυπο 2022-06-15, 5 18 21 μμ](https://user-images.githubusercontent.com/15834471/173850137-6e21ffc7-92e6-4154-b623-288d097f8575.png)
*Figure 1 - Purely National EG Criterion Original Structure*

![Στιγμιότυπο 2022-06-15, 5 21 44 μμ](https://user-images.githubusercontent.com/15834471/173851481-5180afa2-10de-463f-ba0d-245144269531.png)
*Figure 2 - Purely National EG Criterion Structure which includes 2 Purely National EG Criteria*

If we understand it correctly the structure of this particular criterion in Taxonomy doesn't include a sub-criteria list, but instead of that uses the internal sub-group with cardinality one-to-many as a placeholder for multiple "Purely National EG". So for instance, if we had a case where a country has two "Purely National EG" the structure would expand like in Figure-2 to include both of those "Purely National EG". If our logic is correct and in combination with the first requirement mentioned in the technical handbook (see Figure 3) the e-Certis service MUST be able to provide those two individual "Purely National EG" criteria and also allow the Member State to include individual "Purely National EG".

![Στιγμιότυπο 2022-06-15, 5 42 54 μμ](https://user-images.githubusercontent.com/15834471/173855680-f56c38e0-30a7-4984-9c5b-633494ea2175.png)
*Figure 3 - First Requirement in Purely National Criteria Section*

<ins>Question 1</ins>
Is the logic expressed above regarding the "Purely National EG" correct?
<ins>Question 2</ins>
Is e-Certis capable of providing multiple "Purely National EG" criteria? Because by looking at the available options from e-Certis's perspective as an editor we are not sure if it is possible to edit the "Purely National EG" criterion to add more "Purely National EG" criteria.

**Comment by Nikanoras** [comment]
We are working on this part also in our application. Would be great to get an answer to this question.

**Comment by JennyBV** [comment]
This is a very important question! Would be great with input on this.

**Comment by pascalinelaur** [comment]
Hello,

Thank you for your questions.

For  Question 1, the answer is yes. The logic that you expressed regarding the "Purely National EG" criterion is correct.

We have created an xml file test from a copy of the ESPD-request that includes the question subgroup with multiple cardinality "1..n" replicated twice, as proposed above. The file has passed the validation with the ESPD Validator available at "https://www.itb.ec.europa.eu/espd/upload".

That means that the multiple cardinality "1..n" allows to provide more than one Purely National EG criterion. The model is consistent whether there is only one or several corresponding eCertis criterion.

Please feel free to reproduce the test taking the ESPD-request file from the master branch and come back to us if you encounter any troubles: https://github.com/OP-TED/ESPD-EDM/blob/master/xml-examples/ESPD-Request.xml.

For Question 2, as discussed during the last [OUC meeting held on 16 June 2022](https://docs.ted.europa.eu/espd-ouc/20220616_OUC%20meeting%20report.html), the issue is under discussion on eCertis side. The ESPD  only reuses the existing Purely National EG criterion from eCertis.

Kind regards,
The ESPD Team.

**Comment by Nikanoras** [comment]
Hi @pascalinelaur 
Follow-up question. 
How do we handle `Is this information available electronically?` Because the current structure implies to have one question for all questionsubgroups, but the mockups in the technical handbook shows for each subgroup
![Purely_national_criteria_mockup_CA_perspective](https://user-images.githubusercontent.com/37303011/176680583-e81bca9b-ddad-4aef-b6d6-9ce5cb057ebe.jpg)

**Comment by pascalinelaur** [comment]
Hello @Nikanoras, Hello @konstantinosraptis91, 

Thank you for your follow-up question.

Indeed, there is a difference between the mockup (from the online technical handbook documentation on exclusion criteria) and the data structure of criterion C24 nati-ground Purely national exclusion grounds. We have analysed this difference and here is our first outcome. 

We have to decide whether to :

1. Update the Mockup (Keep the Data Structure as it is). Even if the mockup illustration is more intuitive we should keep the consistency with the use of the Question Group or Subgroup (QG, QSG) about evidences in other criteria (C1, C2, C3, C32). 

Or to : 

2. Update the Data Structure (Keep the Mockup as it is). This is to have a more natural (semantic) way of providing evidences that correspond to the related questions.

We will come back to you as soon as a clear choice between the two options has been made.

Kind regards,
The ESPD Team.

**Comment by Frantzenna** [comment]
> Hello,
> 
> Thank you for your questions.
> 
> For Question 1, the answer is yes. The logic that you expressed regarding the "Purely National EG" criterion is correct.
> 
> We have created an xml file test from a copy of the ESPD-request that includes the question subgroup with multiple cardinality "1..n" replicated twice, as proposed above. The file has passed the validation with the ESPD Validator available at "https://www.itb.ec.europa.eu/espd/upload".
> 
> That means that the multiple cardinality "1..n" allows to provide more than one Purely National EG criterion. The model is consistent whether there is only one or several corresponding eCertis criterion.
> 
> Please feel free to reproduce the test taking the ESPD-request file from the master branch and come back to us if you encounter any troubles: https://github.com/OP-TED/ESPD-EDM/blob/master/xml-examples/ESPD-Request.xml.
> 
> For Question 2, as discussed during the last [OUC meeting held on 16 June 2022](https://docs.ted.europa.eu/espd-ouc/20220616_OUC%20meeting%20report.html), the issue is under discussion on eCertis side. The ESPD only reuses the existing Purely National EG criterion from eCertis.
> 
> Kind regards, The ESPD Team.

Dear ESPD Team! 

Open User Community Meeting Report states that "Issue [#334](https://github.com/OP-TED/ESPD-EDM/issues/334), regarding the purely national Exclusion Grounds in ESPD-EDM v3.x.x, will not be solved within the next few months and require a change request on eCertis side". Could you please provide a time estimate when we can expect the solution on eCertis side?  

Thank you in advance!

**Comment by ec-mcs** [comment]
@Frantzenna We currently collect all requirements for eCertis and plan to update it in the course of next year.

**Comment by pascalinelaur** [comment]
Hello [@Nikanoras](https://github.com/Nikanoras), Hello [@konstantinosraptis91](https://github.com/konstantinosraptis91),

Thank you again for your follow-up question.

After discussions, it has been agreed to update the Data Structure because it is by nesting the evidence to its related Question Subgroup that the semantic link between both is created. This is mandatory especially when the related Question Subgroup is of multiple cardinality. However, when the cardinality is single, the update (nesting the Question Group or Subgroup for providing Evidence) can still be performed for semantic and maintenance purpose. Hence, the update will be made for multiple and also single cardinality of the related Question Subgroup.

For the criterion C24 EG nati-ground (EG-Purely_national), the update will look like the following screenshot:

![C24_EG_nati-ground_Evidence_Position_Updated](https://user-images.githubusercontent.com/102807568/190579949-ba1e74ea-6ed8-42e2-b2f8-ee4d25639f56.jpg)

This update will be generalized for the whole Criterion Excel file and will be available in a future release. 

Kind regards,
The ESPD Team.

**Comment by AJDAKOST** [comment]
Hello, 
We have two questions regarding purely national exclusion grounds:
1. Will be possible to select "self-cleaning" for a particular purely national exclusion ground by EO, if he chooses the answer "Yes"? 
2. In the context of the wording "When a CA selects the option “Purely national exclusion grounds” in an ESPDRequest, the criteria available in e-Certis classified as “Other exclusion grounds” must be retrieved. All the criteria will be mandatory, that is, the CA is not able to select specific purely national exclusion grounds for a particular procedure.", whether it will be possible to choose only one purely national exclusion ground? According to our national legislation, all purely national exclusion grounds are mandatory in the general field, but not in the infrastructure field.

Thank you for your reply.

Best regards,

Ajda

**Comment by arillpa** [comment]
Thank you for your question @AJDAKOST ,

1) no, it will not be possible for the EO to select 'self-cleaning' for a particular purely national exclusion ground, if he chooses 'Yes'
2) Could you please clarify what you mean with 'the infrastructure field?

Kind regards
The ESPD-EDM Team

**Comment by AJDAKOST** [comment]
Hello,

1. What solution do you propose if we have the possibility of "self-cleaning" in national legislation for a particular purely national exclusion ground?
2. The "infrastructure field" means procurements by entities operating in the water, energy, transport and postal services sectors.

Thank you.

Best regards,

Ajda

**Comment by dragos-eu** [comment]
Hello @AJDAKOST ,

We created a new GitHub issue #422 that will deal with your request. The solution will be provided in a future version of ESPD.

Kind regards,
ESPD Team
