### ISSUE TITLE
Questions with multiple cardinality when Member States demand a specific order.

### ISSUE THREAD

**Issue by daniel-sousa-lobo** [OP-TED/ESPD-EDM#335]
Sorry if this might be a non issue, but we e found out that some member states demand an specific order for some question, and as there is no field for ordering them, if the questions are, for instance, saved in a database they might get in a different order.
Shouldn't there be a Order field to indicate that undoubtedly?
If I follow the specification to the letter I shouldn't care about the order. But then I might have implementation problems when the authorities demand that ordering. And a field for that would support that need.

![image](https://user-images.githubusercontent.com/19727179/176404224-d1d7d622-3254-44bf-88ee-1e4e38304f55.png)

**Comment by JennyBV** [comment]
We are also following this question with interest. Would be great with some clarifications or suggestions on this. Thank you in advance. /Jenny Bobille-Vaucher, Mercell

**Comment by pascalinelaur** [comment]
Hello   @daniel-sousa-lobo ! Hello @JennyBV  ! 

Thank you for your question. We have been reviewing it and here is our answer. 

First of all, yes, there are no explicit ordering of descriptive criterion elements (Question_Group, Question_Subgroup, Question, Requirement_Group, Requirement_Subgroup, Requirement, Caption, Subcriterion, Legislation). The ordering is rather implicit according to the position of the element in the description at a given level. The first element has the number 1, the second element has the number 2, and so on.

In general, we use UUID to refer to criterion element. We have fixed or static UUIDs that are always known and also dynamic UUIDs that are created when a Request or Response is generated.

For fixed UUIDs, we might need an implicit numbering (combined with the parent ID) only if we have the same structure several times because then we use the same uuid for the same structure group (for instance, "evidences" Question_Subgroup in criterion C40 and C41 that appear twice).

For dynamic UUIDs, let imagine that we save the data in a database when the dynamic UUIDs have not yet been assigned. If we restore the data, the questions might indeed be mixed. Although this use case is not common, we should recommend the use of the implicit numbering to ensure the file is restored as it were in the first place and avoid any conflict. 

About including an explicit numbering for our criterion elements or attributes, this will imply to add a new element or new attribute to our model. However, our model is tightly linked to the UBL language, so we cannot add an element or attribute that is not provided by the language because there is a third dependency with UBL.

Hence, guidelines and recommendations about the implicit numbering of criterion elements should be provided in the online documentation for users and developers of the ESPD project in a future release.

Kind regards, 
The ESPD team.
