### ISSUE TITLE
Descriptive text is not the same in eCertis and Taxonomy #interproc

### ISSUE THREAD

**Issue by JennyBV** [OP-TED/ESPD-EDM#336]
Hello!

This is a question about the content in the ESPD. For some of the exclusion grounds the description text provided in eCertis is not the same as in the Taxonomy, see this example for "Participation in a criminal organisation":

**_Description in eCertis:_**
"Participation in a criminal organisation, as defined in Article 2 of Council Framework Decision 2008/841/JHA of 24 October 2008 on the fight against organised crime"

**_Description in Taxonomy:_**
"Has the economic operator itself or any person who is a member of its administrative, management or supervisory body or has powers of representation, decision or control therein been the subject of a conviction by final judgment for participation in a criminal organisation, by a conviction rendered at the most five years ago or in which an exclusion period set out directly in the conviction continues to be applicable? As defined in Article 2 of Council Framework Decision 2008/841/JHA of 24 October 2008 on the fight against organised crime (OJ L 300, 11.11.2008, p. 42)."

The part starting with "Has the economic operator..." is missing in eCertis. Most descriptions are the same in eCertis and in Taxonomy, but not for these exclusion grounds:

- Participation in a criminal organisation
- Corruption
- Fraud
- Terrorist offences or offences linked to terrorist activities
- Child labour and other forms of trafficking in human beings

We are expecting the descriptive text to be the same in eCertis and in Taxonomy, what is your comment on this? Thanks for any input. //Jenny

**Comment by acolomer** [comment]
Good morning,
Thank you for your comment.
We've been reviewing it and there is an inconsistency. We are currently assessing the different options to solve it. 
Kind regards,
The ESPD Team

**Comment by acolomer** [comment]
Good morning,
Thank you very much for you comment.
We understand this will be included in a future eCertis update. The work is foreseen to start in Q2 this year.
Kind regards,
The ESPD Team

**Comment by srdjankr** [comment]
Dear @JennyBV 

The integration between ESPD and eCERTIS was completed in ESPD v3.3.0. The ESPD Service implementer will retrieve full information from eCERTIS and display it in the interface as per specific national laws and regulations. ESPD provides a generic placeholder for this sections. The ESPD Service will customize the model so that it will accommodate the mandatory fields.

Please let us know if you would like to have more details from our side.

Kind regards,
The ESPD Team

**Comment by srdjankr** [comment]
Dear @JennyBV,

The integration between ESPD and eCERTIS was completed in ESPD v3.3.0. The ESPD Service implementer will retrieve full information from eCERTIS and display it in the interface as per specific national laws and regulations. ESPD provides a generic placeholder for this sections. The ESPD Service will customize the model so that it will accommodate the mandatory fields.

Please let us know if you would like to have more details from our side.

Kind regards,
The ESPD Team
