### ISSUE TITLE
Financial ratio type translations #interproc

### ISSUE THREAD

**Issue by Nikanoras** [OP-TED/ESPD-EDM#337]
Hi,
Looking at the FinancialRatioType.gc file there're some values that contains English text with bul labels. Is this correct?
https://github.com/OP-TED/ESPD-EDM/blob/a48f110463517b1a6c763b25154e5a64a4a9e5f3/codelists/gc/FinancialRatioType.gc#L202-L271

**Comment by ghost** [comment]
Hello,
Thank you for informing us, we have noticed a few other changes that need to be made to this file.
We will analyze the best way to deploy the fixes in a future release and will keep you informed.

The ESPD Team.

**Comment by ghost** [comment]
Good morning,
The error in the FinancialRatioType.gc file has been fixed, there were some problems in the XLST transformation file and in the Excel Codelists file. The fix has been implemented in the [update-codelist branch](https://github.com/OP-TED/ESPD-EDM/tree/update-codelist) and it will be released in a future version.
We therefore close the ticket.
Kind regards,
The ESPD-EDM Team

**Comment by ghost** [comment]
Good afternoon,
in order to provide more information about the resolution of this issue, the files affected that have been modified are:

- [ESPD-CodeLists.xlsx](https://github.com/OP-TED/ESPD-EDM/blob/master/__ESPDTeam__/ESPD-CodeLists.xlsx) : there were some formatting issues related to languages not populated (blank) in the tab for the FinancialRatioType codelist.

- [excel-to-gc-multilang-v1.0.xsl](https://github.com/OP-TED/ESPD-EDM/blob/master/__ESPDTeam__/xslx-codelists-to-genericode/excel-to-gc-multilang-v1.0.xsl) : XSL file used to generate the codefiles from the previous Excel file, there was an issue with a wrong cell position for the status column for the FinancialRatioType codelist (position 5 instead of 4).

- [FinancialRatioType.gc](https://github.com/OP-TED/ESPD-EDM/blob/master/codelists/gc/FinancialRatioType.gc) : the codelist file has been generated again after the implementation of the fixes in the two previous files.

Kind Regards,
The ESPD Team.
