### ISSUE TITLE
Invalid text in Taxonomy in SC-Professional_risk_insurance tab #interproc

### ISSUE THREAD

**Issue by Nikanoras** [OP-TED/ESPD-EDM#338]
In column nr. 25, Code List, in the mentioned tab there's a comment in CodeList column.

**Comment by ghost** [comment]
Hello,
Thank you for letting us know.
We will analyze the best way to deploy this fix in a future release and will keep you informed.

The ESPD Team.

**Comment by ghost** [comment]
Good afternoon,
The fix has been implemented and uploaded into the master branch.
We therefore close the ticket.
Kind regards,
The ESPD-EDM Team

**Comment by ghost** [comment]
Good afternoon,
in order to provide more information about the resolution of this issue: in the Excel criterion file, criterion 35 : SC-Professional_risk_insurance tab, there was a misplacement of two comments in the Codelist column. They both have been moved one column to the right to the proper Comment colum.

The fix is available [here](https://github.com/OP-TED/ESPD-EDM/blob/master/codelists/ESPD-criterion.xlsx) in the master branch.
