### ISSUE TITLE
General yearly turnover - differences in taxonomy and mock-ups from ESPD-EDM

### ISSUE THREAD

**Issue by JustinaZaltauskaite** [OP-TED/ESPD-EDM#340]
Hi,
We started digging into criterias a bit deeper and saw that "General yearly turnover" has few differences in [mock-ups](https://docs.ted.europa.eu/ESPD-EDM/3.0.1/xml_technical_handbook.html#_turnovers) and taxonomy

1. mockups have fields for Fiscal year count and threshold per year, but taxonomy does not have whose fields 
![image](https://user-images.githubusercontent.com/75019622/184306096-795ca33e-a651-4636-a21b-50c64336f137.png)

2. evidence question "Is this information available electronically?" is doubled
![image](https://user-images.githubusercontent.com/75019622/184306620-504cb6a4-1514-4481-9cab-eec91e3b7dc2.png)

3. Question "In case the information concerning turnover (general or specific) is not available for the entire period required, please state the date on which the economic operator was set up or started trading:" does not exist in a mock-up 
![image](https://user-images.githubusercontent.com/75019622/184307026-7083ef78-26d5-422a-9d9d-362966b18247.png)

Feels like something is missing or there is too much in this criteria to properly understand how this criteria works. In our implementation we generate ESPD document directly from taxonomy and this criteria currently looks a bit off, although other criteria (that we implemented) look ok

**Comment by hricolor** [comment]
Good morning,
Thank you very much for your comment.
Regarding your three bullets, we would like to comment on the following:

- Regarding the first bullet: it is accurate that the data structure for the criterion does not include the information that the mock-up shows. Therefore, the data structure needs to be updated accordingly.

    - Within the requirement group a requirement needs to be added to show the number of fiscal years to be covered.
    - The data structure for the second question subgroup has cardinality 1 which needs to be changed to 1..n. 
![Issue340](https://user-images.githubusercontent.com/60606496/185927929-19fac713-bc67-4aa5-bc93-2f2377a9d3b3.png)

- Concerning the second bullet: This question is duplicated because the first time is related to the EO meeting directly the requirements established by the Buyer. And the second question is associated with the set-up of the EO (in cases where the EO was set up at a date not allowing it to fulfil the requirement).

- And the last bullet: The documentation needs to be updated to reflect the question that currently is not depicted.

First bullets will be implemented in the following GitHub branch [https://github.com/OP-TED/ESPD-EDM/tree/criterion-evolution.](https://github.com/OP-TED/ESPD-EDM/tree/criterion-evolution)

We will inform you when the changes are applied.

**Comment by acolomer** [comment]
Good morning,
The fix has been implemented in the following GitHub branch: [https://github.com/OP-TED/ESPD-EDM/tree/criterion-evolution](https://github.com/OP-TED/ESPD-EDM/tree/criterion-evolution).

The criterion excel in the aforementioned link has been updated and the corresponding XML sample file has been generated.
This will be included in a future ESPD-EDM release.
We therefore close the ticket.
Kind regards,
The ESPD-EDM Team

**Comment by JustinaZaltauskaite** [comment]
@acolomer  when does this future ESPD-EDM release  happen?

**Comment by acolomer** [comment]
Good morning,
The scope and calendar for future ESPD-EDM releases will be discussed in the next OUC meeting, scheduled for September 28th.
Kind regards,
The ESPD-EDM Team

**Comment by JelenaCaik** [comment]
Hello @acolomer, @hricolor, @delgajc, 
Thank you very much for your answers. 
It is still not clear for us how to handle checkbox "Threshold per year" shown in a mockup and missing in Taxonomy excel file.
There is no requirement for "Threshold per year" in Taxonomy file. 
How do we need to handle it? 
* Do we need to show N times Amount and currency when checkbox "Threshold per year" is checked?
* Do we need to show only once "Amount and currency" when checkbox "Threshold per year" is empty?
If so, Please update taxonomy as checkbox "Threshold per year" is missing there.
 
![github_question](https://user-images.githubusercontent.com/113527358/191044859-bb8d306f-a890-4e59-abf4-8ac790ea1523.png)

**Comment by hricolor** [comment]
Hi @JelenaCaik, many thanks for your comment again. 
We are reviewing it and will provide you with an answer as soon as possible. 
Best Regards, 
The ESPD team.

**Comment by acolomer** [comment]
Good morning,
Thank you very much for your comment.
As shown in the following image, an intermediate requirement that represents the selection of "threshold per year" is necessary to make it clearer:
![image](https://user-images.githubusercontent.com/24680296/191928005-d2d95373-270f-4729-8491-9f1ef49ad5f9.png)

- A new requirement has been added to the data structures that allows selecting whether it should apply for each individual year or for all years;
- In casi it is for individual yeara, the question_subgroup that has 1..n and is marked in yellow, should be replicated as many times as years required;
- Since there is no other equal data structure, a new UUID has been generated to cover this data structure.
Those changes will be applied within the branch criterion_evolution (to add link) and will end up being implemented in future releases.
Best regards,
The ESPD team

**Comment by acolomer** [comment]
Good morning,
The changes detailed in the previous comment have been applied in branch [criterion_evolution](https://github.com/OP-TED/ESPD-EDM/tree/criterion-evolution) and will be implemented in a future ESPD release.
Best regards,
The ESPD Team

**Comment by JelenaCaik** [comment]
Hello,
I would like to re-open this issue as based on v3.1.0 we can not implement in the same logic, as it is presented in ESPD EDM Technical Handbook mockups. 

![29_criterion](https://user-images.githubusercontent.com/113527358/214040530-8ecb9861-0f86-4306-98e4-efb1aee51169.png)

Based on ESPD-criterion v3.1.0 we need/can to repeat Requirement group N times, and this is not the aim based on mockups:
Buyer (1):
![General_Yearly Turnovers_CA mock-up_ common_threshold](https://user-images.githubusercontent.com/113527358/214041132-85bdd418-2a58-4295-8f34-d9f7f1374bfb.jpg)

Buyer (2):
![General_Yearly_Turnovers_CA mock-up_ commonThreshold](https://user-images.githubusercontent.com/113527358/214041162-efbace4b-46ba-407f-8b96-3671db6e6956.jpg)

EO:
![General_Specific_Yearly_Turnovers_ EO_mock-up](https://user-images.githubusercontent.com/113527358/214041191-2d797a75-073b-4c72-ab09-82a2496bb9a4.jpg)

1. There is a need to change Cardinality for min Requirement group (line 11) - it should be 1.
2.  It should be added ONTRUE and ONFALSE blocks/ groups based on Threshold per year Value:

- ONFALSE, then show Minimum requirement - Cardinality -1,
- ONTRUE, then show Minim requirement Cardinality - 1..n

**Comment by ghost** [comment]
Good afternoon,
cardinalities have been fixed as requested. The corrected version of the criterion excel file is available [here](https://github.com/OP-TED/ESPD-EDM/blob/master/codelists/ESPD-criterion.xlsx) and they will be included in the next patch-release.

Kind Regards,
The ESPD Team.
