### ISSUE TITLE
For service contracts: authorisation (membership) of particular organisation needed: question cardinality

### ISSUE THREAD

**Issue by JelenaCaik** [OP-TED/ESPD-EDM#343]
Selection criteria > Suitability > For service contracts: **authorisation** AND **membership** criterion:

* Buyer's request: Requirement group Cardinality is 0..n, so buyer can check this criteria and do not enter any register name/URL. 
* Seller's response: Should seller get a group of question (as Cardinality is 1..n) even if there is no Register is entered by buyer?

or should be Requirement group Cardinality for CA should be mandatory?

![question2](https://user-images.githubusercontent.com/113527358/190179038-ebc9a080-9598-4a8b-b742-d328e284562b.png)

**Comment by acolomer** [comment]
Good morning,

Thank you very much for your comment.

We have reviewed your isue in detail and have concluded that cardinalities are properly established because:

1. The criterion asks if the Economic Operator requires to be registered in its country of establishment. Therefore, it is not dependent on the Buyer and could not be any constraint.
2. However, the requirement allows the Buyer to restrict the information that the Economic Operator needs to provide, making it possible to include specific register types where the Buyer expects the Economic Operator to be registered.

Therefore, the data structures and the cardinalities are correct in the image you provide.

Best regards, 

The ESPD team

**Comment by JelenaCaik** [comment]
Thank you for you answer @acolomer . We still need to verify the specific case:
1. Should seller get a group of question when no requirements were provided by buyer?
2. What questions should get seller in this case?

**Comment by Nikanoras** [comment]
@acolomer 
From your answer I understood that the CA can provide no requirement groups on the request side and on the response side EO will have to answer the criteria questions as there is one requirement group, am I correct? If so, what values should be in both of the requirements for Register name and URL? because they still will have to be present in the XML, in other case we won't be any connection to the TenderingCriterionResponse in the XML.

**Comment by hricolor** [comment]
Good afternoon, 
Many thanks again for your comments @jelenacaik and @nikanoras. 
 
About your questions, we have to comment on the following.
 
After analysing your comments we have detected that cardinalities for the requirements needed to be changed to 0..1 for both, criterion 27 and criterion 28 (Suitability). This way, if the Buyer does not include any requirement, there is no need to include information in the requirements and the economic operator will get the general question as is stated in the criterion. 
 
The changes are available in the specific branch [criterion-evolution](https://github.com/OP-TED/ESPD-EDM/tree/criterion-evolution/codelists). And will be released in the next minor release 3.1.0.
 
Kind Regards, 
The ESPD team
