### ISSUE TITLE
Average turnover

### ISSUE THREAD

**Issue by JelenaCaik** [OP-TED/ESPD-EDM#345]
Hello,

I would like to confirm requirements for Average yearly turnover AND for Specific average turnover.

1. **Average yearly turnover**, CA & EO:

- Taxonomy: Requirement has field "Number of fiscal years"
- Technical handboook has fields "Start date" and "End date".

Question: what should we show for CA and EO (number of fiscal years OR Start/End dates)?
![1_average_yearly_TO](https://user-images.githubusercontent.com/113527358/191281395-0cda8163-eb85-497c-b668-f2ddc67327cf.png)

______________________________________________________________________________________________________________________________________________

2.  **Specific average turnover**, EO

- Taxonomy: Requirement has field "Start date" and "End date" (row 26)
- Technical handboook has no such fields, just Average amount per last N years (in example, last 3 years)

Question: what should we show for EO (number of fiscal years OR Start/End dates)?
![2_specific_avergae_turnover](https://user-images.githubusercontent.com/113527358/191282408-f1c75b0c-300f-42d8-aa4a-014a10557e45.png)

**Comment by acolomer** [comment]
Good afternoon.
Thank you very much for your questions and comments, which we have analysed in detail.

**1. Regarding the average yearly turnover:**
 As it is represented in the mockups and stated in the data structure and the expected datatype, on the buyer side it is good to represent directly the amount as it is asking the general average of different years. That's why:

- The data structure has a 3 number of fiscal years; and

- The mock-up shows 3 years from start to end.

From the EO perspective, it includes the 3 years also as a range or period (3 years). And then, the EO needs to include the average for those 3 years.

**2. Regarding the specific yearly turnover:**
As indicated in the documentation (check the image below):
![image](https://user-images.githubusercontent.com/24680296/194553732-bbfe2590-c1de-472f-b6eb-e43b860d3a35.png)
This criterion asks for the recent past fiscal years. The Buyer establishes the period, which is shown as in the mock-up in the documentation (EO Perspective):
![image](https://user-images.githubusercontent.com/24680296/194553929-b1c24ef2-4f12-4bd3-ae64-6e1e5dae9bdb.png)
We hope this information is helpful. If it is not clear enough or you have further doubts, don't hesitate to share them with us.

Best regards,
The ESPD Team
