### ISSUE TITLE
Initial question for the EO to fulfil or not the criteria - critical for implementation

### ISSUE THREAD

**Issue by JelenaCaik** [OP-TED/ESPD-EDM#346]
Based on Taxonomy structure(Data structure) each requirement group has its own question "Does the EO fulfil the criteria by itself?" It seems not logical, as the question is about CRITERIA, not requirement.

Based on Mockup, you provide, this question should be asked ONCE before each criteria.

Please confirm how it should be implemented and update Taxonomy based on the rule.

![FulFil](https://user-images.githubusercontent.com/113527358/191534467-77a61020-3369-4555-981a-715b2ee484e4.png)

**Comment by acolomer** [comment]
Good morning,
Many thanks for your comment.
We have analysed in detail the your question.
This first question group was added in version 3.0.0 after the agreement with the OUC. The purpose of the group is to know if the Economic Operator relies on any other entity to fulfil the criteria and the requirements. It is useful to gather additional information from the EO.
The data structure allows for the ESPD Service to implement the question as it is represented in the mockup. Therefore, no additional modifications would be needed to implement ESPD services the way it is shown in the mockup.
Additionally, to add more granularity to our explanation, criteria are built with a requirement_group element (cac:TenderingCriterionPropertyGroup) and within it, all questions are nested. This does not mean that questions need to respond only to those requirements, because there are cases where the Buyer does not include any additional requirement to the questions from the criteria.
In consequence, there is not need to modify these data structures to extract this question group outside the requirement group, as all criteria include a requirement_group (cac:TenderingCriterionPropertyGroup) as the basis.
We hope this information is helpful to your implementation purpose.
Best regards,
The ESPD Team

**Comment by JelenaCaik** [comment]
Hello @acolomer ,
Thank you for your explanation.
I would like to confirm specific case for Criterion 55 - **Certificates by independent bodies about quality assurance standards**

* Buyer has added 3 Requirement groups:
 - _Requirement 1A_
 - _Requirement 2B_
 - _Requirement 3C_

* Then, Seller gets 3 groups of questions for:
 - _Requirement 1A_
 - _Requirement 2B_
 - _Requirement 3C_

Should we ask question "Does the EO fulfil the criteria by itself?" 3 times inside each requirement group?
Or should we ask question "Does the EO fulfil the criteria by itself?" only ONCE?

Best regards,
Jelena

**Comment by acolomer** [comment]
Good afternoon,
Thanks for your question and comments, which we have checked in detail.
1. We have detected that cardinality is missing for question subgroup "Does the EO fulfil the criteria....". This will be addressed in a future ESPD version and will be implemented in a specific branch.
2. Regarding the times the group should appear, the answer is 3 times, since the creation of a new requirement group implies that the whole structure is replicated. This way, the EO could state whether or not is going to fulfil any specific requirement.
Kind regards,
The ESPD Team

**Comment by acolomer** [comment]
Good morning,
We have implemented the necessary changes in cardinality from point 1. The correction is available in the [criterion-evolution branch](https://github.com/OP-TED/ESPD-EDM/tree/criterion-evolution) and will be released in ESPD v3.1.0, scheduled for the end of this year.
Kind regards,
The ESPD Team
