### ISSUE TITLE
SC Suitability: EO side. Question_subgroup: Your answer?

### ISSUE THREAD

**Issue by JelenaCaik** [OP-TED/ESPD-EDM#350]
Hello,

I would like to confirm if EO can add N time a block/ group of answers regarding "Your answer"? | "Registration number"? when answering to any of 4 criterias at Suitability criterion group?

![1_your_ANSWER](https://user-images.githubusercontent.com/113527358/197518408-749b7c9f-3a32-42b1-b016-6e417bf861a6.png)

Requirement group Cardinality is 1..n (let's say Buyer has added 2 occupations). The EO gets 2 groups of questions:
 - Does the EO fulfil the criteria itself?
 - Your answer?
 - Registration number?
 - Is this information available electronically?

And based on spreadsheet, seller can add N times answers to questions "Your answer" and "Registration number". Is that correct? What is the business logic/explanation here?

**Comment by acolomer** [comment]
Good morning,
Many thanks for your comment.
We have analysed your question in detail.
There is a mistake in the cardinalty of the question subgroup, which should be 1. 
Although it is possible to have several requirement groups within criteria within Suitability, prof-regist allowing here to define different occupations, we can have only one set of answers per requirement group meaning per occupation.
This will be fixed in a the next ESPD release (ESPD v3.1.0, scheduled for mid December).
Kind regards,
The ESPD Team

**Comment by ghost** [comment]
Good morning,
The changes are already done in the Excel criterion file and XML sample files for all the Suitability criterias (number 25, 26, 27 and 28), the cardinality is now set to 1. They are available in the specific branch [criterion-evolution](https://github.com/OP-TED/ESPD-EDM/tree/criterion-evolution/codelists) and will be released in the next minor release 3.1.0.

Kind Regards,
The ESPD Team.
