### ISSUE TITLE
Exclusion grounds (Part III, point C) and selection criteria (Part IV)

### ISSUE THREAD

**Issue by AJDAKOST** [OP-TED/ESPD-EDM#351]
Hello,

if we understand correctly, regarding Article 57(6) of the Directive 2014/24/EU, when the public procurement is divided into lots, for each exclusion grounds (Part III, point C) and for each selection criteria (whole Part IV) in the ESPD version V.3.X.X. will be possible to write a different request for each lot.

Best regards,

Ajda

**Comment by acolomer** [comment]
Good morning,
Many thanks for your comment.
We have analysed your question in detail.
In alignment with the Directive, in the ESPD Request selection criteria can include different requirements, which are specific constraints from the Buyer for specific lots within a procurement procedure. For example, for the turnover, the Buyer can specify a minimum amount or the number of years, which can be the same for or lots or different in each lot.
However, in the last major release (ESPD v3) which was released in April 2021, there was an alignment with eForms from both the business and technical perspective. This change caused that, although from a business point of view there are selection criteria that can implement different requirements per lot, the current technical implementation does not allow multiple and different requirement per lot, this is, all lots share the same requirements within a given criterion. 
This issue will be fixed in the next major release (ESPD v4.0.0), scheduled for the end of the first quarter of 2023.
This issue affects only selection criteria, since exclusion grounds are common to all lots and, therefore, for exclusion grounds there cannot be specific requirements per lot.
We hope this information is helpful.
Kind regards,
The ESPD Team
