### ISSUE TITLE
Questions regarding lots and group of lots concepts #interproc

### ISSUE THREAD

**Issue by konstantinosraptis91** [OP-TED/ESPD-EDM#353]
Hello ESPD team,

I got a question concerning the newly introduced "group of lots" concept. I understand that this comes from the alignment with eForms, but I am not sure what is allowed or not in the ESPD. For instance, is it possible to break a tendering procedure into 4 lots and 1 "group of lots", which includes lots 3 and 4, or are those concepts (lots and group of lots) mutually exclusive and cannot coexist in the same ESPD artefact? In my assumption, a selection criterion could look like this based on the scenario I mentioned before:

![Στιγμιότυπο 2022-11-14, 1 08 28 μμ](https://user-images.githubusercontent.com/15834471/201668537-e6903dd7-b84d-4883-933a-0aff30b934b1.png)

1. The representation of the 1st lot.
2. The 1st group of lots grouping lots 3 & 4.

Another issue I have found has to do with the 4-digit scheme that has to be followed. In the technical handbook, Figure 14 says that the scheme follows a 4-digit pattern combined with the relevant lot prefix (LOT- or GLO-). Still, every XML example in the technical handbook, including the example artefacts in the ESPD-EDM repository, seems to follow a 5-digit pattern. So, is the 4-digit pattern (scheme) mandatory, and which is correct? Figure 14 or the examples?

![Στιγμιότυπο 2022-11-14, 3 16 59 μμ](https://user-images.githubusercontent.com/15834471/201669848-a1688481-a619-48be-a9f5-79ffa6739b6a.png)

Additionally, from the examples, I understand that numbering starts from 0 regarding the lots / group of lots. Is this correct? I couldn't find where in the tech handbook this information is clarified.

**Comment by naerp** [comment]
To add to what Konstantinos mentioned already in the issue, while discussing the UI for the Group of Lots, we came to some additional doubts to the ones already stated, regarding Lots and Groups of Lots implementation, which we wanted to have feedback on how to implement it:
1) Are we supposed to keep evidence of which lots are inside each group of lot?
2) If yes on 1), does the GLO element allows us to store that information in the XML request? 
3) If no on 2), how can we store that information in the XML? (for instance, if ESPD service from company A opens an XML Request generated in ESPD service from company B, how will the service from company A know what lots are inside GLO-0001?) We found very little information regarding GLO object in the Technical Handbook.
4) If no to 1), how do we manage the number of each lot / group of lots, as the technical handbook talks about a consecutive numbering of lots / groups of lots?
Example: Procedure A has 5 lots, lots 1 and 2 are inside Group of Lots 1 and lots 4 and 5 are inside Group of Lots 2.
Should we have in the ESPD app LOT-0003, GLO-0001 and GLO-0002 or should we have LOT-0001, GLO-0001 and GLO-0002 (and, in this scenario, should we use the description to make LOT-0001 to match the real LOT 3 of the procedure)?
4) Should we keep only GLO-0001 and GLO-0002 or should we also have each of the individual LOT that are inside each GLO? (for instance, allow to associate a Selection Criterion just to one of the Lots inside the Group of Lot 1)

Thank you in advance for your clarifications, as we really need them to make sure we are implementing Lots and Groups of Lots as it is expected, but we don't find clear answers in the available documentation.

**Comment by pascalinelaur** [comment]
Hello @konstantinosraptis91, Hello @naerp, 


Thank you for your questions and the follow-up as well. 

The management of Lots has been studied and a former existing solution has been integrated to the UUID Issue proposals. 

The case of the mangement of Group of Lots has not been studied as stated in the documentation 
because the current solution allows to define several Lots (Requirement cardinality is multiple) 
in a given Requirement Group and that is already a way of defining a Group of Lots. 
Moreover, we can have several Requirement Group (Requirement Group cardinality is multiple) 
with several Lots inside and hence, several Group of Lots. 

However, the documentation allows to define either Lots (LOT-XXXX) or Group of Lots (GLO-XXXX), 
with 4 digits, starting at 0 and incrementing by one. 

The deletion or the integration of that notion of Group of Lots 
as a pre-defined entity (GLO-XXXX) is currently under discussion. 

The integration of the notion of Group of Lots (GLO-XXXX) 
as a pre-defined entity raise various issues that you described very well and we will need to address each of them. 

On the other hand, the final format of the LOT identifier has to be uniform,  
whether to use 4 or 5 digits. Then, the documentation or the XML samples will be updated accordingly. 

Lastly, how to start numbering the Lots or Group of Lots, from 0 or from 1? 
Is the default Lot called "Lot0" when there is no Lot in the procurement procedure?
This has to be clarified in the documentation and in the samples as well. The increment numbering will be by one. 


Kind regards, 
the ESPD team.

**Comment by acolomer** [comment]
Good morning,
This issue is pending discussion with the eForms Team.
We will keep you updated.
Kind regards,
The ESPD Team

**Comment by konstantinosraptis91** [comment]
Hello @pascalinelaur 

Any news regarding the clarification of the starting number in the LOT-XXXX and GLO-XXXX schemes? I haven't found anything considering this topic in the documentation. Is this still a pending issue?

**Comment by acolomer** [comment]
Good morning,
As mentioned, this issue is pending discussion with the eForms Team.
We will keep you updated.
Kind regards,
The ESPD Team

**Comment by dragos-eu** [comment]
Dear @konstantinosraptis91,

The requested changes were implemented in ESPD-EDM v3.3.0 and are documented in https://docs.ted.europa.eu/ESPD-EDM/latest/technical/tech_selection_criteria.html#_lot_management_approach_for_selection_criteria. 
We close the ticket.

Kind Regards,
ESPD Team
