### ISSUE TITLE
SC-References: performance of works / deliveries / services of the specified type

### ISSUE THREAD

**Issue by JelenaCaik** [OP-TED/ESPD-EDM#362]
Hello,

I would like to clarify the logic of criterion appearance and cardinality for _Selection Criteria_ >
* For works contracts: performance of works of the specified type
* For supply contracts: performance of deliveries of the specified type
* For service contracts: performance of services of the specified type

==============
**QUESTION 1:**
Based on XSD file Cardinality for Criteria question group is 1 ..n, for Reference is 1..n, (group in group),  so fields from row 21 to row 40 could be repeated N times. When we check all fields inside, we see all fields from row22 to row 33 are optional. And only EVidence (information online) is mandatory.
So it could be a case, when user leave all fields empty for criteria and only need to fill in Evidence information.
Is that really correct?

Or should we have at least any other mandatory field for Reference or Recipient?
![1_criteria_37](https://user-images.githubusercontent.com/113527358/204771952-f5cac96c-6d5b-4885-bd93-da03df077e78.png)

==============
**QUESTION 2:**
_Example:_ 
1. If buyer enters "Minimum number of reference" = 2:
a) should we repeat Reference sub group minimum 2 times for seller (without possibility to remove them, rows 21-40 | c8ec5c30-2c17-4936-abbb-392523d873e5)? 
b) OR should we repeat group row 19-41 | a44e24e9-f878-4651-9ead-e0b1387dae09 ?

2. Can EO adds a Reference group  (c8ec5c30-2c17-4936-abbb-392523d873e5) additionally more than minimum number of references?

3. Row 19, ElementUUID=a44e24e9-f878-4651-9ead-e0b1387dae09 has cardinality 1..n, when (in what case) we need to repeat this sub-group?

**Comment by JelenaCaik** [comment]
Hello, do you have any answer? It seems about 2 weeks we haven't got any reply.

**Comment by acolomer** [comment]
Good, afternoon,
Thank you very much for your comment.
Sorry for the delay, currently we are focused on the release. We will provide you an answer in the oncoming days.
Kind regards,
The ESPD Team

**Comment by pascalinelaur** [comment]
Hello @JelenaCaik, 


Thank you for your questions.

They have been analysed thouroughly and here is the first outcome.

For Question 1, the Question Subgroup (QSG) for "References" (at line 21) has cardinality "1..n" and all its children have cardidinality "0..1", except the evidence QSG. Then yes, it would be more natural to have the related QSG with the cardinality "0..n", if we apply the generalisation law. However, the cardinality of the QSG is not inconsistent per say, since it is most likely that at least one child value is going to be provided by the seller (Economic Operator EO) or that the seller might provide an evidence saying that he does not have any reference.

For Question 2 :

  -  If the buyer enters "Minimum number of reference" = 2, we should repeat the Reference subgroup (line 21) minimum 2 times for seller.
  - Yes, the EO can add more than the minimum number of references.
  - For Row 19, ElementUUID=a44e24e9-f878-4651-9ead-e0b1387dae09 has cardinality 1..n. We are currently checking in which cases, we will need to repeat this subgroup. Otherwise, its cardinality should be equal to 1.


Kind regards,
The ESPD Team.

**Comment by Nikanoras** [comment]
Hi,
Could you explain the general procedure how to identify the correlation between requirements and question groups/sub-group cardinality? Because at this point it becomes a custom case for each criteria, and to point requirement to specific question group you need to create an artificial connection, which is nowhere present. Also, from my understanding on Response side user is free to add or remove question groups, based on cardinality, but in such scenario there are some group cardinalities you can modify, and some not.

**Comment by Nikanoras** [comment]
Hey @pascalinelaur,
Any update on my previous question?

**Comment by acolomer** [comment]
Good morning,
We suggest to discuss this in the next OUC meeting scheduled for 26th January.
Kind regards,
The ESPD Team

**Comment by acolomer** [comment]
Good morning,
We suggest to discuss this in the next OUC meeting scheduled for 26th January at 10.00 ([https://ecconf.webex.com/ecconf/j.php?MTID=m9579200ced86da3e3f46fff7f67275ab](https://urldefense.com/v3/__https:/ecconf.webex.com/ecconf/j.php?MTID=m9579200ced86da3e3f46fff7f67275ab__;!!DOxrgLBm!C-TrRwefCqcV8H6gDwVtygnSOmksQ4rOjLCdnrzuME-edI0psWdKffcXIoKf9HYkWJ9FTQdjoHZ7L2CHbDAPyqPl7dGD$)).
Kind regards,
The ESPD Team

**Comment by acolomer** [comment]
Good morning,
As discussed during the last OUC meeting, held on 26 January 2023, the ESPD Team will review this issue in detail and provide a solution proposal in a future OUC meeting. This issue might not be included in ESPD-EDM v4.0.0.
Kind regards,
The ESPD Team

**Comment by dragos-eu** [comment]
Dear @Nikanoras,

In ESPD v3.3.0 we provided a fix in the way the elements are mapped from ESPD Request to ESPD Response. 
The solution based on XML Path like IDs is implemented in v4.0.0. which allows to uniquely identify the group or subgroup, the occurrence, and the order of responses  (to be released in the Q3 2024).
We recommend to consider upgrading to ESPD v4.0.0 or above.

Kind regards,
The ESPD Team
