### ISSUE TITLE
Alignment between ESPD-EDM v3.0.1 and eCertis regarding criterion 33

### ISSUE THREAD

**Issue by acolomer** [OP-TED/ESPD-EDM#363]
Criterion 33 “Set up of economic operator” has been removed from taxonomy in ESPD EDM but is still available in eCertis. 

When we generate the ESPD from eCertis we are getting this criteria although it is not supposed to be in the ESPD anymore.

**Comment by mc-ec** [comment]
The criterion "Set up  of an economic operator" can't be deleted, because it is still referenced from older versions. The referencing should be done through the scenarios in eCertis. All countries who mark this criterion as "not applicable" in their scenario, because they use v3 of the ESPD, should get this information/or not from eCertis. The same logic applies to the criterion "purely national exclusion grounds". In some countries there are no such criterion defined, this should be as well be marked by those countries as "not applicable".
I will close this issue. If there are further questions on this issue, please feel free to open it again.
