### ISSUE TITLE
Identifying properties in XML #interproc

### ISSUE THREAD

**Issue by Nikanoras** [OP-TED/ESPD-EDM#364]
Hello,
We are working on import of ESPD Response and found an issue. When importing there're two steps, first is structural (propertyGroups, properties), second are answers(TenderingCriterionResponses), based on the structure of ESPD both request and response. When going through the property group structure we try to match the property, if it's a property group then by id, if it's single property then by order (because no id's are present in ESPD 3). If we fail to find this property it means that this property is in a wrong place, is a custom field added by the user, etc. If we do not find this property group or property in taxonomy, we ignore it and continue to the next element. In that way we ensure that only relevant and real ESPD elements are imported. I tried to add custom property to ESPD Response XML and validate it. Validator did not return any kind of errors regarding that, it seem not to validate the specific structure of each criteria property groups. If we won't try to map taxonomy to ESPD XML, the imported information may brake the system or in future may lead to export of invalid XML.
So this brings the problem, is you have something optional, it means that in property group structure this element won't exist, and it won't have an answer, but the ordering of properties inside property group is based on taxonomy, where we count all mandatory and optional properties. So if one property is missing then this won't work, as indexes will shift for some properties.

e. g. You're importing ESPD Response and current criterion is work-tech. You're trying to map question group 52ffcf91-3598-438f-8c3d-faf97da02602 children to taxonomy, and some of them are not filled, because most on questions are 0..1. In this version of ESPD 3.x questions and requirements do not have an ID, so to find the same equivalent element in taxonomy we are currently using ordering. If some of the elements are missing, the ordering fail, because ordering of questions is created based on taxonomy elements both optional and mandatory.

Could you suggest how to map properties in XML to taxonomy?

**Comment by pascalinelaur** [comment]
Hello @Nikanoras , 

Thank you for your question. After an analysis, here is the outcome.
The Request is the ESPD is the common shared document for a procurement procedure. All Responses for a given procurement procedure should be aligned with its Request.
Hence, when defining IDs in the Request (UUID, numbering, etc.), the same ID should be re-used in the Response to keep the link with the Request somehow.
So, if a property (here a Question) is optional, it doesn't mean that in the Response the numbering of a set of properties should change because the EO is not filling some of them.
Everything that is in the Request should correspond to the "exact same thing" in the Response. For example, if in the Request for a given Question Subgroup there are Question 1, Question 2 and Question 3, then in the Response if Question 1 is missing, then there are going to have in the Response only Question 2 and Question 3. Question 2 should not become Question 1, nor Question 3 should become Question 2.
If you change the numbering of a Question in the Response, then yes obviously you would not be able to refer to the initial Question defined in the Request.
You can only create a new ID in the Response if and only if this ID doesn't exist already in the Request. Then, it means you are creating something new in the Response that is not in the initial Request and for that you need to provide a new ID for this new element.

If you don't have any further questions, we then close the issue. 

Kind regards,
The ESPD Team.

**Comment by Nikanoras** [comment]
You are describing the "happy path", when importing ESPD Response XML generated from the same ESPD Request. But what if the ESPD Response was created from different ESPD Request, the generated IDs for properties won't match, how then should we match?  @pascalinelaur

**Comment by pascalinelaur** [comment]
Hello @Nikanoras , 

Thanks for your follow up question. 

Normally, a procurement procedure is one Request and a set of related Responses. From one procedure to another, the Request structure may change. Hence, all Responses for different procurement procedures don't necessarily have to be aligned. 

Kind regards, 
The ESPD Team.
