### ISSUE TITLE
Criteria legislation ids unavailable in eCertis #interproc

### ISSUE THREAD

**Issue by aurimas-jankauskas** [OP-TED/ESPD-EDM#366]
If we make a request for criterion in eCertis, for example: https://ec.europa.eu/growth/tools-databases/ecertisrest/criteria/005eb9ed-1347-4ca3-bb29-9bc0db64e1ab

We can see legislations in the response. However, there is no id's specified for any of the legislations. Is this a bug in eCertis or we should look for legislation id's somewhere else?

P.S: We can see that the example XML in this repository (xml-examples/ESPDRequest.xml) does contain legislations with id's, but it's unclear where they come from.

**Comment by acolomer** [comment]
Good morning,
Thank you very much for you comment.
We understand this will be included in a future eCertis update. The work is foreseen to start in Q2 this year.
Kind regards,
The ESPD Team

**Comment by dragos-eu** [comment]
Hello @aurimas-jankauskas ,

The integration between ESPD and eCERTIS was completed in ESPD v3.3.0. The ESPD Service implementer will retrieve full information from eCERTIS and display it in the interface as per specific national laws and regulations. ESPD provides a generic placeholder for this sections. The ESPD Service will customize the model so that it will accommodate the mandatory fields.

Please let us know if you would like to have more details from our side.

Kind regards,
The ESPD Team
