### ISSUE TITLE
Missing legislation translations in eCertis #interproc

### ISSUE THREAD

**Issue by aurimas-jankauskas** [OP-TED/ESPD-EDM#367]
It seems that some criteria are missing translations for legislations, e.g: https://ec.europa.eu/growth/tools-databases/ecertisrest/criteria/005eb9ed-1347-4ca3-bb29-9bc0db64e1ab?lang=sv
![image](https://user-images.githubusercontent.com/100671859/208853835-478a45e0-3ea0-4a5d-89b8-52df73390c78.png)

**Comment by acolomer** [comment]
Good morning,
Thank you very much for you comment.
We understand this will be included in a future eCertis update. The work is foreseen to start in Q2 this year.
Kind regards,
The ESPD Team

**Comment by srdjankr** [comment]
Dear @aurimas-jankauskas,

The integration between ESPD and eCERTIS was completed in ESPD v3.3.0. The ESPD Service implementer will retrieve full information from eCERTIS and display it in the interface as per specific national laws and regulations. ESPD provides a generic placeholder for this sections. The ESPD Service will customize the model so that it will accommodate the mandatory fields.

Please let us know if you would like to have more details from our side.

Kind regards,
The ESPD Team
