### ISSUE TITLE
Lots are missing or were removed? #InterProc

### ISSUE THREAD

**Issue by daniel-sousa-lobo** [OP-TED/ESPD-EDM#370]
Hello!

We noticed that the section for Lots i version 3.1 in the Selection Criteria was removed from the EXCEL.
The Lots are no longer needed?

Any clarification is appreciated.

**Comment by acolomer** [comment]
Good afternoon,

Thank you very much for your comment.

As was presented in the 2022 ESPD Annual Seminar in November, the ESPD selection criteria include requirements, which are specific constraints from the Buyer for specific Lots within a procurement procedure. In the last major release of the ESPD (April 2021), the logic for the management of lots was aligned with eForms, from both the business and technical perspective. 

Recently, an issue has been identified in the usage of lots in ESPD-EDM v3, since from a business point of view there are selection criteria that can implement different requirements per lot but, from a technical point of view, the current technical implementation does not allow multiple and different requirement per lot.

With this logic, a requirement within a selection criterion is unique and, therefore, all lots that the criterion targets would have the same requirements, since there is no field / requirements within the requirement to establish the Lot targeted.

In the next ESPD-EDM release (v4.0.0) this issue will be solved and the structure will be as it was implemented in v2.1.1, with the inclusion of a field / requirement to specify LOTS where it applies, so requirements can be replicated (cardinality 1..n).

Therefore, Lots are still needed, and will be available again in the next release. This issue affects only ESPD-EDM v3.

Kind regards,
The ESPD Team

**Comment by naerp** [comment]
Hi @acolomer, thank you for your answer.
To be clear, since we are still implementing v3, what we should assume is:
1) It is still possible to define lots in the ESPD Request (v3).
2) All criterion defined in the ESPD Request, both Exclusion Grounds and Selection Criteria, apply to all lots defined.
3) It's not possible to have more than one instance of each Selection Criterion in the same ESPD Request.
Can you confirm this?
