### ISSUE TITLE
Clarification on Lots in v3 of ESPD-EDM #interproc

### ISSUE THREAD

**Issue by naerp** [OP-TED/ESPD-EDM#372]
Hello all,

Since issue https://github.com/OP-TED/ESPD-EDM/issues/370 was closed, I opened this issue, to make sure we get a reply to the additional clarifications I added to that issue.
What I wrote as a comment in the other issue:

To be clear, since we are still implementing v3, what we should assume is (for this specific version):

1 - It is still possible to define lots in the ESPD Request (v3).
2 - All criterion defined in the ESPD Request, both Exclusion Grounds and Selection Criteria, apply to all lots defined.
3 - It's not possible to have more than one instance of each Selection Criterion in the same ESPD Request.

Can you confirm this?

**Comment by acolomer** [comment]
Good morning,
Thank you for your comments.
Regarding youe questions:
1.	Yes, it is possible to define lots in ESPD Request v3 (using cac:ProcurementProjectLotReference) but they will all be assigned to the same set of Requirements defined in the related selection criteria.
2.	Exclusion Grounds is applied to all lots. In selection criteria, a set of lots can be defined.
3.	We should not have more than one instance of each criterion although the file will validate with the ESPD Validator since it is not a written rule but it should be.
We hope this information if useful. We will discuss this in the next Open User Community to ensure that is clearly understood.
Kind regards,
The ESPD Team
