### ISSUE TITLE
Question regarding the additional EO information mandatoriness (OTHER-EO) #interproc

### ISSUE THREAD

**Issue by konstantinosraptis91** [OP-TED/ESPD-EDM#373]
Hello ESPD team,

I was searching the technical handbook regarding the additional Economic Operator information, also known as OTHER-EO "Criteria" cardinalities, and I couldn't find something relevant. Could you please clarify if those are mandatory and MUST be included in the ESPD Request and Response or, as their name states, those are considered additional information; therefore, they are optional. 

In the ESPD-Criterion.xlsx (former Criteria Taxonomy excel sheet), the OTHER-EO criteria are the following ones:
**shelt-worksh, registered, eo-group, relied, subco-ent, staff-red, sme**

**Comment by acolomer** [comment]
Good afternoon,
Thank you very much for your comments.
It is correct that cardinalities are not provided in the technical handbook since they are available in the criterion excel file.
Regarding additional Economic Operator information (OTHER-EO), all these criteria have an initial mandatory question which is a boolean (YES / NO) and, in some cases, depending on this initial answer, there are further questions that can be mandatory 
 (conditional mandatory) as reflected in the criterion excel file.
Please let us know if this explanation is not clear enough, so we can discuss it in the next Open User Community meeting, scheduled for the 23rd of February.
Kind regards,
The ESPD Team

**Comment by konstantinosraptis91** [comment]
Thank you for your answer @acolomer. Maybe my question wasn't very clear. I was asking if the OTHER-EO "Criteria" are mandatory or not and must be included in the ESPD artifacts. My question wasn't about the internal structure and the respective cardinalities of the OTHER-EO "Criteria".

**Comment by acolomer** [comment]
Good afternoon,
It must be taken into account that this Economic Operator additional information (OTHER-EO) are not actual criteria, since are qustions included in Part II (Information concerning the economic operator) of the ESPD. Therefore, these questions have to be included in the ESPD Response so the Economic Operator can provide the necessary information, and do not have to be included in the ESPD Request, which is filled in byt the contracting authority and does not contain the aforementioned Part II (Information concerning the economic operator).
Please let us know if this is not clear enough and further information is needed.
Kind regards,
The ESPD Team

**Comment by konstantinosraptis91** [comment]
Thank you for your quick response. Yes, those are "Criteria" only at the syntax binding level. Does the wording "have to be included" mean "MUST be included" (in the ESPD Response, of course)?

**Comment by acolomer** [comment]
Good morning,
Yes, Economic Operator additional information (OTHER-EO) must be included in the ESPD Response as is stated in the [ESPD regulation](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:32016R0007&from=EN).
Kind regards,
The ESPD Team
