### ISSUE TITLE
Clarification on date and time format #interproc

### ISSUE THREAD

**Issue by naerp** [OP-TED/ESPD-EDM#378]
Hello all.
We were looking into the tech handbook and saw this info, regarding the format for time and date.
(https://user-images.githubusercontent.com/38315856/214353586-50ee6e89-2385-4e53-8180-5b813642f381.png)
You mention that date should be in format yyyy-dd-mm (2023-01-24, as an example) and time should be in format hh:mm:ss (16:41:23, as an example).
Nevertheless, when we look at the example artifacts available in the ESPD-EDM, we find this:
<cbc:IssueDate>2022-11-24+01:00</cbc:IssueDate>
<cbc:IssueTime>16:44:18.554+01:00</cbc:IssueTime>
It seems you are including the timezone offset to UTC in both date and time and also including milliseconds in the time.
If you try and use the example artifacts in the Interproc validator (which we built according with the rules defined of the tech handbook), we will get a warning, regarding date and time fields.
Which one should we consider as correct, the tech handbook specification or the example artifacts?
Can you fix the one that is not correct and let us know?
Thank you.

**Comment by ghost** [comment]
Good afternoon,

thank you for your comments. Regarding your questions:

- The date and time formats including the timezone offset to UTC in the XML examples are correct. However, the miliseconds is an error that has been already fixed in the master branch and it´s included in the upcoming new release 3.2.0 which is about to be published.
- The regular format of date and time described in technical documentation are also correct, but we will include a clarification note about the timezone offset to UTC.

Kind Regards,
The ESPD Team.
