### ISSUE TITLE
Subcontractors not relied upon have to provide information about Selection Criteria

### ISSUE THREAD

**Issue by lschoonjans** [OP-TED/ESPD-EDM#381]
Hello ESPD team,

GROW had a workshop with Slovenia about eProcurement. Following the legislation, entities not relied upon (subcontractors) do not need to fill in the Selection Criteria. However, following the ESPD model the Selection Criteria must be filled in also for the entities not relied upon (subcontractors).

Could you please propose changes to the model as to be aligned with the legislation?

Thank you in advance,

Best regards,

Laurent

**Comment by pascalinelaur** [comment]
Hello @lschoonjans, 

Thank you for your question. We are cyurrently analysing it and we will come back to you as soon we have a proposal. 

Kind regards, 
The ESPD Team.

**Comment by dragos-eu** [comment]
Hello @lschoonjans ,

Following the direct discussion that we had with Slovenia on 15.02.2024. We agreed that the way forward is to move to either ESPD v3.3.0 or to ESPD v4.0.0. Both versions support accepted solution.

The Code List _EORoleType.gc_ have been modified from v2.X to v3.x so that the Subcontractor has been introduced while Other entity (relied upon) was deleted. This is in line with the directive and each CA may request or not the EO to provide separate information in the form of ESPD Response, according to the MS specific regulation.

Kind regards,
The ESPD Team

**Comment by dragos-eu** [comment]
Since there are any further comments, we proceed to close this issue.
