### ISSUE TITLE
Incomplete ESPD example artifacts description in criterion 23 (misinterpr) #interproc

### ISSUE THREAD

**Issue by konstantinosraptis91** [OP-TED/ESPD-EDM#382]
Hello ESPD team,

I am not sure if this has been reported before, but the included example artifacts in the ESPD-EDM repository don't have the whole description text in criterion 23 (misinterpr). I think this issue might be connected to multi-cbc:Description element option for larger descriptions. Nevertheless, I would like to confirm that this multiple cbc:Description element behavior is a recommendation and not a mandatory rule.

![Στιγμιότυπο οθόνης 2023-04-04, 7 19 30 μμ](https://user-images.githubusercontent.com/15834471/229855009-83a0ff94-ed79-40bf-96a0-5732b8aa0f67.png)
_ESPD Request v3.1.0 example artifact_

<img width="885" alt="Στιγμιότυπο οθόνης 2023-04-04, 7 30 29 μμ" src="https://user-images.githubusercontent.com/15834471/229857469-82b8aea3-0fdd-42f5-9bae-206f0d085ae3.png">
_Criterion 23 (misinterpr) in ESPD-criterion-v3.1.0.xlsx_

**Comment by pascalinelaur** [comment]
Hello @konstantinosraptis91 , 

Thank you for your question. Indeed, the multiple cbc:Description is a recommendation. 

In the sample, there is a reading-xml-generation error since none of the Additional_Description_Line are read to be appended to the "cbc:description" element, as to have the full description information. 

This issue had already been identified and will be solved in a future release. 

Kind regards, 
The ESPD Team.

**Comment by dragos-eu** [comment]
Dear @konstantinosraptis91,

Since there are no further comments we proceed to close this issue.

Kind regards,
The ESPD Team
