### ISSUE TITLE
General question in regard of interoperability of ESPD Response #interproc

### ISSUE THREAD

**Issue by Nikanoras** [OP-TED/ESPD-EDM#385]
Hi,

I have a question regarding interoperability of ESPD Response, when trying to reuse on different ESPD Request.

Let's take for example 1 criterion, "prof-regist".

We have a requirement of type CODE, with code list occupation. So let's say we created a ESPD Request with 2 requirement groups, and provided value "0110.11" navy officer and "0110.10" lieutenant. Now we want to reuse ESPD Response, so we import it. And let's say our ESPD Response XML contains answers for groups "0110.11" navy officer and "3312.6" mortgage loan underwriter. Let's say we are importing the ESPD Response for previously defined ESPD Request, we will try to fill in values, based on requirements. As we understand we will only import data for the questions in requirement group where is requirement "0110.11" navy officer, because it's contained inside ESPD Response XML. Do we understand correctly how the import of ESPD Response XML works?

Best regards,
Nikanoras

**Comment by pascalinelaur** [comment]
Hello @Nikanoras,

Thank you for your question. Actually, it is raising a very discussed issue here in the ESPD project related to the re-usability of data across procedures or across lots. 

Indeed, when we want to re-use data in the above context, we might encounter mismatch due to different or incompatible requirements.

Hence, your understanding is correct, you should only import data when the requirement is the same or when the requirement is evaluated (with a rule) as being compatible. Moreover, even if the user is re-using existing values, he should still have the ability to update them, because data can evolve in time. Actually, information are imported as a potential answer in a given procedure.

So, regarding your example, the user can import values related to the requirement group for the occupation "navy officer" and he should be able to update them as well afterwards.  For the requirement group related to the occupation "mortgage loan underwriter", the user will have to fill in all the values manually.

Kind regards,
The ESPD Team

**Comment by Nikanoras** [comment]
Hello @pascalinelaur ,

Thank you for the clarification. It indeed get tricky then.

Let's take for example **authorisation** criterion. How do we map between ESPD Response XML to ESPD Request? In case of **prof-regist** we have a fixed value from a codelist, which we can match against. In **authorisation** criterion we have a DESCRIPTION and URL, it's basically a free text. How do we match by these requirements? If we match by value, should we match by both fields? 

Kind regards,
Nikanoras

**Comment by pascalinelaur** [comment]
Hello @Nikanoras,

Thank you again for your follow up question.

Indeed, the mapping process is tightly linked to the datatype of the criterion descriptive element (requirement, question). Hence, a mapping method should be defined accordingly.

For instance, when it is a code, a url (address) or a numeric value type one should perform a boolean mapping (exact value mapping) with a result value being either 0 or 1. In other cases, one should compute a degree of similarity with a result value normalized and being any number between 0 and 1 by using a given threshold to select a value as being similar or not. Also, this should be defined in more details by the ESPD service.

Kind regards,
The ESPD Team.

**Comment by pascalinelaur** [comment]
As we have no further comments, we proceed to close this issue.
