### ISSUE TITLE
Other economic or financial requirements

### ISSUE THREAD

**Issue by AJDAKOST** [OP-TED/ESPD-EDM#388]
Hello,
what CA and EO should enter in Part IV (Selection criteria), Other economic or financial requirements in the field of minimum amount (if the answer is "Yes" for the question "Select the periods applicable for all ratios") or minimum rating (if the answer is "No" for the question "Select the periods applicable for all ratios"), if CA only wants to specify a descriptive requirement in this field and does not require an amount or rating.

Thank you.

Best regards,
Ajda

**Comment by pascalinelaur** [comment]
Hello @AJDAKOST , 

Thank you very much for your question. 
Could you please provide us with a screen related to your question? 

KR, 
The ESPD Team.

**Comment by AJDAKOST** [comment]
Hello,

As an example, CA requires from EO to attach a credit rating (a document) to meet this criterion. What CA and EO should enter in this fields (minimum amount)?

View of CA

***@***.***


View of EO

***@***.***

Thank you.

Best regards,

Ajda

**Comment by arillpa** [comment]
Dear Ajda,

we cannot see the CA neither the EO views that you mention above. Could you please chech on your side if the screenshot is properly displayed?
We only see '***@***.***'

Maybe we could also discuss during the OUC meeting on 29 June this GitHub issue.

Kind regards
The ESPD Team

**Comment by AJDAKOST** [comment]
[Other economic or financial requirements.docx](https://github.com/OP-TED/ESPD-EDM/files/11745579/Other.economic.or.financial.requirements.docx)

Hello,

I hope you can see views now.

Best regards,

Ajda

**Comment by AJDAKOST** [comment]
Dear ESPD team,

I will not be able to attend the ESPD meeting tomorrow due to another meeting. 

Best regards,

Ajda

**Comment by mc-ec** [comment]
Dear Ajda,

If I understand your request, you would prefer next to "economic or financial requirement" and "rating requirement" a third option to allow only a description. 

We documented the discussion we had with the ESPD group back then here https://github.com/OP-TED/ESPD-EDM/issues/14 on this criterion. It was not the easiest criterion that we have discussed.

Having a third option would be okay in my view. Nevertheless, It would be good to know how this criterion is used in practice.

Best MC

**Comment by AJDAKOST** [comment]
Dear MC,

thank you for the answer. The third option would be fine by us. 

Our example: CA requires from EO not to have blocked transaction accounts or to have a certain company's credit rating. EO must fulfil this field and maybe even submit a document to meet this criterion (for non-blocked transaction accounts-the answer “Yes or No”, for the company's credit rating EO must fulfil the field with the words for example SB5). 

Best regards,

Ajda

**Comment by mc-ec** [comment]
Dear Ajda,

Many thanks for your feedback. I would suggest to discuss this for version 4 (next year) as we should discuss together with the OUC on how to implement it.

Best MC

**Comment by dragos-eu** [comment]
Dear @AJDAKOST ,

Thank you for your time.
As agreed, we will proceed with the following solution:

![image](https://github.com/OP-TED/ESPD-EDM/assets/152891717/664c99f3-fc40-414b-abc9-b8e18ade18e0)

- The top level questions will allow to choose between Economic and financial requirements / Rating or Descriptive requirement
- Adding a new section to capture the Descriptive requirement with a similar behavior as Rating requirement

Best regards,
The ESPD Team

**Comment by AJDAKOST** [comment]
Dear ESPD Team,

thank you very much for proposed solution. 

Best regards,

Ajda

**Comment by pascalinelaur** [comment]
Hello @AJDAKOST , 

For this issue, we decided to go for a new solution, because the purpose of radio buttons is to group things not to split them.  

The new solution was found after investigating a bit further.

There are 2 possible solutions :

1. We can use radio buttons to group all the options. That is the purpose of radio buttons. Hence, it doesn't make sense to have subgroup of radio buttons for the same thing.

2. We can use "yes" and "no" answer to question, to split all the options, meaning we have an INDICATOR type. Each Indicator represent a given option. The option/question has to be formulated clearly enough as to not lose the user and give him at the same time insight about the following questions. In general, we should avoid to go further than 3 (sub-)levels.

**The first solution that will include all the options in a single set of radio button is the one that we will implement as to keep the initial choice of our criterion file and for more clarity.**

Solution 1 is described below in our data structure for criterion C36_SC_finan-requ. This solution will be implemented in a future release. 

![C36_3options_sc_other_eo_fin_rq](https://github.com/OP-TED/ESPD-EDM/assets/102807568/ea570a72-fce9-46a6-922c-540a4fecf4a3)

![C36_3options_sc_other_eo_fin_rq_next](https://github.com/OP-TED/ESPD-EDM/assets/102807568/ec7edc49-4f82-4874-8fd0-7974ba577e8d)

**Comment by pascalinelaur** [comment]
Since the solution is provided and there are any further comments, we proceed to close this issue.
