### ISSUE TITLE
Pre qualification systems and classification of EOs

### ISSUE THREAD

**Issue by AJDAKOST** [OP-TED/ESPD-EDM#389]
Hello,
Please can you explain what to choose in this part in case national legislation does not have a pre qualification system. Particular in the case of the question "Will the economic operator be able to provide a certificate relating to the payment of social security contributions and taxes or to provide information that will allow the contracting authority or contracting entity to obtain it directly by accessing a national database in any Member State which is available free of charge?"?

Thank you.

Best regards,
Ajda

**Comment by pascalinelaur** [comment]
Hello @AJDAKOST , 

Thank you very much for your question. 
Could you please provide us with a screen related to your question? 

KR, 
The ESPD Team.

**Comment by AJDAKOST** [comment]
Hello,

If the EO selects »No« for the question »If applicable, is the economic operator registered on an official list approved economic operators or does it have an equivalent certificate (e.g. under a national (pre)qualification system?«, in ESPD-CriteriaTaxonomy-EXTENDED-V2.1.1 he must answer the question "Will the economic operator be able to provide a certificate relating to the payment of social security contributions and taxes or to provide information that will allow the contracting authority or contracting entity to obtain it directly by accessing a national database in any Member State which is available free of charge?"? Will this be the same in the V3.2.0? What we can do in case our national legislation does not have a (pre)qualification system? How EOs should answer this question?

Thank you.

Best regards,

Ajda
***@***.***

**Comment by mc-ec** [comment]
Dear Ajda,

I just looked in the Regulation itself https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX%3A32016R0007 and I realise that we have probably an error in the ESPD EDM. The Regulation describes it as it is behaving no. If yes, A to D has to be answered if no E. So in both cases something has to be answered. But the Regulation allows also to select not applicable, which is not the case in the ESPD EDM, here we distinguish only between yes and no.

Having that said, this field created a lot of confusion from the usage because EOs are often not aware if this does exist or not. So they might fill something in which is not correct. Maybe we can discuss on how to treat this field in the future. An idea would be that in eCertis we would allow MS to indicate if a country has qualification services (and which). So to show it only, if the country of the EO has such qualification service in place.

Best MC

**Comment by AJDAKOST** [comment]
Dear MC,

thank you for the answer. We agree with proposed solution.

Best regards,
Ajda

**Comment by mc-ec** [comment]
Dear Ajda,

Many thanks for your feedback. I would suggest to discuss this for version 4 (next year). The adjustment would introduce a new code list for the ESPD (yes/no/na). To do this properly, we should discuss together within the OUC.

Best MC

**Comment by dragos-eu** [comment]
Dear @AJDAKOST ,

Thank you for your time today and valuable input.
As we agreed, we will proceed with the following solution:

![image](https://github.com/OP-TED/ESPD-EDM/assets/152891717/ff9680de-8542-4151-9fbe-7564409f0687)

- Split the initial question in 2 parts: one about the MS having or not a (pre)qualification system and in case of positive answer the question about the EO being registered or not in such a system. The former will contain the exact questions as the existing implementation.
- If the MS does not have a (pre)qualification system then the EO has no further information to provide

Best regards,
The ESPD Team

**Comment by AJDAKOST** [comment]
Dear ESPD Team,

thank you very much for proposed solution. 

Best regards,

Ajda

**Comment by pascalinelaur** [comment]
Hello @AJDAKOST , 

Please find below the data structure of the updates related to criterion C58_SC_registered about Pre-Qualification Systems. The updates will appear in a future release. 

![C58_SC_registered_PQS](https://github.com/OP-TED/ESPD-EDM/assets/102807568/70e52471-1db0-4ac1-8d75-88ee19a0bb16)

**Comment by pascalinelaur** [comment]
Since the solution is provided and there are any further comments, we proceed to close this issue.
