### ISSUE TITLE
PERCENTAGE Questions: Artifact Examples and Shematrons Inconsistency #interproc

### ISSUE THREAD

**Issue by konstantinosraptis91** [OP-TED/ESPD-EDM#390]
Hi ESPD team,

I think I detected an inconsistency in the example artifacts and also in the Schematron rules. Specifically, QUESTIONs of PERCENTAGE valueDataTypeCode are expected to have a "cac:TenderingCriterionResponse / cac:ResponseValue / cbc:ResponseQuanity" instead of a  "cac:TenderingCriterionResponse / cac:ResponseValue / cbc:ResponseNumeric". In the technical handbook, there is a reference in Table 94 that claims that QUESTIONs of PERCENTAGE ValueDataTypeCode are being mapped to a "/cac:TenderingCriterionResponse /cac:ResponseValue / cbc:ResponseNumeric" as you can see in the snippet below.

![image](https://github.com/OP-TED/ESPD-EDM/assets/15834471/1f695ac6-fca2-4e08-b21d-78e12abfe47e)

Additionally, the relevant example table (Table 43) shows that cbc:ResponseNumeric is the element that has to be used for PERCENTAGE QUESTIONs mapping:

![image](https://github.com/OP-TED/ESPD-EDM/assets/15834471/ab9986ad-40c0-4ced-9a30-0f036afff537)

Kind regards,
Konstantinos

**Comment by pascalinelaur** [comment]
Hello @konstantinosraptis91 ,


Thank you very much for your question.

After analysis:

In the Online documentation, the table 94 states that for the datatype "Percentatge" we should have a "cac:ResponseValue/cbc:ResponseNumeric".  ​

Also, in the UBL documentation, a "ResponseNumeric" is used for a number, rate or percent as a reply to the criterion requirement. ​

Therefore, for "Percentage" datatype, we should change "ResponseQuantity" to "ResponseNumeric" ​in the related XSLT files.

We didn't encounter any validation error related to this datatype "Percentage", so we should also add a validation rule for the "Percentage" case, so that the constraint is properly validated.

​This change will be done in the next release.

 
Kind regards,
The ESPD Team.

**Comment by konstantinosraptis91** [comment]
Hi @pascalinelaur 

We encountered a validation error by using the ITB validator that suggests we must use a ResponseQuantity instead of a ResponseNumeric for a PERCENTAGE response. By reading your answer, it's not very clear that you will also update the improper current Schematron rule. I don't know if updating the related XSLTs will also update/impact the inconsistent current Schematron rule.

Kind regards,
Konstantinos

**Comment by pascalinelaur** [comment]
Hello @konstantinosraptis91,

Thank you for your follow up question. 

We will check the schematron rules.

There are 2 cases: either a rule exist and is using incorrect values in which case we will correct it, or the rule doesn't exist and we will have to add one.

Kind regards, 
The ESPD Team

**Comment by pascalinelaur** [comment]
Since we don't have any further comments, we proceed to close this issue.
