### ISSUE TITLE
Foreseen implementation of General Yearly Turnover Selection Criteria in ESPD-EDM version 3.3.0

### ISSUE THREAD

**Issue by andreea-pasare** [OP-TED/ESPD-EDM#402]
The use cases need to be made clear. The minimum requirement has a cardinality of 1..n but it is not clear how this should be used.

1. How are the multiple minimum requirements to be implemented? 
2. Would it be logical that the requirements would be associated to given years?
3. Is it implicit that the first minimum requirement is year 1 and the second year two and so forth?

More detailes on the ePO Working Group Meeting [minutes](https://docs.ted.europa.eu/epo-wgm/notes/2023-09-26-wgm.html).

Related to #44.

**Comment by pascalinelaur** [comment]
Hello @andreea-pasare, 

Thank you for your question. 

This issue is related to the criterion C29 SC gen-year-to (general yearly turnover).

The number of fiscal years defines year 1, year 2 and so on. 

When the EO answers to the related QSG (period, amount) that is of multiple cardinality, the number of occurrences of this QSG is the number of fiscal years. In this QSG, the EO provides the start and end date (period) of each fiscal year that is automatically bound to year 1, year 2 and so on, with respect to the related minimum amount requirement for the corresponding amount field, where the requirement is previously defined by the Buyer. **The order of questions in this QSG has to be inverted following the criterion C32 SC spec-year-to as to provide the period before the amount. This update will appear in the next release.**

The following mock-ups screenshots might help to clarify doubts. 

When the threshold requirement box is not checked, the same minimum requirement amount is applied for all the fiscal years. 

![threshold_not_checked](https://github.com/OP-TED/ESPD-EDM/assets/102807568/564a9d79-cd2a-42c2-b11f-68a44e24ea20)

When the threshold requirement box is checked, a different minimum requirement amount is applied for each fiscal year. 

![threshold_checked](https://github.com/OP-TED/ESPD-EDM/assets/102807568/f7bf6039-6b5f-44cd-8c79-32db3cdefc2e)

In the EO view, when the threshold has been checked, the EO has a view of the various requirements amount for each year and hence can fill in properly the related QSG. 

![threshold_checked_eo_view](https://github.com/OP-TED/ESPD-EDM/assets/102807568/8e702f50-5ed6-4b70-960b-e942b8deca36)


See also the online documentation : https://docs.ted.europa.eu/ESPD-EDM/3.0.1/xml_technical_handbook.html#_turnovers


Kind regards,

The ESPD Team.

**Comment by pascalinelaur** [comment]
Since we don't have any further comments, we proceed to close this github issue.
