### ISSUE TITLE
UBL term: cbc:CopyIndicator. A contradiction between the two definitions

### ISSUE THREAD

**Issue by AchillesDougalis** [OP-TED/ESPD-EDM#408]
In the Working Group meeting about Collecting eSubmission requirements for ePO on 16/1/2024, while going through UBL terms from [ESPD-EDM Response Technical Overview](https://docs.ted.europa.eu/ESPD-EDM/latest/_attachments/ESPD_CM_html/index.html) , it was discovered that there was a contradiction between the two definitions of the UBL term: cbc:CopyIndicator,  and was agreed that the ESPD-EDM team would check further.

**Comment by pascalinelaur** [comment]
Hello @MummiaDoug , 

Thank you for your question. 

In the ESPD documentation, the CopyIndicator is used in combination with the UUID of the document (Response or Request). 

In order to link the original document to its copies, all documents should have the same UUID. The CopyIndicator for the original is 0 and the CopyIndicator for the various copies is 1. 

Hence, the ESPD documentation has to be updated accordingly in various artefacts : online documentation, conceptual model. 

The updates will appear in the next release. 

Kind regards, 
The ESPD Team.

**Comment by andreea-pasare** [comment]
Definition from ESPD Response TOV:
![image](https://github.com/OP-TED/ESPD-EDM/assets/88081600/99f6992d-a084-4bd0-b728-5a630a10f57f)

Definition from ESPD Response BOV:
![image](https://github.com/OP-TED/ESPD-EDM/assets/88081600/8b3b673e-729e-489d-9e93-24773e9ec880)

This ticket can be closed. Thanks!

**Comment by pascalinelaur** [comment]
Since we don't have any further comments, we proceed to close this github issue.

**Comment by dragos-eu** [comment]
Hello @AchillesDougalis ,

The definition is now consistent in our documentation, and it reads:

> **cbc:CopyIndicator**
> Indicates whether this document is a copy (true) or not (false).
> ESPD definition: this component enables to keep track of the event of having forwarded the same document several times to the same or to different destinations.
> Additional comments: copies of an ESPD document should be identified with same UUIDs.

The changes are in our ESPD EDM - https://docs.ted.europa.eu/ESPD-EDM/latest/_attachments/ESPD_CM_html/index.html, and online documentation V3.3.0 - https://docs.ted.europa.eu/ESPD-EDM/latest/xml_technical_handbook.html.

Best regards,
The ESPD Team
