### ISSUE TITLE
power of Attorney

### ISSUE THREAD

**Issue by AchillesDougalis** [OP-TED/ESPD-EDM#410]
Regarding the discussion of the  WG meeting in 24/1/2024, we would like to know if there is a conflation between the concept of a person and PowerOfAttorney document.

**Comment by dragos-eu** [comment]
Hello @AchillesDougalis ,

Thank you for the message.
We are investigating this aspect and will be back to you with more information on the status of the topic.

Best regards,
ESPD Team

**Comment by dragos-eu** [comment]
Hello @AchillesDougalis ,

As we agreed on the Work Group meeting, in ESPD we have the Person that is modeled by Power of Attorney and in ePO the concept is broader: "Relation indicating that a Legal Representative has a Power of Attorney. WG approval 12/03/2024".

Starting with v4.0.0 ESPD will be aligned with ePO v4.1.0 and beyond.

Since we reached an agreement, we will close the ticket.

Kind regards,
ESPD Team
