### ISSUE TITLE
General and Specific Turnover

### ISSUE THREAD

**Issue by rgannu** [OP-TED/ESPD-EDM#415]
Related to [402](https://github.com/OP-TED/ESPD-EDM/issues/402)

In the [ESPD-criterion.xlsx](https://github.com/OP-TED/ESPD-EDM/blob/v3.3.0/codelists/ESPD-criterion.xlsx) for V3.3.0, the selection criteria for General (Yearly & Average) & Specific (Yearly & Average) specifies that "The CA defines three minimum amounts". 

1. There is no period associated with the requirement? How the EO will know which "minimum requirement" is applicable for which year?
2. The "minimum requirement" is of type AMOUNT but the cardinality is not 1..n in all the criteria (General (Yearly & Average) & Specific (Yearly & Average)). Why?

**Comment by dragos-eu** [comment]
Hello @rgannu ,

Thank you for your feedback.
We are analyzing your request and we will be back to you with an answer.

Kind regards,
The ESPD Team

**Comment by dragos-eu** [comment]
Hello [@rgannu](https://github.com/rgannu) ,

Thank you for your questions.

**For your question 1a) and b):**

As mentioned in previous answers in [Issue #402 · OP-TED/ESPD-EDM (github.com) ](https://github.com/OP-TED/ESPD-EDM/issues/402)and [Issue #44 · OP-TED/ESPD-EDM (github.com)](https://github.com/OP-TED/ESPD-EDM/issues/44) we can summarize the main response as follows:

This issue is related to the criteria C29 SC gen-year-to (general yearly turnover) and C32 SC sped-year-to (specific yearly turnover).

The number of fiscal years defines year 1, year 2 and so on.

When the EO answers to the related QSG (period, amount) that is of multiple cardinality, the number of occurrences of this QSG is the number of fiscal years. In this QSG, the EO provides the start and end date (period) of each fiscal year that is automatically bound to year 1, year 2 and so on, with respect to the related minimum amount requirement for the corresponding amount field, where the requirement is previously defined by the Buyer.

See also the online documentation [Section 5.4 - Turnover]: [The European Single Procurement Document :: TED Developer Documentation (europa.eu)](https://docs.ted.europa.eu/ESPD-EDM/latest/xml_technical_handbook.html#_turnovers)



**For question 2:**

Each turnover criterion is different. For criterion C29 General-yearly-turnover it is a general turnover for a given number of fiscal years where the Buyer can specify a threshold per year, meaning it is possible to have a different minimum requirement amount for each fiscal years. Hence the minimum required amount is of multiple cardinality.

For C32 Specific-yearly-turnover the minimum required amount is of single cardinality because there is no threshold provided. Hence is the same minimum for all fiscal years.

Let us know if further information is needed.

Kind regards,
The ESPD Team

**Comment by dragos-eu** [comment]
Dear @rgannu ,

Since there are no further comments we proceed to close this issue.

Kind regards,
The ESPD Team
