### ISSUE TITLE
Criterion dependencies (Lots)

### ISSUE THREAD

**Issue by arocamop** [OP-TED/ESPD-EDM#55]
**Story**: As a CA I need to differentiate whether a Criterion has to be applied or not to specific aspects of a Procurement Project (PP). Thus one selection Criterion may apply to one Lot but may have not sense for a different Lot of the same PP. Similarly, selection criteria that apply to a specific Economic Operator do not apply necessarily to subcontractors. Exclusion Criteria MUST apply to all Lots and roles of EO.

**Problem description**: 
1) In the case of Lots, the current ESPD Model caters for the definition of multiple Lots, and multiple Criteria. However the ESPD Model does not provide a method to link one Criterion to one or more Lots.
2) In the case of Economic Operators, this is not a problem as the decision was made to produce one ESPD document per EO (or subcontractor).

**Solutions**:

A) DO NOTHING: One solution could be having one ESPD per Lot. For example, in the case of a PP with 3 Lots and 2 EOs this would end up in 6 ESPD documents. **If adopted, this solution does not entail any change upon the current ESPD Model.**

B) MODIFY THE MODEL: A different solution would be to modify the current model to allow for the definition and linking of n Lots to m criteria (or viceversa) in one single ESPD document.

The following Data Models present: (i) the current situation; (ii) how to group and link Lots and Criteria under an e-Procurement-specific Criterion class and (iii) how to aggregate Lots to criteria. 

The reason to have an e-Procurement-specific Criterion would be justified in respect of the principle according to which the core Criterion and Evidence vocabularies are to be designed so they can be reused cross-sectorly.

i) Current situation

![image](https://cloud.githubusercontent.com/assets/24680325/21363202/e93f7986-c6eb-11e6-90b4-d0465a00c367.png)

ii) Lots an Criteria grouped:

![image](https://cloud.githubusercontent.com/assets/24680325/21420741/9ad9c6e4-c82f-11e6-8aa0-3f4c2b774c20.png)

* One advantage: the core Criterion object is not restricted only to procurement (tendering, in our case);
* Two inconvenients: (i) Criterion instances have to be duplicated per Lot; (ii) at edition time many selection criteria will have to be selected per each Lot;

iii) One Criterion points at zero, one or multiple Lots:

![image](https://cloud.githubusercontent.com/assets/24680325/21420758/b2588b66-c82f-11e6-9096-ad3d94edaf21.png)

* Two advantages: (i) the core Criterion object is not restricted only to procurement (tendering, in our case); (ii) Only one instance of Criterion is needed; 
* One inconvenient: at edition time one or more Lots will have to be selected per each Criterion. If the PP is divided in dozens or hundreds of Lots the selection can become really cumbersome an error-prone.

The mockups for this last option are shown below:

* 1)  CA mockup view:
![mu_criteriaselectionlot_ca](https://cloud.githubusercontent.com/assets/24680325/21363711/0e14b300-c6ee-11e6-8011-ead11eff2071.png)

* 2) EO mockup view:
![mu_criteriaselectionlot_eo](https://cloud.githubusercontent.com/assets/24680325/21363727/1a6b03c0-c6ee-11e6-87ab-022afe51cdcd.png)

**Comment by arocamop** [comment]
To discuss:

1) Think and strongly argument why Option A would not be the optional option. We are currently convinced that having one ESPD per Lot is not a bad solution at all. It would simplify the model and reduce complexity and errors to both EOs and evaluators.

2) In our opinion, if option B would considered a better Option than A, then the best choice would be (iii) Criterion points a zero, one or multiple Lots (the one the mockups above included catter for). But let's discuss it.

Cheers.

**Comment by ec-mcs** [comment]
During the discuss I modified the mockup for the general yearly turnover. The conclusion is that for some criteria the CA would/could provide different minimum requirements but the answer would be given by the EO only once
![untitled](https://cloud.githubusercontent.com/assets/20335285/21392602/ef452cc2-c790-11e6-87a6-ee2684703e84.png)

**Comment by rantati7** [comment]
I have a request from FI users of our self-contained ESPD that is now online (in time for our new act on public procurement that requires the use of ESPD):

First, regarding lots with different exclusion grounds and selection criteria 
- 83% of the respondents would do separate invitations to tender (and hence separate ESPDs) for lots where the requirements for exclusion and selection differ by lot.

![image](https://cloud.githubusercontent.com/assets/20238848/21611169/5df08e1c-d1d4-11e6-962c-80b071ce4441.png)

Second, it's only necessary to have CA to fill in the lot descriptions in her view and it would only need to show in part II A (where applicable, indication of the lot(s) for which the economic operator wishes to tender.. see below). CA would define in her view the lots. CA would then select from a dropdown list which lot he wishes to participate in .

![image](https://cloud.githubusercontent.com/assets/20238848/21611354/306f08c8-d1d5-11e6-897d-efb1523a4ae1.png)

Including complex dependencies would possibly just mess up ESPD (or make it more dificult to use).

**Comment by ec-mcs** [comment]
Michael De Winne / e-Proc Belgium: maybe not all of the selection criteria need to be able to vary from lot to lot?

Laura Martin / Scottish Government: If the selection criteria differs, there needs to be the possibility of having a seperate ESPD per lot but if possiblt all linked to the same procurement exercise/notice.

Marc-Christopher SCHMIDT: The ESPD would/should cater than for all the lots mentioned in one contract notice. I would suggest that we will make a proposal to discuss this next week.

Marc-Christopher SCHMIDT: As we are doing currently a consultaiton on the new notices we should make sure that the same logic can be applied to the notices and the ESPD

Rudolf Maier: One possibilty would be to use the same criteria for all lots and just write a notice to the lot where the criteria are different.

Marc-Christopher SCHMIDT: Rudolf, that would force the EO to look at the notice to fill out the ESPD. So I would suggest not going this route.

Marc-Christopher SCHMIDT: We will make a proposal for the next meeting. Shall we continue to the next issue?

Michael De Winne / e-Proc Belgium: ok

Laura Martin / Scottish Government: Yeah

Marc-Christopher SCHMIDT: New topic - fields https://github.com/ESPD/ESPD-EDM/issues/56

Rudolf Maier: What i meant is to put extra description to the respective lot in the ESPD.

Timo Rantanen / Hansel / Finland: remember that there is also question on lots in Part II -where the EO is aked which lot he wishes to participate in.

Timo Rantanen / Hansel / Finland: issues 56

Marc-Christopher SCHMIDT: Right Timo. This should be something like a selection box so that they would only see the content of the ESPD which is necessary for these lots :-)

Timo Rantanen / Hansel / Finland: we detected this from teh feedback on our self-contained ESPD

**Comment by paulakeen** [comment]
We'd like to follow Laura's and Alba's proposal: one Lot --> one ESPD, this way:

1) the model is kept minimalistic and simpler
2) software applications have an opportunity to produce automatically as many ESPD as necessary based on one single Procurement Project (PP) that binds all its Lots through its "ContractFolderId" Unique Identifier. The CA can use the resulting ESPD instances to add, modify, or delete the "base" PP criteria.

**Comment by ec-mcs** [comment]
Roles in ESPD
![untitled](https://cloud.githubusercontent.com/assets/20335285/22066333/d00b2890-dd8c-11e6-81a5-b0c418a5a1c0.png)

**Comment by arocamop** [comment]
We've been considering your proposal of the list of EO roles. We'd like to make this other counter proposal:

**Is the economic operator participating in the procurement procedure together with others?**

1.  If "yes":

- Consortium Leader
- Consortium Patner
- Subcontractor

2. If "no": 

- Sole Tenderer 
- Subcontractor

We will provide a mockup asap.

**Comment by rantati7** [comment]
What makes this tricky is the dual-role a subcontructor can have. The role of the subcontractor needs to be decided by the EO that assumes the leading role.

It can have two types of subcontractors:

a) subcontractor whose resources the the leading partner (supplier) relies on for fulfilling the requirement in part IV
b) subcontractor whose resources the leading partner (supplier) DOES NOT rely on for fulfilling the requirements in part IV.

Depending on the type of subcontractor the fields that it needs to fill in also differs. In case a) the subcontractor needs to fill in ... pretty much the whole ESPD.

In case b) the subcontractor needs to fill in only part III - but selectively unfortunately.

I would lift this question right at the beginning: in what role are you filling in / submitting ESPD?

This needs to be thoroughly though over.

I am not yet convinced that we have managed to capture all possible permutations!

Timo


Sent from my iPad

On 19 Jan 2017, at 19.42, arocamop <notifications@github.com<mailto:notifications@github.com>> wrote:


We've been considering your proposal of the list of EO roles. We'd like to make this other counter proposal:

Is the economic operator participating in the procurement procedure together with others?

  1.  If "yes":

  *   Consortium Leader
  *   Consortium Patner
  *   Subcontractor

  1.  If "no":

  *   Sole Tenderer
  *   Subcontractor

**Comment by arocamop** [comment]
Dear Timo,

Many thanks for your observation. Indeed some permutations as the one you just describe above will be identified in time.

We like your idea of having new types of ESPD creators additionally to CA and EO. This would enable the ESPD service application to dynamically behave appropiately. We will try to come up with a mockup for this.

**Comment by arocamop** [comment]
Following discusions see this mockup:

![mu_start_roles](https://cloud.githubusercontent.com/assets/24680325/22241552/1f3c3caa-e220-11e6-8f58-21f4541a8f13.png)

**Comment by ec-mcs** [comment]
To have one lot per ESPD will be an overkill. There could be 400 lots and the only difference is the nuts code. So the thumb of rule should be that the same set of criteria are in one ESPD (this could be 1 lot or several lots)
The buyer should define for which lot this ESPD is relevant (Part I "Information about the procurement procedure")
- Example lot 1 to 12 or 2,5,9
Screenshot of the Contract Notice
![lots](https://cloud.githubusercontent.com/assets/20335285/22692678/5bba9b24-ed40-11e6-9048-1362d5e1daf4.PNG)


The supplier should define for which lot(s) he participate in Part II
- Example lot 1 to 5 or 1,5,6

**Comment by arocamop** [comment]
The proposal of selecting the role of the EO in the coverpage has been dismissed and replaced by a similar solution in section A of Part II: Information concerning the economic operator, as shown below:

![image](https://cloud.githubusercontent.com/assets/24680325/22736212/6e88558a-edfd-11e6-9c91-6f3d75013ded.png)

**Comment by arocamop** [comment]
Please find below a proposal for the identification of lots and related information by the Contracting Authority:

![mu_part_i_ca](https://cloud.githubusercontent.com/assets/24680325/22935794/e7b1b9d0-f2d3-11e6-8d15-4247a416fc6e.png)

This other mock-up below would allow the Economic Operator to select those lots the EO is interested in by moving the identifier of the lot from the left box and into the right one. However, having this component in section A (Information about the EO) doesn't make much sense. It should go to into a section about the procurement procedure, as we do for the CA.

![image](https://cloud.githubusercontent.com/assets/24680325/22736212/6e88558a-edfd-11e6-9c91-6f3d75013ded.png)

**Comment by ec-mcs** [comment]
Marit Lysemose Thomsen, Mercell: it could also be a group of lots, no?

Laura Martin / Steve Patterson / Scottish Government: Yes to lot number and lot title but not sure you need the last option

Anne Katrine Mortensen: I agree. It should be sufficient.

Marit Lysemose Thomsen, Mercell: on the notice the CA can identify a group of lots...

Marit Lysemose Thomsen, Mercell: agree Jose

SELLITTO Giampaolo IT: groups of lots can make it very complex...

SELLITTO Giampaolo IT: it is better to stand with one lot - one ESPD

Timo Rantanen / Hansel / Finland: Is "tenders may be submitted for... one lot etc. )" also in Contract Notices?

Timo Rantanen / Hansel / Finland: i cannot remember.... 

Timo Rantanen / Hansel / Finland: I would avoid dublication

Timo Rantanen / Hansel / Finland: Lot title is more relevant than lot number

Laura Martin / Steve Patterson / Scottish Government: I agree you need the lot number but think you need the title too.

Laura Martin / Steve Patterson / Scottish Government: We will try and find one

Michaël De Winne / e-Proc Belgium: http://ted.europa.eu/udl?uri=TED:NOTICE:56863-2017:TEXT:EN:HTML&src=0

Michaël De Winne / e-Proc Belgium: procurement with lots

Jose Luis Cueva - Spain: I think the drawbacks of lot title are greater than ommitting it and just put the lot id

Michaël De Winne / e-Proc Belgium: (but it's only visible in the original language I'm afraid

Timo Rantanen / Hansel / Finland: http://ted.europa.eu/udl?uri=TED:NOTICE:57512-2017:TEXT:EN:HTML&src=0

Jose Luis Cueva - Spain: even more for automatic e-Procurement

Jose Luis Cueva - Spain: Is there an example in Greek?

Timo Rantanen / Hansel / Finland: This is exactly the reason why I do not want the dublication

Jose Luis Cueva - Spain: asking all EEOO to write the lot titles in a different alphabet is a chore that can be avoided

Jose Luis Cueva - Spain: Plus the problem with character encoding (if non Unicode)

Laura Martin / Steve Patterson / Scottish Government: Yeah

Anne Katrine Mortensen: An example of a contract notice with lots (15): 2017/S 011-016175

Timo Rantanen / Hansel / Finland: Please not in part II - we can populate this information from eTendering sysmte but not the number of lots they intend to take part

SELLITTO Giampaolo IT: lots can have different criteria expecially for the qualifiction part

Laura Martin / Steve Patterson / Scottish Government: http://ted.europa.eu/udl?uri=TED:NOTICE:321552-2016:TEXT:EN:HTML&src=0 Example of a noitce with multiple lots.  Same NUTS code but different criteria per lot.

Anne Katrine Mortensen: The ESPD-website is unavailable. I will send you the specific ESPD later.

SELLITTO Giampaolo IT: we shall forster re-use of the ESPD but also make the submission process as simple as possible

Jose Luis Cueva - Spain: Even if every lot can have different criteria/requirement, it might be possible that a single set of (hig level)  capabilities can fulfill several sets of requirements (eg having betterfinance than the highest required by any lot)

Anne Katrine Mortensen: The Danish ESPD C:\Users\Akam\Desktop\espd-requestHOFOR.xml   But if your´re unable to open you may find the ESPD on : http://www.hofor.dk/installatoerer-og-leverandoerer/igangvaerende-udbud/  by going down to Rådgiverydelser 2017+ and press the Downloadline.

Timo Rantanen / Hansel / Finland: My microfone does not seem to work

Timo Rantanen / Hansel / Finland: I type

Anne Katrine Mortensen: In the Danish example: Only 1 ESPD for that competition with 15 lots. And the CA wants  only1 ESPD even though an EO sapplies for 15 lots.

Jose Luis Cueva - Spain: From the ESPD model point of view it should make possible  to using a single ESPD for several/all lots, 

Anne Katrine Mortensen: Yes. Possible, but could be a very long ESPD and difficult to read.

Jose Luis Cueva - Spain: but nothigg prevents an EO to provide 1-1 ESPD for every lot

Anne Katrine Mortensen: The CA in the Danish example has said that an EO only can send 1 ESPD in all - no matter how many lots an operator applies for.

Jose Luis Cueva - Spain: Anne: could you provide your bidders with a "merging service" that joins all ESPDs for different lots in the same procedure?

Timo Rantanen / Hansel / Finland: What we are doing with the current ESPD already and in (structured eTendering system this is easy), 1.	if the selection criteria differs between lots -> separate into several tenders with their own ESPD2.	if both exclusion and selection criteria differ -> again separate tenders – not to lots – all tenders with own ESPDIn general, and with structured tendering system, I foresee that the use of lots is likely to diminish. We should remember that these choices we are making will be affecting the way CAs do their calls for tenders. Do we want to promote the lots (I guess the answer is partly yes) but - really - with eTendering systems lots could be turned to separate procurement procedures. Why CAs have split the procedures to lots, stems partly from the paper world where it’s easier for do a big tender by splitting it up which also means less pages in call for tenders than if separate into 20 or 200 separate tenders.  

Timo Rantanen / Hansel / Finland: you can read this later

Timo Rantanen / Hansel / Finland: and think about it

Cécile: did you discuss the difficulty to establish the participation of each group member to a list of lots in a consistent way 

Jose Luis Cueva - Spain: can exclusion criteria differ between lots? really?

Jose Luis Cueva - Spain: can somebody give us an example?

Anne Katrine Mortensen: I don´t quite understand your question, JL. 

Timo Rantanen / Hansel / Finland: Jose Luis: I have now a case where the exclusion grounds differ between lots... or because of this we shilt the procurment not into lots but to separate tenders. 

Timo Rantanen / Hansel / Finland: split

Timo Rantanen / Hansel / Finland: yes exacltu different procedures

Marit Lysemose Thomsen, Mercell: yes

Jose Luis Cueva - Spain: Anne, my question relates to the problem raised by Timo

**Comment by arocamop** [comment]
Please find below a proposal for lots management, from two perspectives:

1. **CA perspective**: we propose not to ask whether the procurement procedure is divided into lots or not, but to directly ask for the number of lots the contract is divided into (0 and 1 would mean the procedure is not divided into lots). If the number of lots entered by the CA is >1, two boxes will be displayed (as shown in the mock-up below), in order for the CA to select the lots that are to be included in the ESPD (that is, a group of lots that share the same exclusion and selection criteria). The CA will be able to move all lots at once, and also to select specific lots. 

![mu_part1_lots_ca](https://cloud.githubusercontent.com/assets/24680325/23206897/a8fa3100-f8ef-11e6-827a-1f9f3cd9be39.png)


2. **EO perspective**: when the procurement procedure is divided into lots, the EO will need to select the lots for which he wants to tender. In order to do so, two boxes will be displayed (as shown in the mock-up below), where the first box will display the lots established by the CA for this ESPD. The EO will be able to move all lots at once, and also to select specific lots. 

![mu_part2_a_lots_eo](https://cloud.githubusercontent.com/assets/24680325/23158023/ce9c2c7e-f81d-11e6-9db8-e24cfca145ed.png)

**Comment by ec-mcs** [comment]
Thx for the mockups. Looks good to me.

**Comment by paulakeen** [comment]
Please find below a proposal for the selection of the lots that apply to an ESPDResponse (EO perspective). For this proposal, we take the case where the CA has generated different ESPDRequests for the different lots the procurement procedure is divided into. 

![image](https://cloud.githubusercontent.com/assets/16134316/23892498/29a2adea-089b-11e7-8719-2e6852e4bf53.png)

We see risks in allowing the EO to create a single ESPDResponse with lots from different ESPDRequests, for the system cannot control the differences in the selection criteria included in the different ESPDRequests.
Let's discuss it tomorrow.

**Comment by paulakeen** [comment]
Please find below what was commented about this issue in the discussion group:

Rudolf Maier: Where should be more than one ESPD for one procedure with several lots?

Rudolf Maier: Cannot the different requirements of the various lots be covered with one ESPD and the possibility to answer this criteria by making the section of Lots dynamic (each lot is shown seperatly in the same ESPD?

Anne Katrine Mortensen: I prefer one ESPD per lot. As we recently had to make one ESPD with 93 pages because it had to contain information reg all 19 lots.. Very complicated.

Anne Katrine Mortensen: At least I prefer the last possibility not being there. The first is the best and can stand alone.

John Degiorgio 2: Marc I believe that the ESPD should be integrated into the tender submission and be as simplified as much as possible. Elsewhere we agree  on 1 submission throughout

Marit Lysemose Thomsen, Mercell: IF using procurement system: One ESPD per purchase. CA can indicate for wach criteria which lots it is relevant to. When EO makes bid on a lot, the correct questions are shown

Rudolf Maier: Most of the evidences will be the same for each lots. Many ESPD would be created just to make a difference in one evidence the others are repeated/the same fpor all lots.

Rudolf Maier: This is the point - all evidences were the same - only the references where different from lot to lot.

Jose Luis Cueva - Spain: I agree with Rudolf

Marit Lysemose Thomsen, Mercell: But flexibility is complex

Giampaolo Sellitto ANAC: it is not a problem if the same ESPD can be linked to different lots... the content remains the same but tit is associated to different lots

Rudolf Maier: I cannot understand why there should be so many NUTs - Cods. If the place for service is spread all over the country I use the country NUTS code.

Jose Luis Cueva - Spain: As long as the eESPD is an electronic, structured document, a computer program shoud be able to automatically matching  every item in the eESPD against the corresponding requirement in the corresponding lot.

Rudolf Maier: There are procedurs of 50 and more lots, e.g. in the medical field. To have 50 ESPDS would be hardly to handle for the CA and likly for making mistakes.

Jose Luis Cueva - Spain: Therefore the lenght of the eESPD is not a burden for the C.A. --> it is dealt by the computer

Rudolf Maier: Can yu repeat the question?

Giampaolo Sellitto ANAC: if we adopt the one size fits alland we do not associate the espd to a specific lot, the self declaration can loose its value. We have some procedures of 1000 and more lots where some lots require high qualification and some very low value qualifications and technical requirements

Rudolf Maier: It may be different in one or two points from lot to lot, e.g. concerning references.

Giampaolo Sellitto ANAC: e.g. health sector tenders for medicines and syringes and so on

Marit Lysemose Thomsen, Mercell: yes Jose

Rudolf Maier: Jose is right. Why not allow a list in one section of ESPD and to underline any special request for certain lots?

Alba Colomer (GROW): but when defining the exclusion and selection criteria, how will the CA specify for which lot is each criteria?

Jose Luis Cueva - Spain: M-C: sounds OK

Steve Patterson (Scottish Government): MC there are 2 different scenarios. You mentioned NUTS codes, which are not selection or exclusion criteria, so the same ESPD can be used, However where the difference betreen the lots is one of the selection or exclusion criteria, for example turnover, they supplier will have to provide a differnt ESPD each time, even if this is the only difference between lots. 

Jose Luis Cueva - Spain: Steve: the EO can privide a single figure for turnover, which is higher than the highest required for any lot it applies for.

Jose Luis Cueva - Spain: No need to provide five figures for the turnover

Jose Luis Cueva - Spain: a) for common requirements: single data (better or equal to the highest threshold). b) for different criteria: one item for every requirement, all in the same eEDSP

Alba Colomer (GROW): sure

Jose Luis Cueva - Spain: A key feature for the ESPD-EDM: to guarantee 100% interoperability fo rall independent implementations compliant to the EDM

**Comment by paulakeen** [comment]
Please find below a new proposal for the solution and mock-ups regarding lots management, according to what was commented on last Wednesday's session:

- ESPDRequest:

In Part I, the CA provides de number of lots the procurement procedure is divided into:

![mu_lots_parti_ca](https://cloud.githubusercontent.com/assets/16134316/24103632/2aec1a30-0d80-11e7-8080-13cf77929936.png)

In Part IV, the CA provides, for each criteria. the specific requirements and the set of lots these requirements apply to. By default, all specific requirements will apply to all lots, so the CA must only select the lots for requirements that apply only to particular lots.

![image](https://cloud.githubusercontent.com/assets/16134316/24103299/218ac604-0d7f-11e7-988f-5242269313fa.png)

- ESPDResponse:
In Part II Section A, the EO provides the lots for which the economic operator wishes to tender:

![image](https://cloud.githubusercontent.com/assets/16134316/24103410/787cf176-0d7f-11e7-8033-f919ffbfd155.png)

In Part II Section C, when the EO relies on the capacities of other entities in order to meet the selection criteria, the EO must provide the lots for each entity:

![image](https://cloud.githubusercontent.com/assets/16134316/24103483/b64254a6-0d7f-11e7-89b8-ece1a4ac861a.png)

In Part IV, the system will display the specific requirements that apply to each lot, and the EO will be able to provide information for specific lots:
 
![image](https://cloud.githubusercontent.com/assets/16134316/24103558/f1d3eaac-0d7f-11e7-9e63-d43d4ecff8dc.png)

**Comment by paulakeen** [comment]
Please find below what was commented about this issue in the discussion group (22/03/2017):
Alba Colomer (GROW): should this Type of activity be a free text field?

Alba Colomer (GROW): ok

Marit Lysemose Thomsen, Mercell, DK: Should it be possible to create several versions of the same criteria, to add different lot to the different versions?

John Degiorgio: Experience?

Enric Staromiejski (GROW): @Marit not necessary with the solution that MC is describing

virgiliu: it is not obvious from the mock-up that you can add multiple references for different lots

Marit Lysemose Thomsen, Mercell, DK: @Enric thanks, thinking of this scenario, dont know if it is relevant: CA selects and defines criteria:Criteria A applies to all lotsCriteria B1 applies to lot 1,3,4Criteria B2 applies to lot 2Criteria B3 applies to lot 5,6CA might have different specs on a criteria depending on the lot?

Anne Katrine Mortensen, DK: I find that stating the lot no is easier for both the CA when checking upon receiving the bid and for the EO when formulating an ESPD with a lot of lots in one ESPD.

virgiliu: the general experience can be modeled as a requirement

Anne Katrine Mortensen, DK: Yes. I think so. As a EO might supply for several lots in one ESPD.

Michaël De Winne / e-Proc Belgium: Yes the EO only needs to know for which lots there are specific requirements, I think

Anne Katrine Mortensen, DK: I agree.

Jose Luis Cueva - Spain: my point is: the EO does not need to match every performance to every lot. It  makes  thinks much more complex, and neither the EO nor the CA needs it really

John Degiorgio: As I wrote last Wednesday the ESPD should not turn cubersome 

Anne Katrine Mortensen, DK: I agree, M-C. We have to make it easy for the CA and the EO.

virgiliu: that's why they can select multiple lots

Michaël De Winne / e-Proc Belgium: mic problem, sorry

Enric Staromiejski (GROW): @josé luis: no, no, no, 

Enric Staromiejski (GROW): @José luis: one ESPD one EO

John Degiorgio: Ok thanks

Marit Lysemose Thomsen, Mercell, DK: yes :-)

Jose Luis Cueva - Spain: good

Marit Lysemose Thomsen, Mercell, DK: it is great, huge

Anne Katrine Mortensen, DK: If only 1 ESPD pr. team couldn´t we provide the possibility for numerous signatures?

John Degiorgio: An important element is that CAs would have the possibility to very the data being provided by EOs with the respective institutions

Jose Luis Cueva - Spain: XAdES standards makes possible to have different parts of an XML signed by different people, but I do not know whether real implementations of XAdES  handle this well and in an interoperable way.

John Degiorgio: Let's make it paperless please ...

Marc-Christopher SCHMIDT: Alba/Enric could you check if this is possible/what needs to be done to use Xades correctly

Enric Staromiejski (GROW): @MC: Yes

**Comment by paulakeen** [comment]
Please find below a new proposal for the solution and mock-up regarding the information the EO will need to provide in Part IV (Selection criteria) when the procurement procedure is divided into different lots.

![mu_references_lots_eo_55](https://cloud.githubusercontent.com/assets/16134316/24545215/9e23af20-1606-11e7-8c80-bb73964cff27.png)

As shown in the mock-up, the EO will be able to define a set of lots and provide as many references as needed for this set of lots. If need be, later on the EO can add another set of lots for which the EO will again be able to provide as many references as needed.

**Comment by paulakeen** [comment]
Please find the details of the final decision in https://github.com/ESPD/ESPD-EDM/wiki/9.-Lots-management
