### ISSUE TITLE
Regulated ESPD vs Self-contained ESPD

### ISSUE THREAD

**Issue by rantati7** [OP-TED/ESPD-EDM#56]
Part III: Exclusion grounds 
C: Grounds relating to insolvency, conflicts of interests or professional misconduct

For having the ESPD self-contained the three first Qs need CA input: Breaches in environmental law, social law and labour law.

Also the text need modification. See my mock-up.

![dia1](https://cloud.githubusercontent.com/assets/20238848/21448669/daba7272-c8ed-11e6-919c-41cb1c9866e7.PNG)
![dia2](https://cloud.githubusercontent.com/assets/20238848/21448672/de7353d4-c8ed-11e6-9438-ea8b213e5b34.PNG)
![dia3](https://cloud.githubusercontent.com/assets/20238848/21448676/e12adc78-c8ed-11e6-8afc-58aa6b48b9db.PNG)

**Comment by rantati7** [comment]
maybe instead of "breaching of OTHER obligations" the text should (maybe) read: "breaching of SPECIFIC obligations"

**Comment by ec-mcs** [comment]
Marc-Christopher SCHMIDT: Ok issue 56. Timo said that we currently have a number of times the following text in the ESPD "see notice, proc docs or ESPD". In the self contained ESPD it should be different.

Marc-Christopher SCHMIDT: I would suggest the following

Timo Rantanen / Hansel / Finland: Every part where there is text "relevant notice or the procurement documents" the information shouldbe provided in self-contained ESPD....

Laura Martin / Scottish Government: agree, Timo

Marc-Christopher SCHMIDT: I would suggest that the CA in the ESPD can select between "regulation ESPD" or "self-contained ESPD". When CA selects "self-contained ESPD" this text is not shown at all...

Marc-Christopher SCHMIDT: Yes Timo. And there are parts where this is not mentioned but still necessary...

Timo Rantanen / Hansel / Finland: yep

Laura Martin / Scottish Government: Sounds good, MC

Rudolf Maier: The crossed out (red) text is not necessary. Therfor I see no necessity to use two versions of ESPD.

Timo Rantanen / Hansel / Finland: BUT the real issue is that in self-contaned version ther shouldbe some place to put those requirements. That's why I split the Qs into two.

Rudolf Maier: Yes, this place is necessary but it is already provided anyway.

Marc-Christopher SCHMIDT: Having only one text for both versions would be indeed bettter. We could think that if the self-contained version is ready that we use something like an informaiton box if the CA selected "regulation ESPD": Dear EO, how you can fill in the ESPD please look at the eProc docs or notice

Marc-Christopher SCHMIDT: Rudolf: If someone uses the self-contained ESPD they should not provide this as well in other documents as well...

Laura Martin / Scottish Government: Agree, guidance would be needed to remind CA that criteria would need to be in notice/docs if the 'regulation ESPD' was selected

Marc-Christopher SCHMIDT: I would suggest that we make a mockup and discuss this from there?

Marc-Christopher SCHMIDT: Ok for your?

Laura Martin / Scottish Government: Yeah

Timo Rantanen / Hansel / Finland: mock up on whole ESPD (where we stand at this point) highly welcomed!

**Comment by ec-mcs** [comment]
Rudolf Maier: In most cases the space in the ESPD should be sufficient for description. I cdon't think that lengthy descriptions bythe CA concerning the exclusion grounds are necessary.

Marc-Christopher SCHMIDT: I agree Rudolf

Marc-Christopher SCHMIDT: We had just before Christmas a very interesting mail exchange with LT about taxes

Marc-Christopher SCHMIDT: The case: If a supplier from country A participates in a public procedure in country B they have to respect the amount of the buyer. In Lithuania in PP procedures if the supplier has more than 50 € unpaid tax they will be excluded.

Timo Rantanen / Hansel / Finland: in this one case that I had, 500 marks was nto enouhgt for the CA. And I agreed as their environmental law requirements went on far more detalled level than what was in the law (the reqwuirments were still inline with the law) 

Timo Rantanen / Hansel / Finland: about taxes....

Marc-Christopher SCHMIDT: Ok. How about providing the possibility for the CA to define a threshold?

Marc-Christopher SCHMIDT: Please Rudolf

Rudolf Maier: The EO is always adviced to make sure that there are no debts even though the € 50 should not be a problem.

Marc-Christopher SCHMIDT: The threshold depends on the country. In LT by law > 50 € and EO is out

Marc-Christopher SCHMIDT: In Germany this is up to the CA to decide

Laura Martin / Scottish Government: In the UK, its up to the CA too

Marc-Christopher SCHMIDT: Please Timo

Timo Rantanen / Hansel / Finland: Finland: 0€ and you are out. Unless you have made an agreement with the tax man on payback

Marc-Christopher SCHMIDT: How about providing in eCertis the possibility for countries to define the threshold?

Timo Rantanen / Hansel / Finland: This actually shows that in other places of ESPD (part III) there might be a need to have a description field. Currently this can be described in eCertis (if we had instructions whihc part in eCertis becomes visible in ESPD and how it's shown there).

Marc-Christopher SCHMIDT: Indeed... we have to identify them

Timo Rantanen / Hansel / Finland: I updated eCertis data before our new PP law came to power on 1.1.2017 and made a complete mess out of eCertis....

Marc-Christopher SCHMIDT: Timo - I guess you did a fantastic job with eCertis :-)

Marc-Christopher SCHMIDT: As well here I would suggest to make a mockup for eCertis/ESPD to show how this could be integrated

Timo Rantanen / Hansel / Finland: as I said - complete mess! But those fields really do need to be identified. I would leave this however to eCertis and would not do anything  new with ESPD 

Marc-Christopher SCHMIDT: Timo we need to address both: In LT by PP law 50 € is the threshold. In Germany or UK up to the CA. In eCertis for the Taxes critiera the editor allows for providing a threshold or saying "Up to CA". If it is by law, the threshold will be shown in ESPD if "Up to CA" the CA can provide the threshold

Marc-Christopher SCHMIDT: Using only the chat is a good exercise to learn typiing ;-)

Timo Rantanen / Hansel / Finland: other topics?

Marc-Christopher SCHMIDT: Please Rudolf

Marc-Christopher SCHMIDT: None from my side. Anyone else?

Laura Martin / Scottish Government: not for me

Marc-Christopher SCHMIDT: Ok I would suggest for the agenda next week to discuss the mockups and go through the Timo mentioned list to check where we are and what we still have to do

Timo Rantanen / Hansel / Finland: thanks!

Laura Martin / Scottish Government: sounds good!

Michael De Winne / e-Proc Belgium: ok

Rudolf Maier: The EO can avoid the problem of the € 50 by using a evidence issued by the tax authority which states that there are no debts as 50 or more € can be shown on the tax account due to small differences occuring in the prescription and booking of the bank transfers. What I mean is that this 50 or more € are onlay a problem if the tax authoirity has aready urged the EO to pay this debt.

Marc-Christopher SCHMIDT: True Rudolf. So if I understand correctly the Tax certificate would show 50€ if this is missing.

Marc-Christopher SCHMIDT: I would suggest to continue the discussion next week. Bye bye! See you next week!

**Comment by arocamop** [comment]
To meet the request by Timo of having a free text in order to better specify Exclusion criteiria we could add a new element to the ccv:Requirement class as shown in the diagram below (AdittionalInformation element):

![image](https://cloud.githubusercontent.com/assets/24680325/21770546/0c396a44-d684-11e6-87ef-854c09abf77e.png)

**Milestone**: Version 1.1.0


This would cater for any implementation you'd prefer of the "Regulation ESPD" vs. "Self-Contained ESPD".

**Comment by ec-mcs** [comment]
Actually this would not be a requirement. The idea of "Regulation ESPD" vs. "Self-Contained ESPD" was that the CA can select on the starting page which possibilities they would like to use. So it would be for the whole ESPD not for a single requirement. And it might not even be necessary to have it in the model itself.

**Comment by arocamop** [comment]
Agree; either way, the introduction of a free text field as a flexible way of better specifying national requirement about some exclusion criteria (e.g. 50 Euros max amount allowed in case of tax breach) would be a good idea; and in general having a text to separate specific national requirements related to any type of criterion makes the model more flexible.

**Comment by arocamop** [comment]
Following discusions see this mockup:

![image](https://cloud.githubusercontent.com/assets/24680325/22033886/9f06cdf0-dcea-11e6-83a1-447567f439bf.png)

1) Regulated ESPD:

CA view (No changes):

![mu_regulated_ca](https://cloud.githubusercontent.com/assets/24680325/22033910/bb90e190-dcea-11e6-973c-b5cf5857c9e4.png)

EO view (No changes):

![mu_regulated_eo](https://cloud.githubusercontent.com/assets/24680325/22033913/c1bb940c-dcea-11e6-9a73-388306c1e26d.png)

2) Self-contained ESPD:

CA view:

![mu_self_contained_ca](https://cloud.githubusercontent.com/assets/24680325/22033941/d50e8014-dcea-11e6-9ce4-9c3a053e2991.png)

EO view:

![mu_self_contained_eo](https://cloud.githubusercontent.com/assets/24680325/22033962/e50785b0-dcea-11e6-9e9a-758a1ace69dc.png)

**Comment by paulakeen** [comment]
Please find below what was commented about this issue in the discussion group:

Anne Katrine Mortensen: "Regulated" and "Self-contained" need to be explained in a I note

Jose Luis Cueva - Spain: I got it!

Anne Katrine Mortensen: Self-contained is that for example using Mercell´s system?

Anne Katrine Mortensen: OK

Anne Katrine Mortensen: Of course.

Anne Katrine Mortensen: I suggest the wording: "Regulated/Delivered by EU" and "Self-contained/delivered via another procurement site"

Anne Katrine Mortensen: Why do you need this information?

Michaël De Winne / e-Proc Belgium: Do you have a list of all the actual differences between regulated and self-contained?

Anne Katrine Mortensen: It seems to me that the ESPD is getting longer and longer and more and more complicated.

**Comment by paulakeen** [comment]
Please find the details of the final decision in https://github.com/ESPD/ESPD-EDM/wiki/24.-Regulated-ESPD-vs--Self-contained-ESPD
