### ISSUE TITLE
Elements for the identification of a Consortium (EO roles)

### ISSUE THREAD

**Issue by arocamop** [OP-TED/ESPD-EDM#57]
The current version of the XSD Schema, plus the usual business practices, provides enough elements to determine whether and EO belongs to a Consortium or not.

1. Business practice: One EO or one Subcontractor can't belong to one or more Consortia for the same Procurement Project (**please confirm this is true**). 

2. The EO or Subcontractor MUST be identified using the element /ESPDResponseType/espd-cac:EconomicOperatorParty/cac:Party/cac:PartyLegalEntity/cbc:CompanyID (i.e. National, VAT-Number, LEI, BRIS-EUID, DUNS&BRATS):

![image](https://cloud.githubusercontent.com/assets/24680325/22216214/7a65215a-e19e-11e6-9f66-0921393e4cf0.png)

3. A short name MUST be used to unambiguously identify the Consortium (e.g. "LOTUS2","SEED", "LIGHTWAY", etc) . For this use the element:  /ESPDResponseType/espd-cbc:EconomicOperatorGroupName. All the EO and Subcontractors MUST use **exactly** the same name (this is critical):

![image](https://cloud.githubusercontent.com/assets/24680325/22216429/56bd343a-e19f-11e6-95ea-19ee25917209.png)

4. The Procurement Project is always identified with a unique number using the element **cbc:ContractFolderID**, which by the way is compulsory. This number is always provided by the CA.

5. The role of the EO. For this use the element /ESPDResponseType/espd-cac:EconomicOperatorParty/espd-cbc:EconomicOperatorRoleType:

![image](https://cloud.githubusercontent.com/assets/24680325/22216566/e5bc7bf0-e19f-11e6-85af-b92cfa4efdd4.png)

Therefore the set of all ESPD elements the should be provided are these five, but most importantly the Consortium's name.

However this solution is error-prone. One possible technical work-arround (rather a patch) could be using the /ESPDResponseType/cbc:ID and fill it in with an automatically generated twofold UUID, such as in "dda09d86-5484-47c3-9b03-da64fcd9e19c**.**e4bdf73a-6e15-45f4-9558-f624d0945961", where the first UUID "dda09d86-5484-47c3-9b03-da64fcd9e19c" identifies the Consortium and the second one this ESPD (and there for also the EO or Subcontractor):

![image](https://cloud.githubusercontent.com/assets/24680325/22217403/3668227c-e1a3-11e6-9a17-4b0f084bc5a5.png)

A more canonical solution would be to add a cbc:EconomicOperatorGroupUUID next to the cbc:EconomicOperatorGroupName to identify uniquely the Consortium. All the EO's and Subcontractor's would provide this UUID additionally (or alternatively) to the name of the group/Consortium.

Let's discuss it again next Wednesday.

**Comment by paulakeen** [comment]
Follows chatbox-text with conversation corresponding to meeting held on Wednesday the 25th January:

Marc-Christopher SCHMIDT: Hi, we will start at 13:04

Marit Lysemose Thomsen, Mercell: +45 60 95 26 56

Marit Lysemose Thomsen, Mercell: sorry! +45 60 94 26 56

Steve Patterson (Scottish Government): Would a slution be a aupplier workspcae area

Steve Patterson (Scottish Government): of the ESPD service, whhere bidders can pull togther and check their bids prior to submission.

Jose Luis Cueva - Spain: I think every bid (eg Consortium) shoud have an "unique ID", so it unambiguously identifies the bid and all members of the Consortium

Steve Patterson (Scottish Government): agree with Jose Luis, once the bid is submited there should be a unique ID, however I think there also needs to be an area where the bidders can work togther prior to submission if they are bidding with others.

Timo Rantanen / Hansel / Finland: Steve: This is what happens inside our eTendering system. We have built-in ESPD in our eTendering system and the leading EO combines the subcontractors / consortium members ESPD togethe.

Jose Luis Cueva - Spain: The "bid ID" can be included in all ESPDs of Consortium members, so the C.A. can easily group them toghether

Steve Patterson (Scottish Government): Timo, that sounds good! Unfortunately not all eTendering solutions currently work that way :(

Timo Rantanen / Hansel / Finland: yeP

Jose Luis Cueva - Spain: As long as ESPD is an XML file according to a clearly defined EDM, it should be easy to make services for aggregating all ESPD from Consortia members. It can be done either by Aggregators, eTendering, 3th party services...

Marit Lysemose Thomsen, Mercell: Timo, can main bidder see the responses from subcontractors?

Steve Patterson (Scottish Government): I would suggest pdf is not a great solution in the long term. most of our suppliers want to be able to store and re-use any previously submitted responses, which should be stored and re-called electronically.

Timo Rantanen / Hansel / Finland: Main contractor can see all but the the oehrway round

Timo Rantanen / Hansel / Finland: but not the other way round

Marit Lysemose Thomsen, Mercell: thnx

Dariusz: would it help if we would add the consortium identifier in the file name of the generated espd file?

Timo Rantanen / Hansel / Finland: But subcontractor is a subcontractor regardless of the field it works in

Enric Staromiejski (GROW): @Marit: one nice advantage of having the roles coded is that the ESPD can be customised based on the EO Role...

Jose Luis Cueva - Spain: I agree with Timo: in this data-field no need to explain nothing more than Lead/consortium member/subcontractor.

Jose Luis Cueva - Spain: So closed-list shoud suffice here

Steve Patterson (Scottish Government): agree with Timo and Jose Luis also.

Timo Rantanen / Hansel / Finland: Subcontracting things should actually be gathered together...

Jose Luis Cueva - Spain: I see only: 

Jose Luis Cueva - Spain: Consortium member/lead/Subcontractor/3th party (Part II-C)

Jose Luis Cueva - Spain: So a 4-items list migth suffice

Timo Rantanen / Hansel / Finland: 3rd party is subcontractor whose resources you do not rely on

Timo Rantanen / Hansel / Finland: sounds like hat

Timo Rantanen / Hansel / Finland: that

Jose Luis Cueva - Spain: 3th party is what article 63 says

Jose Luis Cueva - Spain: "reliance on the capacities of other entities"

Jose Luis Cueva - Spain: Part II-C  <-> article 63

Timo Rantanen / Hansel / Finland: that is not 3party but a subcontractor whose capacities one does not rely on

Mai-Ly Pham: Article 63Reliance on the capacities of other entities1.   With regard to criteria relating to economic and financial standing as set out pursuant to Article 58(3), and to criteria relating to technical and professional ability as set out pursuant to Article 58(4), an economic operator may, where appropriate and for a particular contract, rely on the capacities of other entities, regardless of the legal nature of the links which it has with them. With regard to criteria relating to the educational and professional qualifications as set out in point (f) of Annex XII Part II, or to the relevant professional experience, economic operators may however only rely on the capacities of other entities where the latter will perform the works or services for which these capacities are required. Where an economic operator wants to rely on the capacities of other entities, it shall prove to the contracting authority that it will have at its disposal the resources necessary, for example, by producing a commitment by those 

Jose Luis Cueva - Spain: A "3th party" is not part of the contract, but the bidder "relies on its capabilities" as a complement to his own capabilities

Jose Luis Cueva - Spain: A 3th party does not need to be neither subcontractor nor consortium member

Jose Luis Cueva - Spain: Ie a firm controlled by the bidder

Timo Rantanen / Hansel / Finland: no they are not

Jose Luis Cueva - Spain: perhaps "article 63"

Jose Luis Cueva - Spain: I would suggest makenig explicit reference to Article 63

Timo Rantanen / Hansel / Finland: if there is control the we might be speaking about "companies that belong the same "holding" or "groupd of companies". Lets take an example: Accenture bids as a the the main Company adn lists all its counru organisations as possible other "parties". Then these country organsiations are actually subcontractors  or consurtium members . 

Timo Rantanen / Hansel / Finland: I think we shoul stick to some commonly used terms

Steve Patterson (Scottish Government): I think the Main Contractor and Consortium Lead are both responsible for the ultimate submission of the bid.

Stefan Van der Meulen: May be a stupid question, but could a subcontractor not be considered also to be "an entity which you rely on"?

Timo Rantanen / Hansel / Finland: there are two types of subcontractors - those whose capacities the main supplier relies on and those whose capacities it does not rely on

Timo Rantanen / Hansel / Finland: this rely on refers on part IV in ESPD

Jose Luis Cueva - Spain: Timo: the usual case is the one you explin, but the Article 63 explicitly says "regardless of the legal nature of the links..."

Timo Rantanen / Hansel / Finland: Those "whose capacities the main bidder does not rely on" can be whatever and do whatever tasks as long as they capacities are not used in part IV 

Jose Luis Cueva - Spain: So we cannot restrict 3th party to Groups or Holdingas

Difi - Jan and Hilde: Yes

Stefan Van der Meulen: OK, thanks Timo

**Comment by ec-mcs** [comment]
Spoke with Claudio about Selection criterion "Subcontracting proportion". This is only to be used for II-D because for II-C a separate ESPD needs to be filled out. And we cannot combine it (or put directly under II-D) because it is a selection criterion.

**Comment by rantati7** [comment]
My bit witty contribution to this discussion with a case that could be real...

[Typical set.docx](https://github.com/ESPD/ESPD-EDM/files/730056/Typical.set.docx)

**Comment by rantati7** [comment]
My bit witty contribution to discussion on the roles of EOs in bidding stage. Enjoy
[Typical set.docx](https://github.com/ESPD/ESPD-EDM/files/730103/Typical.set.docx)

**Comment by rantati7** [comment]
In my writing I am suggesting that there are just four types of players in the bidding stage: 

1.	Contractor (or main contractor)
2.	Consortium Member
3.	Subcontractor  - whose capacities the contractor (or main contractor) relies on
4.	Subcontractor  - whose capacities the contractor (or main contractor) does not rely on

All other possible set-up as subsets of these four.  

One could also argue that there are just three:  contractor and consortium member could be just named as "bidder" / "supplier". When several companies bid as one (forming a consortium), they all are equal bidders / suppliers and will be treated as such also in the contract.

**Comment by rantati7** [comment]
One addition: 

Please note that the parts of ESPD the "other parties" need to fill in, depend on their role. 

Contractor and Consortiun Members need to fill in all. Subcontractor whose capacities are being relied on by the contractor needs to fill in more than a subcontractor whose capacities are not being relied on. 

Further, the contracting entity may decide that it does not require ESPDs at all from the latter group.

**Comment by ec-mcs** [comment]
@rantati7 This is a very good document. I will pass it on to Claudio for his opinion. We should discuss it tomorrow in the eMeeting.

**Comment by ec-mcs** [comment]
Here is the presentation from Anne about issues in the ESPD service (including consortia, subcontractor)...
[Wissenberg.pptx.pdf](https://github.com/ESPD/ESPD-EDM/files/741318/Wissenberg.pptx.pdf)

**Comment by paulakeen** [comment]
Just for your information: 

1. UBL-2.2 already modelled the document equivalent to the ESPDResponse. They call it UBL-QualificationApplicationResponse. Here it is how it looks like in UBL-2.2:
![image](https://cloud.githubusercontent.com/assets/16134316/22463637/f0951f1e-e7b2-11e6-8f56-bef59edef6b2.png)

2. Notice that in the UBL-2.2 document they use the **ProcurementProject** component to identify what you call "the bid". They also defined smaller components to refer to the bid, like "**ProjectReference**"Therefore any EO or subcontractor can refer to it. 

3. The structure for Procurement Project was already defined in UBL-2.1 and looks like this (Notice also the structure for **ProcurementProjectLot** and **ProjectReference**:

![image](https://cloud.githubusercontent.com/assets/16134316/22463728/78abc1fa-e7b3-11e6-90b6-651dd48b502f.png)

4. During the analysis and design of the ESPD the decision was made of not to add the component **ProcurementProject** as an additional element at the root of the document because "it already is included inside the component "**ProcurementProjectLot**". Therefore, in the ESPD, WE DO HAVE a method to refer to the bid: the "ProcurementProject@ID" and other of its subelements. The question remains to ask UBL-2.2 why did they decide to be so redundant and add ProcurementProject AND ProcurementProjectLot?

**Comment by arocamop** [comment]
For discussion this afternoon:

![mu_entities_c_eo](https://cloud.githubusercontent.com/assets/24680325/22504057/df817084-e874-11e6-9385-f375d0d273dd.png)

![mu_parties_d_eo](https://cloud.githubusercontent.com/assets/24680325/22504068/e6b780f0-e874-11e6-8682-d9d3e731f2e4.png)

**Comment by ec-mcs** [comment]
Marc-Christopher SCHMIDT: We will start 13:04

Zilvaras Gelumbauskas: I agree with Jose Luis, in legal terms

Jose Luis Cueva - Spain: I believe these 4 roles are OK

Zilvaras Gelumbauskas: I dont agree that there are only 4 roles

Jose Luis Cueva - Spain: can you hear me?

Jose Luis Cueva - Spain: my micro does not work

Zilvaras Gelumbauskas: Legaly Contractor can rely on capacity of fird party wich will not be a subcontractor 

Jose Luis Cueva - Spain: there are 4 roles: lead/single contractor, consortium member, subcontractor, AND  any  3td party whose capacities are relied on

Jose Luis Cueva - Spain: these 3rd party IS NOT A PARTY INTHE CONTRACT, 

Krijn de Veer (NL): these are the ones I could think of

Krijn de Veer (NL): have yet to find another

Jose Luis Cueva - Spain: AND CAN BE ANUBODY (art 63 Directive)

Timo Rantanen / Hansel / Finland: Subcontractor can be any company

Jose Luis Cueva - Spain: labeling "subcontractor implies a very precise legal relationship 

Jose Luis Cueva - Spain: so who fills the ESPD coul be misled

Krijn de Veer (NL): I would have to look into it but I wouldnt see why it would be wrong

Krijn de Veer (NL): what other relationship is there?

Jose Luis Cueva - Spain: I would stick to "third party" as defined in article 63 Directive

Krijn de Veer (NL): the term subcontracting comes from the directives (article 71 or something). It is well defined. Making it broader would inlcude also the company selling you your toilet paper who doens't have anything to do with the project

Krijn de Veer (NL): but I will have to look into article 63

Jose Luis Cueva - Spain: In part II-C does not even appear the word "subcontractor"

Timo Rantanen / Hansel / Finland: directives do not use work 3rd party. Just "party"

Timo Rantanen / Hansel / Finland: word

Jose Luis Cueva - Spain: "rely-on party (as in art 63)"?

Marit L. Thomsen, Mercell: yes good idea :-)

Krijn de Veer (NL): that's always a good idea

Krijn de Veer (NL): (the wine part)

Marit L. Thomsen, Mercell: If the invited subcontractor has previously filled out an ESPD on another project, can she reuse it?

Marit L. Thomsen, Mercell: so it is based on emails? they are unique?

Zilvaras Gelumbauskas: Looks goodĄ

Krijn de Veer (NL): I would like to have the slides in that case TImo

Krijn de Veer (NL): looks good

Jose Luis Cueva - Spain: sorry, my micro does not work

Jose Luis Cueva - Spain: we are considering a more decoupled architecture

Jose Luis Cueva - Spain: not so dependent on the server side

Jose Luis Cueva - Spain: But Timo's presentation is very nice

Jose Luis Cueva - Spain: As long as all capabilities of all parties are to be aggregated, it does not make sense to complicate thinngs with  hierarchies of several levels 

Jose Luis Cueva - Spain: (a+b)+c =( (a) +(b+c))

Krijn de Veer (NL): agreed with JL

Timo Rantanen / Hansel / Finland: https://github.com/ESPD/ESPD-EDM/issues/59

Krijn de Veer (NL): thanks Timo

Krijn de Veer (NL): exactly

Jose Luis Cueva - Spain: Nice, but perhaps adding an "ID qualifier" (eg, VIES, Registration number, etc) could be useful

Krijn de Veer (NL): what capacities are they bringing to the table?

Marit L. Thomsen, Mercell: Role and Field of expertise are two different needs

Jose Luis Cueva - Spain: ¿tasks to be performed (in the contract)?

Zilvaras Gelumbauskas: I fully agree with Timo, field of expertise is not needed. Need to me rrenamed

Marit L. Thomsen, Mercell: We need to know their "administrative" function and we need to know what commercial areas they contributing in

Krijn de Veer (NL): never mind that

Zilvaras Gelumbauskas: Technical ID is not needed, we need legal code of the company

Timo Rantanen / Hansel / Finland: ID Eu wide = VAT number

Jose Luis Cueva - Spain: 2-letter country + VAT number = VIES

Jose Luis Cueva - Spain: EG: ES + Spanish VAT number -> VIES of Spanish company

Krijn de Veer (NL): as you might already guess, i like it

Krijn de Veer (NL): Coming back really quickly to our earlier discussion, just for when everybody is drinking wine

Krijn de Veer (NL): Regarding 2C, Jose Luis is right from a legal point of view. Article 63 states using other entities “regardless of the legal nature of the links which it has with them”. This group is theoretically broader than subcontractors. However, I don’t think this occurs a lot (if at all) so from a pragmatic point of view, for clarity, we could consider using subcontractor. I have yet to find out why 2D speaks of subcontracting all of a sudden. Summary: from a strict legal point of view, it should be “other entities”. 

Jose Luis Cueva - Spain: Regarding to 3th party label, if the Commission is happy with any, me too.

Marit L. Thomsen, Mercell: thank you and likewise

Krijn de Veer (NL): BYE

Jose Luis Cueva - Spain: bye

Stefan Van der Meulen (Belgium): bye

Zilvaras Gelumbauskas: Bye

**Comment by ec-mcs** [comment]
Roles that we discussed in today
1.	Main contractor (Part II A) -> Complete ESPD
2.	Group Member (Part II A) -> Complete ESPD except Part II A - b (identify procurers)
3.	Other entities who you rely on (Part II C) -> Complete ESPD like 2 
  An other entity could have again another entity which they rely on (Part II C) or a subcontractor (Part II D)  
4.	Subcontractor  who you do not rely on (Part II D) ->Only if asked by buyer Part II and Part III A/B and Part IV only for "Subcontracting Portion" (not Part V)
  A subcontractor can again have a subcontractor (Part II D) or another entity which they rely on (Part II C)

Buyer needs to specify if "Subcontracting proportion" in Selection ground should be filled out by "Main contractor" or "Consortium Member"

**Comment by ec-mcs** [comment]
Some rules

-	Buyer needs to specify if "Subcontracting proportion" in Selection ground should be filled out by "Main contractor" or "Consortium Member"
-	Consortium member -> Complete ESPD
-	Subcontractor who you rely on -> Complete ESPD
-	Subcontractor who you do not rely on -> Part II and Part III A/B and Part IV only for "Subcontracting Portion" (not Part V)

**Comment by ec-mcs** [comment]
Mockup
![untitled](https://cloud.githubusercontent.com/assets/20335285/22691321/2a44847a-ed3a-11e6-8595-0239bd838ea6.png)

**Comment by krijndeveer** [comment]
Dear all. 

Coming back to the discussion of subcontraction versus "other entities". Art. 63 of Directive 2014/24 offers economic operators (EO) the possibility to rely on the capacities of other entities, regardless of the legal nature of the links it has with them. 
Perhaps the clearest example of reliance on the capacities of others can be found in subcontracting. However, art. 63 the Directive specifically states other entities, regardless of the legal nature which is a term with a broader scope. This article is a codification of settled case-law of the CJEU. In Ballast Nedam I and Holst Italia the Court found that it was possible for an EO to rely on the capacities of other entities . The following practical circumstances where found to be in accordance with EU procurement law:

-	Holding where subsidiaries form separate legal persons.
-	Reliance on parent company of other subjects of law with which the EO has direct or indirect ties.
-	Agencies, branches, outside technicians or technical divisions; regardless of legal form
-	Other entities or undertakings which it does not own. 

Especially reliance on holdings / parent companies are not just theoretical. I therefore think we should go for "other entities"  for II C as Jose Luis suggested.

Best,
Krijn

**Comment by arocamop** [comment]
Find below the proposal of the mock-ups for sections A, C and D of Part II: Information concerning the economic operator with:

- identification  of the role of the EO that fills in the ESPD (Section A).

- for main contractors that lead a group (joint venture, consortium or other), identification of the other EO that are part of the group (Section A).

- for main contractors that rely on the capacities of other entities in order to meet the selection criteria, identification of these entities (Section C).

- for main contractors with subcontractor on whose capacity they do not rely on, identification of these subcontractors (Section D).

![image](https://cloud.githubusercontent.com/assets/24680325/22736412/464da948-edfe-11e6-80da-64de2900ac00.png)

![image](https://cloud.githubusercontent.com/assets/24680325/22736418/4d6bfe1e-edfe-11e6-9f95-94b73f03447d.png)

![image](https://cloud.githubusercontent.com/assets/24680325/22736421/5359e372-edfe-11e6-8f3a-fd1175bea721.png)

**Comment by ec-mcs** [comment]
After discussion there will be 3 roles of EOs

1.  Lead entity (Part II A) -> Complete ESPD
2.  Group Member (Part II A) -> Complete ESPD except Part II A - b (identify procurers)
3. Other entity (relied upon) (Part II C) -> Complete ESPD like 2
4. Other entity (not relied upon) (Part II D) -> Not Part IV and Part V 
  - Another entity could have again another entity which they rely on (Part II C) or a subcontractor (Part II D)

Buyer needs to specify if "Subcontracting proportion" in Selection ground should be filled out by "Main contractor" or "Consortium Member"

**Comment by ec-mcs** [comment]
Notes from the Chat room
Marc-Christopher SCHMIDT: Hi all, we will start at 13:03

Anne Katrine Mortensen: OK. Anne Katrine

Hilde Kjølset and Jan Mærøe, Difi - Norway: We hear you

Anne Katrine Mortensen: I hear you.

Hilde Kjølset and Jan Mærøe, Difi - Norway: In Norway we have a maximum of 2 levels as a general rule. But there can be situations with more than two levels.

Alba Colomer (GROW): it should be the main contractor who identifies all the entities and subcontractos involved, regardless of the relationship or levels beetween them

Jose Luis Cueva -Sapin: Ill type

Jose Luis Cueva -Sapin: My micro does not work

Jose Luis Cueva -Sapin: I do not think the whole chain of subcontractors has to be modelled in the ESPD

Jose Luis Cueva -Sapin: It is an unneeded complexity

Rudolf Maier: It should be the responsibility of the main contractor to fill in all the data for the subcontractors/entitie he need.

Timo Rantanen / Hansel / Finland: To what extent the level of "other entities" need to be defined is either the question on how many levels the CA requires to have those OR it may  b defined in  the  law. In Finland there is a nasty piece of legislation t called   Contractors Liability Act that requires the CAs in certain procedures (mainly works) to clarify all subcontracting arrangements. The rationaea of this Act is to get rid of the  "gray labour" which has been identified as a problem....  

Jose Luis Cueva -Sapin: As far as the selection of bidders is needed, it is irrelevant the chain of subcontractors

Rudolf Maier: The subcontractor has to declare if he needs somebody additional to thje maincontractor. As the main contractor has to face the consquences if one member of the chain is not suitable.

Anne Katrine Mortensen: Very difficukt to hear Timo

Jose Luis Cueva -Sapin: Further levels of subcontracting have no relationship with the contracting authority

Lois: In the UK the CA have the choice on services whether to ask for an ESPD from the subcontractor - if the CA choose this option the CA has to check the  ESPD -(only for subcontractors not relied on. If relied on for selection stage then ESPD is mandated. 

Jose Luis Cueva -Sapin: at the selection moment, no need to know the identity of further deep levels of subcontractors

Jose Luis Cueva -Sapin: nor even feasible in most cases

Lois: It would again rely on the CA's policy

Timo Rantanen / Hansel / Finland: We are typically requiring ESPDs on three levels: Main Contractor ->  Other Entity -> Other Entity. Sometimes also on two levels

Jose Luis Cueva -Sapin: at the very least we should "flatten" the chain, so all subcontractors can be declared but not the whole relationship chain

Anne Katrine Mortensen: Some CA needs/wamts to know the name and/or info of all the firms in the same team.

Timo Rantanen / Hansel / Finland: In case an entity whose capacities the main contractor relies on -  we must ask their ESPDs as the SELECTION criteria can be only checked by calculation together e.g. the turnover all relied entities

Rudolf Maier: I agree with Jose Luis. As there is a certain "Danger" that one of the subconbtrytors would not meet the criteria the main contractors tend to provide a longer list of subcontractors for the CA.

Sarah Guest: I Think the chain is needed to understand liability

Jose Luis Cueva -Sapin: from legal point of view, it is irrelevant whether it is a 2nd level or 3th level or nth level subcontratcor

Sarah Guest: and responsibility/accountability

Anne Katrine Mortensen: I agree

Jose Luis Cueva -Sapin: Only main contractor are responsible  facing the C.A.

Rudolf Maier: To Jose Luis: I agree, but all EO involved in the project have to fullfil the criteria.

Jose Luis Cueva -Sapin: I agree to Rudolf, but I think the "subcontracting level"  is not relevant

Sarah Guest: very difficult to hear. please repeat

Jose Luis Cueva -Sapin: And keeping the whole chain in the ESPD makes things much more complex than flattening the subcontracting chain

Lois: Don't we need the subcontractor on the list tocover the times when the subcontractor is not being relied on. As the definitions are at present the subcontractor not being relied on wouldn't have a role to choose, but may have been asked to complete the ESPD.

Timo Rantanen / Hansel / Finland: Onter entities can be relied on or not relied on

Timo Rantanen / Hansel / Finland: otehr

Timo Rantanen / Hansel / Finland: Other

Jose Luis Cueva -Sapin: Other entities are only relevant if relied on

Jose Luis Cueva -Sapin: If not, no need to report

Timo Rantanen / Hansel / Finland: YES YES 3! 

Jose Luis Cueva -Sapin: I think it is perfect as it is now

Timo Rantanen / Hansel / Finland: Other entity / entities

Alba Colomer (GROW): This would imply that Section II-D needs to be removed from the ESPD. Is that right?

Timo Rantanen / Hansel / Finland: The more choices there are the more confusion it generates.  BUT remember that "other entities" an be relied on or not relied on

Timo Rantanen / Hansel / Finland: yes tool box is good

Timo Rantanen / Hansel / Finland: groups do not cascade

Rudolf Maier: Often ther is an Consortia of bidders. One of them is chosen as coordinator/representative. Instead of "Group Member" the term "Consortia" could be used and the gruop memebrs are listed with their data under this point.

Timo Rantanen / Hansel / Finland: groups sign the contract jointly

Alba Colomer (GROW): Part II D?

Sarah Guest: Can a Group Member be the Head of their own group.

Timo Rantanen / Hansel / Finland: "other entitities" do not sign the contract BUT often they have other agreements / contracts with the main contractors / consortium members. AND these are called often subcontracting contracts... sorry for the consusion.... 

Timo Rantanen / Hansel / Finland: confusion

Alba Colomer (GROW): we were saying that subcontractors on wich we don not rely on do not need to fill in an ESPD. Therefore, part II - D provides no relevant information

Anne Katrine Mortensen: But even if a sub sonctractor is not relied upon a CA somtimes still wants the info of a sub sub contractor. 

Jose Luis Cueva -Sapin: AFAIK part II-D (subcontractors) is for info only, and does not play a role for selection

Alba Colomer (GROW): that's our point

Alba Colomer (GROW): therefore they should be "hidden" because they don't have to complete them

Jose Luis Cueva -Sapin: subcontractors: only "exclusion part" (part III). No "selction part" (part IV)

Lois: No only the exclusions

Timo Rantanen / Hansel / Finland: I think the original problem was weatehr to call subcontractors as subcontractor or as "other entities". I think we have now concluded taht we call those "other entities". This still needs open the question if we need to have  as well "other entities relied on" and "other entities  not relied on"

Timo Rantanen / Hansel / Finland: leaves open the question....

Jose Luis Cueva -Sapin: The logic: if main contractor does not "rely on" capabilities of a subcontractor -> no need of subcontractor part IV

Alba Colomer (GROW): @Timo: yes, because otherwise we cannot make dynamic the ESPd and hid those parts addressed to the ones who are not relied on

Jose Luis Cueva -Sapin: I agree with MC

Jose Luis Cueva -Sapin: Must distinguish:  part we rely on / subcontractor not relied on

Rudolf Maier: This is one more reason, why the main contractor should fill in also the data for the subcontractors.

Jose Luis Cueva -Sapin: subcontractors might again sub-subcontract to consortiaor whoever  but it is irrelevant for the public contract

Sarah Guest: Cannot hear please repeat

Anne Katrine Mortensen: I prefer entity as contractor for me isn´t for example a consultant.

Sarah Guest: Sounds like a good point

Anne Katrine Mortensen: Main entity ans sub-entity and sub-sub-entity

Rudolf Maier: Often consortia are taking part at the procedure. In this case the consortia is the “main contractor”. There must be a possibility to state that the bidder is a consortia and to list the members of this consortia

Timo Rantanen / Hansel / Finland: Rudolf: there is the possibility now

Sarah Guest: we use the term LEAD CONTRACTOR

Timo Rantanen / Hansel / Finland: LEAD contractor is good

Jose Luis Cueva -Sapin: the Regulation says that if Consortia, every member must fill its own ESPD. So, no "Consortium ESPD" but "Consortium member" ESPD

Alba Colomer (GROW): how do you identify then that I am a sole contractor?

Jose Luis Cueva -Sapin: There is a box in the ESPD form

Rudolf Maier: That sounds OK.

Timo Rantanen / Hansel / Finland: but how does it translate to other languages is an intersting Q. Might come out from the translators as complete jibbrish in Finnish.... LEAD may also mean LIVING....

Anne Katrine Mortensen: I mean that for us in Denmark a contractor is for ex an electrician or painter not a consultant.

Timo Rantanen / Hansel / Finland: :-)

Hilde Kjølset and Jan Mærøe, Difi - Norway: The naming will differ with the different languages anyway.

Anne Katrine Mortensen: We need a word that is all three kinds of procurement types.

Timo Rantanen / Hansel / Finland: Yes not is ok

Timo Rantanen / Hansel / Finland: now

Jose Luis Cueva -Sapin: Economic Operator is the all-encompassing term used by the Directive

Timo Rantanen / Hansel / Finland: yes now its ok

Jose Luis Cueva -Sapin: Art. 2-1-(10)

Sarah Guest: Supporting  Contractor - Upon ... 

Anne Katrine Mortensen: Lead entity

Rudolf Maier: As a starting point.

Stefan Van der Meulen (Belgium): as Hilde already remarked, we are now playing on naming in english - in other languages the discussion will probably be restarted again...

Stefan Van der Meulen (Belgium): but OK with this

Jose Luis Cueva -Sapin: When single bidder? Lead entity?

Timo Rantanen / Hansel / Finland: remember: it doesn not matter what we call these players as long as they are defined and understood. Tooltips necessary

Timo Rantanen / Hansel / Finland: J A P A N!

Timo Rantanen / Hansel / Finland: :-)

Timo Rantanen / Hansel / Finland: of course sakura weekend

Jose Luis Cueva -Sapin: very difficult for me 28 and 29 march

Timo Rantanen / Hansel / Finland: April is good....

Jose Luis Cueva -Sapin: 30-31 March?

Rudolf Maier: WOuld this be a net meeting?

Jose Luis Cueva -Sapin: My problem is with last Tuesday-Wednesday every month

Jose Luis Cueva -Sapin: Ok

Rudolf Maier: OK

Hilde Kjølset and Jan Mærøe, Difi - Norway: OK, bye bye

Jose Luis Cueva -Sapin: thanks. Bye

Stefan Van der Meulen (Belgium): bye

**Comment by ec-mcs** [comment]
@arocamop  could you please
- Create a new wiki page with the title EO roles (if you have a better one please feel to change it)
- Update the mockup with the new terms
- Copy the mockup I did on the subcontractor (you can do one in a nicer way as well)
- Update the model with the requirements if necessary and provide an example
- Show with the model how systems could link technically ESPD together

**Comment by arocamop** [comment]
Please find below the mock-ups modified as commented in our last session:

![mu_part_a_eo](https://cloud.githubusercontent.com/assets/24680325/22935901/31104204-f2d4-11e6-8ceb-19caff443a12.png)

![mu_part_c_eo](https://cloud.githubusercontent.com/assets/24680325/22935909/3796c148-f2d4-11e6-88a7-ecc28b04a56e.png)

![mu_part_d_eo](https://cloud.githubusercontent.com/assets/24680325/22935920/3c36c27a-f2d4-11e6-80cc-241e57112104.png)

**Comment by arocamop** [comment]
We've realised that the sequence of fields for the Economic Operator was not logic, since we required the role without knowing whether the Economic Operator was a sole contractor or not. Therefore, we've prepared a new proposal to show how it should work in our opinion. To be discussed, please.

![mu_part2_a_eo](https://cloud.githubusercontent.com/assets/24680325/22966558/fba5569c-f362-11e6-8eac-737328788235.png)

**Comment by arocamop** [comment]
Please find below the mock-up for section A modified as agreed in our last session (as commented, mock-ups for sections C and D were OK and, therefore, have not been modified):

![mu_part2_a_eo](https://cloud.githubusercontent.com/assets/24680325/23119023/c06cab0a-f756-11e6-8bf4-bf2ae15ad95e.png)

**Comment by paulakeen** [comment]
Please find the details of the final decision in https://github.com/ESPD/ESPD-EDM/wiki/5.-EO-roles
