### ISSUE TITLE
Groups - Group Type Codes Missing

### ISSUE THREAD

**Issue by millstream** [OP-TED/ESPD-EDM#71]
For the element cac:TenderingCriterionPropertyGroup, the CriteriaGroupTypeCode which replaces PI is not in the code list. I believe below is a mistake, as the CriteriaType only relates to the actual criteria. Please advice

cbc:CriteriaGroupTypeCode	- A code signifying the type of group. ESPD: Compulsory use of the Code List “CriteriaType”.

**Comment by paulakeen** [comment]
You're right! The CriteriaType does typify the Criterion, not the CriterionGroup. Some will use this CriteriaGroupTrypeCode in replacement of the Processing Instruction (@pi) attribute we had in the previous version 1.0.2. Therefore you will have to use your own codes as they are addressed to your own software application and internal treatment.

The documentation has been corrected as follows (beware that the ESP cardinality also has been modified):

cbc:CriteriaGroupTypeCode	Code	0..1	**0..1**	A code signifying the type of group. Can be used to specify the data structure or the way of processing of the group of criteria. ESPD-EDM does not provide a Code List for this.

**Comment by jerouris** [comment]
So, according to the comment above, there will be no interoperable way in validating when a criteriaGroup it should be fullfiled/showed between applications or there is another mechanism to promote that?

**Comment by millstream** [comment]
There is a PI column in the criteriataxonomy document, but you will have to make the codes up for the new types. From what I can see there are 2, repeatable and no answer required.

**Comment by paulakeen** [comment]
I'm not understanding the issue: nothing, except the naming, is different from the previous version....you can continue using the code GROUP_FULFILLED.ON_TRUE as you were doing up to now, but in the cbc:CriteriaGroupTypeCode instead of the @pi attribute. Jerry, this is what you, Virgiliu and I negotiated as the solution to replace the PI attribute in the version 2.0.0.

May be your point is that you expect us to include the GROUP_FULFILLED.ON_TRUE/FALSE codes as normative in our specification? I wouldn't recommend this...even more these software-specific aspects should be treated in the ext:UBLExtensions section of the document.

**Comment by jerouris** [comment]
Yes, that is correct. This is what we agreed for version 2.0. However, I would also expect to have at least those two values defined as normative, with examples and proper documentation. Otherwise, with the self-contained artifacts, the systems parsing the artifacts will be in no position to understand the flow and even validate it. 

Why you are not recommending the definition of these codes in the new specification? What is the caveat?

**Comment by paulakeen** [comment]
I must admit that from the moment we state as "normative" the way you have to state the exclusion criteria in a negative way then a technical solution to treat these criteria should be proposed even if for illustration purposes. This also would help migrate from version 1.0.2 to version 2.0.0. 

So this is what we'll do (please confirm you agree):

1. We'll keep the GROUP_FULFILLED.ON_TRUE/FALSE codes in the new CriteriaTaxonomy spread-sheet Althoguht not linked to attribute @pi but to the cbc:CriteriaGroupTypeCode element.
2. We'll enrich the documentation to explain how this can be used and we'll make reference to has it was used in the previous version, so the migration is facilitated
3. We'll add the two codes in a new tab of the CodeList spread-sheet

BTW, I'll close #Issue 74 as the latest version of UBL-2,.2 already integrates our change request ([https://www.oasis-open.org/committees/document.php?document_id=60834](url)).

**Comment by millstream** [comment]
This would be helpful. The problem occurs when uploading an xml request/response, there is no way to figure out the processing instruction without it.

**Comment by paulakeen** [comment]
Solved in version 2.0.0.
