### ISSUE TITLE
Multple Response Values

### ISSUE THREAD

**Issue by millstream** [OP-TED/ESPD-EDM#77]
There does not appear to be a way of linking a ResponseValue with a specific TenderingCriterionProperty if there are multiple ResponseValues. Can you please advise how we should handle this?

**Comment by paulakeen** [comment]
In the XML example we provided about references the possibility of having multiple answers (lots ids, in the example) is illustrated. However I just noticed that the property ID has not been referred to correctly. The correct snippet would be this one instead:

**Property:**

`<cac:TenderingCriterionProperty>
					<cbc:ID schemeAgencyID="EU-COM-GROW" schemeVersionID="2.0.0">09cf676d-377d-4edb-b927-d9adb53280e2</cbc:ID>
					<cbc:Description>Lots these reference applies to</cbc:Description>
					<cbc:ValueDataTypeCode listID="ResponseDataType" listAgencyID="EU-COM-GROW" listVersionID="2.0.0">IDENTIFIER_COLLECTION</cbc:ValueDataTypeCode>
</cac:TenderingCriterionProperty>
`

**Answers**

`	
	<cac:TenderingCriterionResponse>
		<cbc:ValidatedCriterionRequirementID schemeAgencyID="EU-COM-GROW" schemeVersionID="2.0.0">09cf676d-377d-4edb-b927-d9adb53280e2</cbc:ValidatedCriterionRequirementID>
		<cbc:ConfidentialityLevelCode listID="ConfidentialityLevel" listAgencyID="EU-COM-GROS" listVersionID="2.0.0">CONFIDENTIAL</cbc:ConfidentialityLevelCode>
		<cac:ResponseValue>
			<cbc:ResponseID>LOT5</cbc:ResponseID>
		</cac:ResponseValue>
		<cac:ResponseValue>
			<cbc:ResponseID>LOT6</cbc:ResponseID>
		</cac:ResponseValue>
		<cac:ResponseValue>
			<cbc:ResponseID>LOT7</cbc:ResponseID>
		</cac:ResponseValue>
	</cac:TenderingCriterionResponse>`

**Comment by millstream** [comment]
Sorry but that is not the issue I am referring to.

If a criteria group has 4 properties for example, how do we know which response value to associate with each property?

For example, if we were uploading the response document for the following criteria, how would we know which property to associate the value with?

005eb9ed-1347-4ca3-bb29-9bc0db64e1ab
Has the economic operator itself or any person ........
C1/G1/G1.1/P1
C1/G1/G1.1/P2
C1/G1/G1.1/P3
C1/G1/G1.1/P4

**Comment by paulakeen** [comment]
In the QualificationApplicationResponse document, each answer is linked to one criterion property. This is done using the element cac:TenderingCriterionResponse/cbc:ValidatedCriterionRequirementID, where the `ValidatedCriterionRequirementID` is the same value than the one in `cac:TenderingCriterionProperty/cbc:ID`.

Thus, in the example below (PART I) you can see a sub-group with 6 Properties: Reference description, Total amount, Activity of the economic operator, specific amount, Period, Confidential. Each of these properties has its own compulsory Universal Unique Identifier (c7bd85b8-6e65-416c-90b8-f64d551bea24, 18606b15-6a4a-4b7a-82e5-aff5c4d065ab, 695810f8-f788-4bda-97d6-53d3e2dd5796, ee486082-93fa-4c17-8920-fdf01b890bd1, cc1da737-6c4e-4f4e-821d-c260029058f6, 5ca58d66-3ef1-4145-957c-45d5b18a837f). 

In the fragment of XML code of PART II, you can see a collection of answers each one with the UUID and the type of expected response (and response value) for each Property of the subgroup in PART I.

**PART I, a subgroup of 6 properties)**

`<cac:SubsidiaryTenderingCriterionPropertyGroup>
					<cbc:ID schemeAgencyID="EU-COM-GROW" schemeVersionID="2.0.0">6a0dea4a-4ce7-447b-81e7-1039e4e29445</cbc:ID>
					<cbc:PropertyGroupTypeCode listID="CriterionElementType" listAgencyID="EU-COM-GROW" listVersionID="2.0.0">ANSWER_GROUP</cbc:PropertyGroupTypeCode>	
					<cac:TenderingCriterionProperty>
						<cbc:ID schemeAgencyID="EU-COM-GROW" schemeVersionID="2.0.0">c7bd85b8-6e65-416c-90b8-f64d551bea24</cbc:ID>
						<cbc:Description>Reference description</cbc:Description>
						<cbc:ValueDataTypeCode listID="ResponseDataType" listAgencyID="EU-COM-GROW" listVersionID="2.0.0">DESCRIPTION</cbc:ValueDataTypeCode>
					</cac:TenderingCriterionProperty>
					<cac:TenderingCriterionProperty>
						<cbc:ID schemeAgencyID="EU-COM-GROW" schemeVersionID="2.0.0">18606b15-6a4a-4b7a-82e5-aff5c4d065ab</cbc:ID>
						<cbc:Description>Total amount</cbc:Description>
						<cbc:ValueDataTypeCode listID="ResponseDataType" listAgencyID="EU-COM-GROW" listVersionID="2.0.0">AMOUNT</cbc:ValueDataTypeCode>
					</cac:TenderingCriterionProperty>
					<cac:TenderingCriterionProperty>
						<cbc:ID schemeAgencyID="EU-COM-GROW" schemeVersionID="2.0.0">695810f8-f788-4bda-97d6-53d3e2dd5796</cbc:ID>
						<cbc:Description>Activity of the economic operator</cbc:Description>
						<cbc:ValueDataTypeCode>DESCRIPTION</cbc:ValueDataTypeCode>
					</cac:TenderingCriterionProperty>
					<cac:TenderingCriterionProperty>
						<cbc:ID schemeAgencyID="EU-COM-GROW" schemeVersionID="2.0.0">ee486082-93fa-4c17-8920-fdf01b890bd1</cbc:ID>
						<cbc:Description>Specific amount</cbc:Description>
						<cbc:ValueDataTypeCode listID="ResponseDataType" listAgencyID="EU-COM-GROW" listVersionID="2.0.0">AMOUNT</cbc:ValueDataTypeCode>
					</cac:TenderingCriterionProperty>
					<cac:TenderingCriterionProperty>
						<cbc:ID schemeAgencyID="EU-COM-GROW" schemeVersionID="2.0.0">cc1da737-6c4e-4f4e-821d-c260029058f6</cbc:ID>
						<cbc:Description>Period</cbc:Description>
						<cbc:ValueDataTypeCode listID="ResponseDataType" listAgencyID="EU-COM-GROW" listVersionID="2.0.0">PERIOD</cbc:ValueDataTypeCode>
					</cac:TenderingCriterionProperty>
					<cac:TenderingCriterionProperty>
						<cbc:ID schemeAgencyID="EU-COM-GROW" schemeVersionID="2.0.0">5ca58d66-3ef1-4145-957c-45d5b18a837f</cbc:ID>
						<cbc:Description>Confidential</cbc:Description>
						<cbc:ValueDataTypeCode listID="ResponseDataType" listAgencyID="EU-COM-GROW" listVersionID="2.0.0">INDICATOR</cbc:ValueDataTypeCode>
					</cac:TenderingCriterionProperty>
</cac:SubsidiaryTenderingCriterionPropertyGroup>`

**PART II, the corresponding answers:**

**Notice that** because in the above example the user was asked whether the answers were to be treated as confidential all the responses have been marked as confidential. This is a bit redundant and may be managed in different ways by different applications. In fact if only one response is signaled as confidential all the Criterion Properties, including the evidences referrenced by the Criterion SHOULD be treated as confidential.


`	
	<cac:TenderingCriterionResponse>
		<cbc:ValidatedCriterionRequirementID schemeAgencyID="EU-COM-GROW" schemeVersionID="2.0.0">c7bd85b8-6e65-416c-90b8-f64d551bea24</cbc:ValidatedCriterionRequirementID>
		<cbc:ConfidentialityLevelCode listID="ConfidentialityLevel" listAgencyID="EU-COM-GROW" listVersionID="2.0.0">CONFIDENTIAL</cbc:ConfidentialityLevelCode>
		<cac:ResponseValue>
			<cbc:Description>DoD consultancy on IT convergence</cbc:Description>
		</cac:ResponseValue>
	</cac:TenderingCriterionResponse>
	
	<cac:TenderingCriterionResponse>
		<cbc:ValidatedCriterionRequirementID schemeAgencyID="EU-COM-GROW" schemeVersionID="2.0.0">18606b15-6a4a-4b7a-82e5-aff5c4d065ab</cbc:ValidatedCriterionRequirementID>
		<cbc:ConfidentialityLevelCode listID="ConfidentialityLevel" listAgencyID="EU-COM-GROW" listVersionID="2.0.0">CONFIDENTIAL</cbc:ConfidentialityLevelCode>
		<cac:ResponseValue>
			<cbc:ResponseAmount currencyID="EUR">15000</cbc:ResponseAmount>
		</cac:ResponseValue>
	</cac:TenderingCriterionResponse>
	
	<cac:TenderingCriterionResponse>
		<cbc:ValidatedCriterionRequirementID schemeAgencyID="EU-COM-GROW" schemeVersionID="2.0.0">695810f8-f788-4bda-97d6-53d3e2dd5796</cbc:ValidatedCriterionRequirementID>
		<cbc:ConfidentialityLevelCode listID="ConfidentialityLevel" listAgencyID="EU-COM-GROW" listVersionID="2.0.0">CONFIDENTIAL</cbc:ConfidentialityLevelCode>
		<cac:ResponseValue>
			<cbc:Description>Military satellite software development</cbc:Description>
		</cac:ResponseValue>
	</cac:TenderingCriterionResponse>
	
	<cac:TenderingCriterionResponse>
		<cbc:ValidatedCriterionRequirementID schemeAgencyID="EU-COM-GROW" schemeVersionID="2.0.0">ee486082-93fa-4c17-8920-fdf01b890bd1</cbc:ValidatedCriterionRequirementID>
		<cbc:ConfidentialityLevelCode listID="ConfidentialityLevel" listAgencyID="EU-COM-GROW" listVersionID="2.0.0">CONFIDENTIAL</cbc:ConfidentialityLevelCode>
		<cac:ResponseValue>
			<cbc:ResponseAmount currencyID="EUR">75912.12</cbc:ResponseAmount>
		</cac:ResponseValue>
	</cac:TenderingCriterionResponse>
	
	<cac:TenderingCriterionResponse>
		<cbc:ValidatedCriterionRequirementID schemeAgencyID="EU-COM-GROW" schemeVersionID="2.0.0">cc1da737-6c4e-4f4e-821d-c260029058f6</cbc:ValidatedCriterionRequirementID>
		<cbc:ConfidentialityLevelCode listID="ConfidentialityLevel" listAgencyID="EU-COM-GROW" listVersionID="2.0.0">CONFIDENTIAL</cbc:ConfidentialityLevelCode>
		<cac:ApplicablePeriod>
			<cbc:StartDate>2014-03-02</cbc:StartDate>
			<cbc:EndDate>2015-01-04</cbc:EndDate>
		</cac:ApplicablePeriod>
	</cac:TenderingCriterionResponse>
		
	<cac:TenderingCriterionResponse>
		<cbc:ValidatedCriterionRequirementID schemeAgencyID="EU-COM-GROW" schemeVersionID="2.0.0">5ca58d66-3ef1-4145-957c-45d5b18a837f</cbc:ValidatedCriterionRequirementID>
		<cbc:ConfidentialityLevelCode listID="ConfidentialityLevel" listAgencyID="EU-COM-GROW" listVersionID="2.0.0">CONFIDENTIAL</cbc:ConfidentialityLevelCode>
		<cac:ResponseValue><cbc:ResponseIndicator>true</cbc:ResponseIndicator></cac:ResponseValue>
	</cac:TenderingCriterionResponse>`

Different akward situations may occur that MUST be avoided. All of them SHOULD raise a fatal exception and the document should be rejected. We will provide Schematron files to control these situations:

1) one answer pointing at a property with a type of data different to the one specified in the property
2) one answer pointing at a property ID that does not exist in the XML
3) one answer with not Property ID value
4) two or more Properties have the same ID
5) two or more answers point at the same ID

I hope this helps to clarify how to link each answer to each property.

**Comment by millstream** [comment]
Thanks for the update.
I can now see how you are linking them, however not sure this is the best way to do it.
This means that there is no relationship really between the parent criteria id and any properties in terms of the response, we just have a bunch of responses.
I would suggest that the additional responses are either children of the parent, or that we just use the ID value to store the property id. 

OPTION 1 - would require schema change
```
<cac:TenderingCriterionResponse> 
    <cbc:ValidatedCriterionRequirementID schemeAgencyID="EU-COM-GROW" schemeVersionID="2.0.0">c7bd85b8-6e65-416c-90b8-f64d551bea24</cbc:ValidatedCriterionRequirementID> 
    <cbc:ConfidentialityLevelCode listID="ConfidentialityLevel" listAgencyID="EU-COM-GROW" listVersionID="2.0.0">CONFIDENTIAL</cbc:ConfidentialityLevelCode> 
    <cac:ResponseValue> <cbc:Description>DoD consultancy on IT convergence</cbc:Description> </cac:ResponseValue>
        <!-- Child reponse -->
        <cac:TenderingCriterionResponse> <cbc:ValidatedCriterionRequirementID schemeAgencyID="EU-COM-GROW" schemeVersionID="2.0.0">18606b15-6a4a-4b7a-82e5-aff5c4d065ab</cbc:ValidatedCriterionRequirementID> <cbc:ConfidentialityLevelCode listID="ConfidentialityLevel" listAgencyID="EU-COM-GROW" listVersionID="2.0.0">CONFIDENTIAL</cbc:ConfidentialityLevelCode> <cac:ResponseValue> <cbc:ResponseAmount currencyID="EUR">15000</cbc:ResponseAmount> </cac:ResponseValue> </cac:TenderingCriterionResponse> <!-- Activity of the economic operator --> <cac:TenderingCriterionResponse>
</cac:TenderingCriterionResponse> 
```
OPTION 2- Use existing ID of the responsevalue
```
<cac:TenderingCriterionResponse> 
    <cbc:ValidatedCriterionRequirementID schemeAgencyID="EU-COM-GROW" schemeVersionID="2.0.0">c7bd85b8-6e65-416c-90b8-f64d551bea24</cbc:ValidatedCriterionRequirementID> 
    <cbc:ConfidentialityLevelCode listID="ConfidentialityLevel" listAgencyID="EU-COM-GROW" listVersionID="2.0.0">CONFIDENTIAL</cbc:ConfidentialityLevelCode> 
    <cac:ResponseValue>
          <!-- WE ARE USING ID TO STORE THE PROPERTY ID (cac:TenderingCriterionProperty) -->
          <cbc:ID schemeAgencyID="EU-COM-GROW" schemeVersionID="2.0.0">PropertyID</cbc:ID>
          <cbc:ResponseIndicator>...</cbc:ResponseIndicator>
    </cac:ResponseValue>
    <cac:ResponseValue>
          <!-- WE ARE USING ID TO STORE THE PROPERTY ID (cac:TenderingCriterionProperty) -->
          <cbc:ID schemeAgencyID="EU-COM-GROW" schemeVersionID="2.0.0">PropertyID</cbc:ID>
          <cbc:ResponseIndicator>...</cbc:ResponseIndicator>
    </cac:ResponseValue>
</cac:TenderingCriterionResponse>
```

**Comment by paulakeen** [comment]
I see your point. But I have a third proposal for you: let's propose UBL-2.2 adding two new elements to the `cac:TenderingCriterionResponse`: (i) a `cbc:TenderingCriterionID` and (ii) a `cbc:ParentPropertyGroupID`. This way you can refer not only to the group of properties but also to the criterion.

What do you think of my proposal?

**About the two options you propose:** 

Option 1: the ESPD-1.0.2 (and previous versions) were modelled as you propose, having the answers inside the criterion. UBL-2.2 decided to separate the answer from the criterion because that way the QualificationApplicationResponse may omit (do not have to replicate) all the content in the QualificationApplicationRequest. This way one QualificationApplicationResponse document may contain only "the bunch of responses", as you say (the ESPD specification does not allow for this, as the Response is seen as a [signed] self-declaration and from the legal point of view the Economic Operator signs its awareness of what is requests and the correspondig answers...something imposed by the "legal-guys", say).

Option 2: If we adopted your approach we would be perverting the semantics of the elements inside the TenderingCriterionResponse. The ID of th the ResponseValue has to be unique and particular of the response, it identifies uniquely the response, hence it should not point at the PropertyID. 

So if you agree with my solution I can propose it to UBL-2.2 the soonest. I have a meeting with them this week/next week to discuss other two "additions" (as provided we do not introduce "change" requests adding new elements should not impact anyone).

**Comment by millstream** [comment]
This would be great!

**Comment by paulakeen** [comment]
UBL-2.2 did not accepted the proposal. They insist on the idea that the current model supports well the linking of each response to a particular question.
